function Behaviour(f,k,e,m,v,L,ua){function w(){this.mouseDown=M;this.mouseMove=N;this.mouseUp=O}function M(a){this.start=new Utils.Point(a.x,a.y);e.showOver();f.beginBlockSelect();e.redraw()}function N(a){var b,c,d;b=Math.min(this.start.x,a.x);d=Math.max(this.start.x,a.x);c=Math.min(this.start.y,a.y);a=Math.max(this.start.y,a.y);b=new Utils.Box(b,c,d,a);e.selectBlock(b);f.blockSelect(b)&&e.redraw()}function O(a){e.selectBlock(null);e.hideOver()}function x(a,b,c){this.isLeft=a;this.id=b;this.dims=
c;this.mouseMove=P;this.mouseDown=Q;this.mouseUp=R}function Q(a){this.start=new Utils.Point(a.x,a.y);e.showOver()}function P(a){a=this.dims.w+(this.isLeft?-a.dx:a.dx);this.width=a=Math.max(a,Config.MIN_ICON_WIDTH);this.dims.w=a;var b=this.dims;a=new Utils.Box(b.x-a,b.y-b.h,b.x+a,b.y+b.h);e.selectBlock(a)}function R(a){e.hideOver();this.width&&(f.setItemWidth(this.id,this.width),a.handled=!0,e.redraw())}function S(a,b,c){this.type=a;this.id=b;this.dims=c;this.mouseMove=T;this.mouseDown=U;this.mouseUp=
V}function U(a){this.start=new Utils.Point(a.x,a.y);e.showOver()}function T(a){var b=0,c=a.dx/2,d=a.dy/2;a=this.dims;b=this.type;if("FR_LU"===b)dx=c,dy=d,b=-c,c=-d;else if("FR_UP"===b)dx=0,dy=d,b=0,c=-d;else if("FR_RU"===b)dx=c,dy=d,b=c,c=-d;else if("FR_RI"===b)dx=c,dy=0,b=c,c=0;else if("FR_RD"===b)dx=c,dy=d,b=c,c=d;else if("FR_DO"===b)dx=0,dy=d,b=0,c=d;else if("FR_LD"===b)dx=c,dy=d,b=-c,c=d;else{if("FR_LE"!==b)throw"Unexpected switch value: "+b;dx=c;dy=0;b=-c;c=0}b=a.w+b;c=a.h+c;d=Config.SIZE_SNAP;
b<d&&(b=a.w,dx=0);c<d&&(c=a.h,dy=0);a.x+=dx;a.y+=dy;a.w=b;a.h=c;a=new Utils.boxFromPoint(a.x,a.y,a.w,a.h);e.selectBlock(a)}function V(a){e.hideOver();f.setFreeItemSize(this.id,this.dims.x,this.dims.y,this.dims.w,this.dims.h);a.handled=!0;e.redraw()}function y(a,b){this.type=a;this.id=b;this.mouseMove=W;this.mouseDown=X;this.mouseUp=Y}function X(a){this.moved=!1}function W(a){this.moved=!0;f.moveHandle(this.id,this.type,a.dx,a.dy,a.x,a.y);e.redraw();a.handled=!0}function Y(a){this.moved&&(f.saveHandlePos(this.id),
a.handled=!0,e.redraw())}function Z(a){this.link=a;this.mouseDown=function(){};this.mouseMove=function(){};this.mouseUp=function(b){b.handled=!0;HtmlUtils.openInNewTab(a)}}function z(a,b,c){this.isLeft=a;this.id=b;this.dims=c;this.left=c.x-c.w;this.right=c.x+c.w;this.width=2*c.w;this.mouseMove=aa;this.mouseDown=ba;this.mouseUp=ca}function ba(a){this.start=new Utils.Point(a.x,a.y);e.showOver()}function aa(a){var b,c;c=this.width+(this.isLeft?-a.dx:a.dx);this.width=c=Math.max(c,2*Config.MIN_ICON_WIDTH);
b=this.dims;a=b.y-b.h;var d=b.y+b.h;this.isLeft?(b=this.right-c,c=this.right):(b=this.left,c=this.left+c);a=new Utils.Box(b,a,c,d);e.selectBlock(a)}function ca(a){e.hideOver();if(this.width){var b=Utils.snapUp(this.width/2);f.setItemWidth(this.id,b);a.handled=!0;e.redraw()}}function da(){this.mouseDown=ea;this.mouseMove=fa;this.mouseUp=ga}function ea(a){this.moved=!1;(a=f.findVisualItem(a.x,a.y))&&f.startVisualDrag(a.id)}function fa(a){this.moved=!0;var b=e.getVisibleBox();f.visualDrag(a.dx,a.dy,
b);e.redraw()}function ga(a){this.moved&&(f.endVisualDrag(),e.redraw())}function l(a){this.target=a;this.mouseMove=ha;this.mouseUp=ia;this.mouseDown=ja}function ja(a){this.snapX=new Utils.Snapper(Config.SNAP);this.snapY=new Utils.Snapper(Config.SNAP);A(a);this.target.mouseDown(a)}function ha(a){this.snapX.snapMove(a.dx);this.snapY.snapMove(a.dy);if(this.snapX.step||this.snapY.step)A(a),this.target.mouseMove({x:a.x,y:a.y,dx:this.snapX.snapped,dy:this.snapY.snapped})}function ia(a){this.target.mouseUp(a)}
function ka(a){this.link=a;this.mouseDown=function(){};this.mouseMove=function(){};this.mouseUp=function(b){b.handled=!0;m.openSub(a)}}function B(a,b,c,d){if(!a)throw Error("chooseDragger: type is null, id: "+b);a===Const.DRN_MOVE||a===Const.DRN_MOVE_ALL?(a=new da,a=new l(a)):a===Const.MIND_SIZE_L?(a=new z(!0,b,c),a=new l(a)):a===Const.MIND_SIZE_R?(a=new z(!1,b,c),a=new l(a)):a===Const.DRN_SIZE_L?(a=new x(!0,b,c),a=new l(a)):a===Const.DRN_SIZE_R?(a=new x(!1,b,c),a=new l(a)):a===Const.LINK?a=new Z(d):
a===Const.SUB?a=new ka(d):a===Const.DRN_SOCKET?a=new la(b):"H_EW"===a?a=new y(a,b):(a=a===Const.FR_0||a===Const.FR_1||a===Const.LINE_START||a===Const.LINE_END?new y(a,b):new S(a,b,c),a=new l(a));return a}function C(a){v.clearTimeout(a)}function p(a){a=f.mouseClick(a.x,a.y);m.click();a.mustRedraw&&e.redraw()}function D(a,b){var c=Math.abs(b.cx-a.cx),d=Math.abs(b.cy-a.cy);return Math.max(c,d)}function E(a){var b=a.x;a=a.y;var c=f.canEditText(b,a);c&&f.startEditTextAt(c,b,a)}function F(a,b){for(var c=
0,d=0,e=a.length;d<e;){var f=a[d],c=f.type;"menu"===c?F(f.items,b):"separator"!==c&&(f.code=ma(f.code,b,f.text));d++}}function G(a){a=e.toDiagram(a);H(a);I(a)}function na(a){var b=0;return a?(b=a.type,b===Const.DRN_MOVE||b===Const.DRN_MOVE_ALL?"move":b===Const.LINK||b===Const.SUB?"pointer":b===Const.DRN_SIZE_L||b===Const.DRN_SIZE_R||b===Const.MIND_SIZE_L||b===Const.MIND_SIZE_R?"ew-resize":b===Const.LINE_START||b===Const.LINE_END?"move":(a=oa[a.type])?a:"default"):"default"}function u(){k.fast=!1;
e.finishZoom();m.onFinishZoom()}function n(a,b,c){a.timer&&(C(a.timer),a.timer=null);a.timer=q(a,Config.WHEEL_TIMEOUT);var d;d=b.delta;var f=(new Date).getTime();a.prev?f-a.prev<Config.WHEEL_THROTTLE?a=0:(a.prev=f,a=Config.WHEEL_STEP):(a.prev=f,a=Config.WHEEL_STEP);0>d&&(a=-a);d=a;0!=d&&(c?(k.fast=!0,e.zoomBy(d)):(b.shiftKey?(b=d,d=0):b=0,c=e.getZoom(),b=Math.floor(b/c),d=Math.floor(d/c),e.scrollBy(b,d)))}function H(a){HtmlUtils.unfocus();g.mouseDown(a)}function I(a){g.mouseUp(a)}function r(){g=pa=
new qa;J=new ra;t=new sa;h=new ta}function K(a,b,c,d,e,g){p({x:a,y:b});if(e||!g)a=f.buildMenuAt(a,b),a.menu&&0<a.menu.length&&(b={rows:a.menu},F(a.menu,!0),L(c,d,b,G,a.item))}function q(a,b){return v.setTimeout(function(){a.timeout()},b)}function A(a){a.x=Utils.snapPos(a.x);a.y=Utils.snapPos(a.y)}function ma(a,b,c){return function(d,f){CallTrace.reset();c&&CallTrace.add("cm:"+c);a(d,f);e.hideOver();e.redraw();b&&m.click()}}function qa(){var a=this;a.type_name="MouseRoot";a.state="Idle";a.mouseDown=
function(b){var c=a.state;if("Idle"==c)c=0,c=b.button,0===c?(a.downEvt=b,c=f.findDraggable(b.x,b.y),a.moved=0,a.old=c,a.dragger=c?B(c.type,c.id,c.dims,c.data):new w,a.dragger.mouseDown(b),a.state="LeftDrag"):1===c?a.state="MiddleDrag":2===c?(c=f.findDraggable(b.x,b.y),a.state=c?c.type==Const.DRN_SOCKET?"Idle":"RightDrag":"RightDrag"):a.state="Idle";else if("LeftDrag"==c)a.state="LeftDrag";else if("AfterClick"==c)0==b.button&&((c=f.findVisualItem(b.x,b.y))&&a.old&&a.old.id==c.id?E(b):p(b)),a.state=
"Idle";else if("MiddleDrag"==c)a.state="MiddleDrag";else if("RightDrag"==c)a.state="RightDrag";else return null};a.mouseMove=function(b){var c=a.state;if("Idle"==c)b=f.findVisualItem(b.x,b.y),b=na(b),e.setCursor(b),a.state="Idle";else if("LeftDrag"==c)a.moved=D(b,a.downEvt),a.moved>Config.MOUSE_START&&a.dragger.mouseMove(b),a.state="LeftDrag";else if("AfterClick"==c)a.state="AfterClick";else if("MiddleDrag"==c)e.scrollBy(b.dx,b.dy),a.state="MiddleDrag";else if("RightDrag"==c)a.state="RightDrag";else return null};
a.mouseUp=function(b){var c=a.state;if("Idle"==c)a.state="Idle";else if("LeftDrag"==c)a.dragger.mouseUp(b),a.moved>Config.MOUSE_START?a.state="Idle":b.handled?a.state="Idle":(p(b),q(a,Config.DOUBLE_CLICK),a.state="AfterClick");else if("AfterClick"==c)a.state="Idle";else if("MiddleDrag"==c)a.state="Idle";else if("RightDrag"==c)K(b.x,b.y,b.cx,b.cy,!0),a.state="Idle";else return null};a.timeout=function(b){if("AfterClick"==a.state)a.state="Idle";else return null}}function ra(){var a=this;a.type_name=
"WheelScroller";a.state="idle";a.mouseWheel=function(b){var c=a.state;if("idle"==c)b.ctrlKey?(n(a,b,!0),a.state="zooming"):(n(a,b,!1),a.state="panning");else if("panning"==c)n(a,b,!1),a.state="panning";else if("zooming"==c)b.ctrlKey?(n(a,b,!0),a.state="zooming"):(u(),n(a,b,!1),a.state="panning");else return null};a.timeout=function(b){b=a.state;if("idle"==b)a.state="idle";else if("panning"==b)e.finishScroll(),a.state="idle";else if("zooming"==b)u(),a.state="idle";else return null}}function la(){var a=
this;a.type_name="SocketClicker";a.state="idle";a.mouseDown=function(b){var c=a.state;if("idle"==c)(b=f.findSocket(b.x,b.y))?(a.socket=b,f.fireSocket(b),e.redraw(),a.state="onsocket"):a.state="idle";else if("onsocket"==c)a.state="onsocket";else if("offsocket"==c)a.state="offsocket";else return null};a.mouseMove=function(b){var c=a.state;if("idle"==c)a.state="idle";else if("onsocket"==c)f.findSocket(b.x,b.y)==a.socket?a.state="onsocket":(f.darkenSocket(a.socket),e.redraw(),a.state="offsocket");else if("offsocket"==
c)(b=f.findSocket(b.x,b.y))?b==a.socket?(f.fireSocket(b),e.redraw(),a.state="onsocket"):a.state="offsocket":a.state="offsocket";else return null};a.mouseUp=function(b){var c=a.state;if("idle"==c)a.state="idle";else if("onsocket"==c)f.clickSocket(a.socket),b.handled=!0,e.redraw(),a.state="idle";else if("offsocket"==c)a.state="idle";else return null}}function sa(){var a=this;a.type_name="Toucher";a.state="Idle";a.timeout=function(b){if("LongOrShortTap"==a.state)a.moved>Config.TOUCH_START?a.state="Drag":
(b=a.downEvt,p(b),E(b),a.state="Idle");else return null};a.touchend=function(b){var c=a.state;if("Idle"==c)a.state="Idle";else if("LongOrShortTap"==c){var c=b.x,d=b.y,c=0==f.getSelection().length?!1:f.findVisualItem(c,d)?!1:!0;a.dragger.mouseDown(a.downEvt);a.dragger.mouseUp(b);a.moved>Config.TOUCH_START||b.handled||K(b.x,b.y,b.cx,b.cy,!1,c);a.state="Idle"}else if("Drag"==c)a.dragger.mouseUp(b),a.state="Idle";else return null};a.touchmove=function(b){var c=a.state;if("Idle"==c)a.state="Idle";else if("LongOrShortTap"==
c)a.moved=D(b,a.downEvt),a.moved>Config.TOUCH_START?(a.dragger.mouseDown(a.downEvt),a.dragger.mouseMove(b),a.state="Drag"):a.state="LongOrShortTap";else if("Drag"==c)a.dragger.mouseMove(b),a.state="Drag";else return null};a.touchstart=function(b){var c=a.state;if("Idle"==c)a.downEvt=b,b=f.findDraggable(b.x,b.y),a.moved=0,a.old=b,a.dragger=b?B(b.type,b.id,b.dims,b.data):new w,q(a,600),a.state="LongOrShortTap";else if("LongOrShortTap"==c)a.state="Idle";else if("Drag"==c)a.state="Idle";else return null}}
function ta(){var a=this;a.type_name="FreeScroll";a.state="Idle";a.mouseDown=function(b){var c=a.state;if("Idle"==c)c=0,c=b.button,0===c?a.state="Drag":1===c?a.state="Drag":(2===c&&m.click(),a.state="Idle");else if("Drag"==c)a.state="Drag";else return null};a.mouseMove=function(b){var c=a.state;if("Idle"==c)a.state="Idle";else if("Drag"==c)e.scrollBy(b.dx,b.dy),a.state="Drag";else return null};a.mouseUp=function(b){b=a.state;if("Idle"==b)a.state="Idle";else if("Drag"==b)a.state="Idle";else return null}}
var oa={FR_LU:"nwse-resize",FR_UP:"ns-resize",FR_RU:"nesw-resize",FR_RI:"ew-resize",FR_RD:"nwse-resize",FR_DO:"ns-resize",FR_LD:"nesw-resize",FR_LE:"ew-resize",FR_0:"move",FR_1:"move",H_EW:"ew-resize"};this.draw=function(a){k.draw(a)};this.redrawCache=function(){f.redraw()};this.setZoom=function(a,b){k.zoom=a;k.retina=b};this.mouseDown=H;this.mouseMove=function(a){g.mouseMove(a)};this.mouseUp=I;this.mouseWheel=function(a){J.mouseWheel(a)};this.touchStart=function(a){g==h?h.mouseDown(a):t.touchstart(a)};
this.touchEnd=function(a){g==h?h.mouseUp(a):t.touchend(a)};this.touchMove=function(a){g==h?h.mouseMove(a):t.touchmove(a)};this.setTimeout=q;this.clearTimeout=C;this.startFreeScroll=function(){r();g=h;e.setCursor("move")};this.endFreeScroll=function(){r();e.setCursor("auto")};this.finishZoom=u;this.getBackground=function(){return k.getBackground()};this.externalClick=G;this.resetMachines=r;this.setTransform=function(a,b,c,d){k.setTransform(a,b,c,d)};var pa,g,J,t,h;r()};
