function Canvas(D,Y,O){function Z(a,b,c,d,e){this.font=a;this.italic=b;this.bold=c;this.size=d;this.family=e;this.face=b+"-"+c+"-"+e}function I(a,b,c,d,e){this.ctx=a;this.moveTo=pa;this.lineTo=qa;this.arc=ra;this.transformX=sa;this.transformY=ta;this.ox=b;this.oy=c;this.scaleX=d;this.scaleY=e}function ua(a,b){a.primitives.push({draw:b})}function va(a,b,c,d,e,f){f=b-d+e;b=b+d-e;d=c-e;a.beginPath();a.arc(f,c,e,.5*Math.PI,1.5*Math.PI);a.lineTo(b,d);a.arc(b,c,e,1.5*Math.PI,.5*Math.PI);a.closePath()}function wa(a,
b,c,d,e,f){f=Math.round(2*e/3);var g=c+e,k=Math.round(490*e/260),l=b-k+f,h=b+k-f,n=g-2*f,r=.8*f,p=1.4*f,m=d/e/2;d=b-.34*k;e=n+.16*e;var q=-.9*Math.PI,t=-.25*Math.PI,k=b+.2*k,u=-.9*Math.PI,p=f;a.ellipse?(a.save(),a.translate(b,c),a.scale(m,1),a.translate(-b,-c),a.beginPath(),a.moveTo(l,g),a.arc(l,g-f,f,Math.PI/2,3*Math.PI/2),a.arc(d,e,r,q,t),a.arc(k,n,p,u,0),a.arc(h,g-f,f,-Math.PI/2,Math.PI/2),a.closePath(),a.restore()):(b=new I(a,b,c,m,1),a.beginPath(),b.moveTo(l,g),b.arc(l,g-f,f,Math.PI/2,3*Math.PI/
2),b.arc(d,e,r,q,t),b.arc(k,n,p,u,0),b.arc(h,g-f,f,-Math.PI/2,Math.PI/2),a.closePath())}function xa(a,b,c,d,e){var f=Math.round(10*d),g=e/f;e=c-f+d;f=c+f-d;a.ellipse?(a.save(),a.translate(b,c),a.scale(1,g),a.translate(-b,-c),a.beginPath(),a.arc(b,e,d,-Math.PI,0),a.arc(b,f,d,0,Math.PI),a.closePath(),a.restore()):(c=new I(a,b,c,1,g),a.beginPath(),c.arc(b,e,d,-Math.PI,0),c.arc(b,f,d,0,Math.PI),a.closePath())}function A(a,b,c,d,e){a.beginPath();y(a,b,c,d,e)}function ya(a,b,c,d,e,f){f=f[2];var g=c+e,k=
b-d,l=k+f;b+=d;d=b-f;c-=e;e=g-f;a.beginPath();a.moveTo(k,c);a.lineTo(b,c);a.lineTo(b,e);a.arc(d,e,f,0*Math.PI,.5*Math.PI);a.lineTo(l,g);a.arc(l,e,f,.5*Math.PI,1*Math.PI);a.closePath()}function za(a,b,c,d,e,f){f=f[2];var g=b-d,k=g+f;b+=d;d=b-f;var l=c-e,h=l+f;c+=e;a.beginPath();a.arc(k,h,f,1*Math.PI,1.5*Math.PI);a.lineTo(d,l);a.arc(d,h,f,1.5*Math.PI,0*Math.PI);a.lineTo(b,c);a.lineTo(g,c);a.closePath()}function Aa(a,b,c,d,e,f){var g=e/3;f=b-d;var k=f+g;b+=d;d=b-g;var l=c-e,g=l+g;c+=e;a.beginPath();
a.moveTo(f,c);a.lineTo(f,g);a.lineTo(k,l);a.lineTo(d,l);a.lineTo(b,g);a.lineTo(b,c)}function aa(a,b,c,d,e,f){q(a,f);a.fillStyle=f.fillColor;1==a.lineWidth%2&&(b+=.5,c+=.5);var g=.3*d;f=.3*e;b=b-d+g;c=c-e+f;d=2*d-2*g;e=2*e-2*f;a.fillRect(b,c,d,e);a.strokeRect(b,c,d,e)}function v(a,b){var c=P(b),d;Q++;d=Q;a.id=d;a.layer=b;c.push(a);z[d]=a;return d}function R(a,b,c,d,e,f){b-=d;c-=e;d*=2;e*=2;f.fillColor&&(t.renderToTexture?(ba(a,f.shadow),K(a,f.fillColor,c,c+e),a.fillRect(b,c,d,e),a.shadowColor="rgba(0, 0, 0, 0)"):
(f.shadow&&(a.fillStyle="rgba(0, 0, 0, 0.3)",a.fillRect(b+5,c+7,d,e)),K(a,f.fillColor,c,c+e),a.fillRect(b,c,d,e)));f=E(a,f);0!=f&&(1==f%2&&(b+=.5,c+=.5),a.strokeRect(b,c,d,e))}function Ba(a){var b=a.x+a.cx,c=a.y+a.cy,d=a.w,e=a.h,f=a.cx,g=a.cy,k=a.x-a.w+1.5,l=a.x+a.w-1.5,J=a.y-a.h+1.5,n=a.y+a.h-1.5,r,p;r=f- -d;p=g- -e;r=r>p;var m;p=f- -d;m=g-e;m=-p>m;var q;p=f-d;q=g- -e;p=-p>q;d=f-d;e=g-e;e=d>e;r&&p&&g<-a.h?(e=ca(a,g),f=da(a,f),r={x:f-e,y:J},p={x:f+e,y:J},r.x=Math.max(r.x,k),p.x=Math.min(p.x,l)):!p&&
e&&f>a.w?(e=ea(a,f),f=fa(a,g),r={x:l,y:f-e},p={x:l,y:f+e},r.y=Math.max(r.y,J),p.y=Math.min(p.y,n)):!m&&!e&&g>a.h?(e=ca(a,g),f=da(a,f),r={x:f-e,y:n},p={x:f+e,y:n},r.x=Math.max(r.x,k),p.x=Math.min(p.x,l)):(e=ea(a,f),f=fa(a,g),r={x:k,y:f-e},p={x:k,y:f+e},r.y=Math.max(r.y,J),p.y=Math.min(p.y,n));(k=a.format.fillColor)?7!=k.length&&(k=k.split(" "),k=3==k.length&&"gradient"==k[0]?k[2]:""):k="";k&&(h.fillStyle=k,h.strokeStyle="",h.beginPath(),h.moveTo(r.x,r.y),h.lineTo(b,c),h.lineTo(p.x,p.y),h.closePath(),
h.fill());0!=E(h,a.format)&&(h.beginPath(),h.moveTo(r.x,r.y),h.lineTo(b,c),h.lineTo(p.x,p.y),h.stroke())}function S(a,b,c,d,e,f){a.save();a.translate(d,e);a.rotate(f);"arrow"===b?(a.setLineDash([]),a.strokeStyle=c.lineColor,a.lineWidth=c.lineThickness,a.lineCap="round",a.lineJoin="round",a.fillStyle=c.lineColor,b=c.lineThickness,h.beginPath(),h.moveTo(-20,-5-b),h.lineTo(0,0),h.lineTo(-20,5+b),h.closePath(),h.fill(),h.stroke()):"sarrow"===b?(a.setLineDash([]),a.strokeStyle=c.lineColor,a.lineWidth=
c.lineThickness,a.lineCap="round",a.lineJoin="round",b=c.lineThickness,h.beginPath(),h.moveTo(-20,-5-b),h.lineTo(0,0),h.lineTo(-20,5+b),h.stroke()):"warrow"===b?(a.setLineDash([]),a.strokeStyle=c.lineColor,a.lineWidth=c.lineThickness,a.lineCap="round",a.lineJoin="round",a.fillStyle=c.fillColor,b=c.lineThickness,h.beginPath(),h.moveTo(-20,-5-b),h.lineTo(0,0),h.lineTo(-20,5+b),h.closePath(),h.fill(),h.stroke()):"paw"===b&&(a.setLineDash([]),a.strokeStyle=c.lineColor,a.lineWidth=c.lineThickness,a.lineCap=
"round",a.lineJoin="round",b=c.lineThickness,h.beginPath(),h.moveTo(0,-10-b),h.lineTo(-20,0),h.lineTo(0,10+b),h.stroke());a.restore()}function L(a,b,c,d,e,f,g){h.beginPath();h.arc(b,c,d,0,2*Math.PI,!1);h.fillStyle=f;h.fill();h.lineWidth=e;h.strokeStyle=g;h.stroke()}function Ca(a,b,c,d,e){B(a,b,c,d,e,xa);q(a,e);e=d[0];var f=d[1];d=Math.round(10*e);f/=d;d=c-d+e;a.ellipse?(a.save(),a.translate(b,c),a.scale(1,f),a.translate(-b,-c),a.beginPath(),a.arc(b,d,e,0,Math.PI),a.restore()):(c=new I(a,b,c,1,f),
a.beginPath(),c.moveTo(b+e,d),c.arc(b,d,e,0,Math.PI));a.stroke()}function Da(a){var b=h;b.font=a.font;ga(b,a,a.x+a.left-4,a.y+a.top-4);for(var c=0,d=a.primitives,e=d.length;c<e;)d[c].draw(),c++;a.angle&&b.restore()}function Ea(a){F(h,a.x,a.y,a.x+a.w,a.y+a.h,a.format)}function Fa(a){var b=a.x,c=a.y,d=a.w,e=b+2,f=a.w-4;h.fillStyle="black";h.fillRect(b,c-2,d,6);h.fillStyle="#00ff00";h.fillRect(e,c,f,2);a.valence&&L(h,(a.left+a.right)/2,c+1,Config.SOCKET_RADIUS,2,"#00ff00","black")}function Ga(a){F(h,
a.x,a.y,a.x+a.w,a.y+a.h,a.format);if(a.parallel){var b=a.y+5+a.format.lineThickness;F(h,a.x,b,a.x+a.w,b,a.format)}}function Ha(a){ha(a.x,a.y,10,10,a.color,"black")}function x(a){var b=0;a=P(a);for(var c=a.length;b<c;){var d=a[b];d.draw(d);b++}}function F(a,b,c,d,e,f){var g=E(a,f);0!=g&&(1==g%2&&(b+=.5,c+=.5,d+=.5,e+=.5),a.beginPath(),a.moveTo(b,c),a.lineTo(d,e),a.stroke(),f.arrowStart||f.arrowEnd)&&(g=Utils.findAngle(b,c,d,e),S(a,f.arrowStart,f,b,c,g+Math.PI),S(a,f.arrowEnd,f,d,e,g))}function Ia(a){F(h,
a.x,a.y,a.x+a.w,a.y+a.h,a.format)}function Ja(a,b,c,d){if("link"===b){b=c-12;var e=b+3,f=c+12,g=f-3,k=d-12,l=k+3,h=d+12,n=h-3;a.beginPath();a.moveTo(b,l);a.lineTo(e,k);a.lineTo(g,k);a.lineTo(f,l);a.lineTo(f,n);a.lineTo(g,h);a.lineTo(e,h);a.lineTo(b,n);a.closePath();a.fillStyle="#000090";a.fill();b=c-5;g=c+5;k=d-5;n=d+5;a.strokeStyle="white";a.lineWidth=3;a.setLineDash([]);u(a,b,n,g,k);C(a,c,k,g,k,g,d)}else"video"===b?(a.beginPath(),b=c-6+1.5,e=c+6+1.5,f=d-6,g=d+6,A(a,c,d,12,12),a.fillStyle="#d00000",
a.fill(),a.beginPath(),a.moveTo(b,f),a.lineTo(e,d),a.lineTo(b,g),a.fillStyle="white",a.fill()):"completed"===b&&(a.beginPath(),A(a,c,d,12,12),a.fillStyle="#00a000",a.fill(),a.strokeStyle="#005000",a.lineWidth=1,a.setLineDash([]),a.stroke(),C(a,c-12*.6,d,c-12*.3,d+12*.3,c+6,d-6),a.strokeStyle="white",a.lineWidth=2,a.setLineDash([]),a.stroke())}function Ka(a){var b=Math.floor(a.x);a=Math.floor(a.y);ha(b,a,30,30,"white","black");ia&&h.drawImage(M,b-15+1,a-15+1,28,28)}function La(a){var b=0;E(h,a.format);
var c=a.radius,d=a.x+.5,e=a.y+.5;h.beginPath();b=a.direction;if("left-top"===b)h.arc(d+c,e+c,c,Math.PI,1.5*Math.PI);else if("right-top"===b)h.arc(d-c,e+c,c,.5*-Math.PI,0);else if("right-bottom"===b)h.arc(d-c,e-c,c,0,.5*Math.PI);else{if("left-bottom"!==b)throw"Unexpected switch value: "+b;h.arc(d+c,e-c,c,.5*Math.PI,Math.PI)}h.stroke()}function ha(a,b,c,d,e,f){h.setLineDash([]);a-=Math.floor(c/2);b-=Math.floor(d/2);e&&(h.fillStyle=e,h.fillRect(a,b,c,d));f&&(h.strokeStyle=f,h.lineWidth=2,h.strokeRect(a,
b,c,d))}function B(a,b,c,d,e,f){var g=Math.round(d[0]),k=Math.round(d[1]);T(a,b,c,k,k,e,function(a,b,c){f(a,b,c,g,k,d)})}function Ma(a,b,c,d,e,f){if("rectangle"===b){var g=e[0],k=e[1];R(a,c,d,g,k,f)}else if("db"===b)Ca(a,c,d,e,f);else if("beginend"===b)B(a,c,d,e,f,va);else if("rounded"===b)B(a,c,d,e,f,G);else if("ctrlstart"===b)B(a,c,d,e,f,za);else if("ctrlend"===b)B(a,c,d,e,f,ya);else if("tab"===b)B(a,c,d,e,f,Aa);else if("cloud"===b)B(a,c,d,e,f,wa);else if("line"===b)F(a,c,d,e[0],e[1],f);else if("poly"===
b){b=Na(e);var l=function(a,b,c){a.beginPath();var d=e[0]+b,f=e[1]+c;a.moveTo(d,f);for(var g=2,k=e.length;g<k;)d=e[g]+b,g++,f=e[g]+c,g++,a.lineTo(d,f);a.closePath()};T(a,c,d,-b.top,b.bottom,f,l)}else if("circle"===b)g=e[0],k=e[1],l=function(a,b,c){A(a,b,c,g,k)},T(a,c,d,k,k,f,l);else{if("more"!==b)throw"Unexpected switch value: "+b;g=e[0];k=e[1];(0,m[e[2]])(a,c,d,g,k,f)}}function Oa(a){var b=Config.SOCKET_RADIUS;a.active?L(h,a.x,a.y,b,2,"black","#ffff00"):L(h,a.x,a.y,b,2,"#ffff00","black")}function T(a,
b,c,d,e,f,g){if(f.fillColor)if(t.renderToTexture){ba(a,f.shadow);var k=b,l=c;K(a,f.fillColor,l-d,l+e);g(a,k,l);a.fill();a.shadowColor="rgba(0, 0, 0, 0)"}else f.shadow&&(a.fillStyle="rgba(0, 0, 0, 0.3)",g(a,b+5*t.zoom,c+7*t.zoom),a.fill()),k=b,l=c,K(a,f.fillColor,l-d,l+e),g(a,k,l),a.fill();d=E(a,f);0!=d&&(1==d%2&&(b+=.5,c+=.5),g(a,b,c),a.stroke())}function Pa(a,b,c,d,e){a.fillStyle=e;a.textAlign="left";a.textBaseline="bottom";a.fillText(b,c,d+1)}function Qa(a){var b=a.x+a.left-4,c=a.y+a.top-4;if(a.angle||
t.fast)ga(h,a,b,c),h.drawImage(a.canvas,b,c,a.width,a.height),a.angle&&h.restore();else{h.save();h.setTransform(1,0,0,1,0,0);var d=t.zoom*t.retina,b=Math.round((b+t.dx)*d),c=Math.round((c+t.dy)*d);h.drawImage(a.canvas,b,c);h.restore()}}function Ra(a){var b=a.x,c=a.y,d=a.h,e=c+2,f=a.h-4;h.fillStyle="black";h.fillRect(b-2,c,6,d);h.fillStyle="#00ff00";h.fillRect(b,e,2,f);a.valence&&L(h,b+1,(a.top+a.bottom)/2,Config.SOCKET_RADIUS,2,"#00ff00","black")}function Sa(a){var b=a.format.lineThickness,c=Math.floor(b/
2);h.fillStyle=a.format.lineColor;h.fillRect(a.x-c,a.y,b,a.h);"par-down-off"===a.role&&S(h,"arrow",a.format,a.x,a.y+a.h-b,Math.PI/2)}function Na(a){var b=0,c=0,d,e=a.length;for(d=1;d<e;){var f=a[d],b=Math.min(b,f),c=Math.max(c,f);d+=2}return{top:b,bottom:c}}function U(a,b){var c=z[b[0]];t.renderToTexture?(b[0]=c.context,a.apply(null,b)):ua(c,function(){b[0]=h;a.apply(null,b)})}function da(a,b){return Math.abs(b)<a.w/2?a.x:0>b?a.x-2*a.w/3:a.x+2*a.w/3}function fa(a,b){return Math.abs(b)<a.h/2?a.y:0>
b?a.y-2*a.h/3:a.y+2*a.h/3}function P(a){if(a in H)return H[a];throw"Unknown plane: "+a;}function ca(a,b){var c=a.w/8,d=Math.abs(a.h-Math.abs(b)),c=Math.min(c,d/4);return c=Math.max(c,15)}function ea(a,b){var c=a.h/8,d=Math.abs(a.w-Math.abs(b)),c=Math.min(c,d/4);return c=Math.max(c,8)}function N(a){return"number"==typeof a?a:1}function V(a,b,c,d,e){var f=.3*e,g=b+d/3;C(a,g,c-e+f,b-d/3,c,g,c+e-f)}function u(a,b,c,d,e){a.beginPath();a.moveTo(b,c);a.lineTo(d,e);a.stroke()}function C(a,b,c,d,e,f,g){a.beginPath();
a.moveTo(b,c);a.lineTo(d,e);a.lineTo(f,g);a.stroke()}function ja(){return{lines:[],line_candies:[],icons:[],icon_candies:[],sockets:[],free:[],free_candies:[],guides:[]}}function ka(a,b,c,d,e,f){q(a,f);a.fillStyle=f.fillColor;d*=.8;A(a,b,c,d,d);a.fill();a.stroke()}function W(a,b,c,d,e){var f=.3*e,g=b-d/3;C(a,g,c-e+f,b+d/3,c,g,c+e-f)}function ga(a,b,c,d){b.angle&&(c=c+b.width/2-5,d=d+b.height/2-5,a.save(),a.translate(c,d),a.rotate(b.angle),a.translate(-c,-d))}function G(a,b,c,d,e,f){var g=f[2],k=f[3];
f=b-d+k+g;b=b+d-k;d=b-g;var l=c-e+k,h=l+g;c=c+e-k;e=c-g;a.beginPath();a.arc(f,h,g,1*Math.PI,1.5*Math.PI);a.lineTo(d,l);a.arc(d,h,g,1.5*Math.PI,0*Math.PI);a.lineTo(b,e);a.arc(d,e,g,0*Math.PI,.5*Math.PI);a.lineTo(f,c);a.arc(f,e,g,.5*Math.PI,1*Math.PI);a.closePath()}function y(a,b,c,d,e){if(a.ellipse)a.ellipse(b,c,d,e,0,0,2*Math.PI);else{var f,g,k;e>d?(f=d,g=1,k=e/d):(f=e,k=1,g=d/e);(new I(a,b,c,g,k)).arc(b,c,f,0,2*Math.PI)}}function K(a,b,c,d){if(b)if(7==b.length)c=b;else{var e=b.split(" ");3==e.length&&
"gradient"==e[0]?(b=e[1],e=e[2],c=a.createLinearGradient(0,c,0,d),c.addColorStop(0,b),c.addColorStop(1,e)):c=""}else c="";a.fillStyle=c}function la(a){if(a){var b=Utils.parseFontString(a);w=new Z(a,b.italic,b.bold,b.size,b.family)}else w=ma;X.font=w.font}function E(a,b){var c=b.lineColor,d=b.lineThickness,e=b.lineStyle;if(0!=d&&c){var f=N(d);a.strokeStyle=c;a.lineWidth=f;a.lineCap="round";if("solid"===e)c=[];else if("s-1"===e)for(c=[1,2],e=0;e<c.length;)c[e]*=d,e++;else if("s-2"===e)for(c=[3,4],e=
0;e<c.length;)c[e]*=d,e++;else if("s-3"===e)for(c=[7,8],e=0;e<c.length;)c[e]*=d,e++;else if("s-4"===e)for(c=[16,16],e=0;e<c.length;)c[e]*=d,e++;else c=[];a.setLineDash(c);return f}return 0}function ba(a,b){if(b){var c=4*t.zoom*t.retina;a.shadowColor="rgba(0, 0, 0, 0.6)";a.shadowBlur=10*t.zoom;a.shadowOffsetX=c;a.shadowOffsetY=c}}function q(a,b){var c=b.lineThickness;a.fillStyle=b.lineColor;a.strokeStyle=b.lineColor;a.lineWidth=N(c)||1}function ra(a,b,c,d,e){var f=Math.cos,g=Math.sin,k;k=Math.max(6,
Math.floor(40<c?c/3:c));var l=e-d,h;for(h=0;h<=k;){var n;n=h==k?e:d+l*h/k;var m=f(n)*c+a;n=g(n)*c+b;m=this.transformX(m);n=this.transformY(n);this.ctx.lineTo(m,n);h++}}function qa(a,b){var c=this.transformX(a),d=this.transformY(b);this.ctx.lineTo(c,d)}function pa(a,b){var c=this.transformX(a),d=this.transformY(b);this.ctx.moveTo(c,d)}function sa(a){var b=this.ox;return(a-b)*this.scaleX+b}function ta(a){var b=this.oy;return(a-b)*this.scaleY+b}var t=this;this.retina=this.zoom=1;var h=null,na="",w=null,
ma=null;this.renderToTexture=!0;var Q=0,z={},H=ja(),X=Y.createElement("canvas").getContext("2d"),M=null,ia=!1,oa=O=D=null,m={};D=Utils.buildFontString(!1,!1,Config.FONT_SIZE,Config.FONT_FAMILY);la(D);M=new Image;M.onload=function(){ia=!0};M.src="/static/images/4-way-pan.png";D=new Image;O=new Image;oa=new Image;D.src="/static/images/video-s.png";O.src="/static/images/link-s.png";oa.src="/static/images/picture-s.png";m.f_ui_vscroll=function(a,b,c,d,e,f){R(a,b,c,d,e,f);a.fillStyle=f.lineColor;var g=
d/4;f=b-d+g;var k=b+d-g,l=c-e+g,h=c-e+1.5*d;d=c+e-1.5*d;c=c+e-g;a.beginPath();a.moveTo(f,h);a.lineTo(b,l);a.lineTo(k,h);a.closePath();a.fill();a.beginPath();a.moveTo(b,c);a.lineTo(f,d);a.lineTo(k,d);a.closePath();a.fill()};m.f_ui_hscroll=function(a,b,c,d,e,f){R(a,b,c,d,e,f);a.fillStyle=f.lineColor;var g=e/4;f=c-e+g;var k=c+e-g,l=b-d+g,h=b-d+1.5*e;e=b+d-1.5*e;b=b+d-g;a.beginPath();a.moveTo(l,c);a.lineTo(h,f);a.lineTo(h,k);a.closePath();a.fill();a.beginPath();a.moveTo(e,f);a.lineTo(b,c);a.lineTo(e,
k);a.closePath();a.fill()};m.f_ui_cross=function(a,b,c,d,e,f){var g=.3*d,k=.3*e,l=b-d+g;b=b+d-g;d=c-e+k;c=c+e-k;q(a,f);a.beginPath();a.moveTo(l,d);a.lineTo(b,c);a.closePath();a.stroke();a.beginPath();a.moveTo(b,d);a.lineTo(l,c);a.closePath();a.stroke()};m.f_ui_check=function(a,b,c,d,e,f){var g=.3*d,k=.3*e,l=b-d+g,h=l+g;b=b+d-g;d=c-e+k;e=c+e-k;q(a,f);a.beginPath();a.moveTo(l,c);a.lineTo(h,e);a.lineTo(b,d);a.stroke()};m.f_ui_menu=function(a,b,c,d,e,f){q(a,f);1==a.lineWidth%2&&(b+=.5,c+=.5);var g=Math.round(.5*
d),k=Math.round(.5*e);f=b-d+g;b=b+d-g;d=c-e+k;e=c+e-k;u(a,f,d,b,d);u(a,f,c,b,c);u(a,f,e,b,e)};m.f_ui_combo=function(a,b,c,d,e,f){var g=.5*d,k=.6*e,l=b-d+g;d=b+d-g;g=c-e+k;c=c+e-k;q(a,f);a.beginPath();a.moveTo(l,g);a.lineTo(d,g);a.lineTo(b,c);a.closePath();a.fill();a.stroke()};m.f_ui_left=function(a,b,c,d,e,f){q(a,f);V(a,b,c,d,e)};m.f_ui_left2=function(a,b,c,d,e,f){q(a,f);f=d/3;V(a,b-f,c,d,e);V(a,b+f,c,d,e)};m.f_ui_right=function(a,b,c,d,e,f){q(a,f);W(a,b,c,d,e)};m.f_ui_right2=function(a,b,c,d,e,f){q(a,
f);f=d/3;W(a,b-f,c,d,e);W(a,b+f,c,d,e)};m.f_ui_radio_false=ka;m.f_ui_radio_true=function(a,b,c,d,e,f){ka(a,b,c,d,e,f);q(a,f);d*=.3;e*=.3;a.beginPath();y(a,b,c,d,e,0,0,2*Math.PI);a.fill()};m.f_ui_check_false=aa;m.f_ui_check_true=function(a,b,c,d,e,f){aa(a,b,c,d,e,f);f=.6*d;var g=.6*e,k=c-e+g;C(a,b-d+f,k,b,c+e-g,b+d-f,k)};m.f_ui_search=function(a,b,c,d,e,f){var g=.6*e;d=.8*g;e=b-g+d;var k=c-g+d;b+=g;c+=g;var l=Math.cos(Math.PI/4)*d,g=e+l,l=k+l;q(a,f);a.beginPath();y(a,e,k,d,d);a.stroke();u(a,g,l,b,
c)};m.f_ui_dots3h=function(a,b,c,d,e,f){e*=.6;d=b-e;e=b+e;var g=N(f.lineThickness)||1;q(a,f);a.beginPath();y(a,d,c,g,g);a.fill();a.beginPath();y(a,b,c,g,g);a.fill();a.beginPath();y(a,e,c,g,g);a.fill()};m.f_ui_dots3v=function(a,b,c,d,e,f){e*=.6;d=c-e;e=c+e;var g=N(f.lineThickness)||1;q(a,f);a.beginPath();y(a,b,d,g,g,0,0,2*Math.PI);a.fill();a.beginPath();y(a,b,c,g,g,0,0,2*Math.PI);a.fill();a.beginPath();y(a,b,e,g,g,0,0,2*Math.PI);a.fill()};m.f_ui_close=function(a,b,c,d,e,f){q(a,f);1==a.lineWidth%2&&
(b+=.5,c+=.5);d=Math.round(.5*e);f=b-3*d;var g=b+3*d;e=f-d;f+=d;var k=g-d,g=g+d,l=c-d,h=c+d,n=2*d;a.strokeRect(b-d,l,n,n);u(a,e,c,f,c);u(a,k,l,g,h);u(a,k,h,g,l)};m.f_ui_close_mac=function(a,b,c,d,e,f){q(a,f);d=.5*e;e=b-3*d;f=b+3*d;var g=d*Math.cos(Math.PI/4),k=e-g,l=e+g,h=c-g,g=c+g;A(a,e,c,d,d);a.stroke();A(a,b,c,d,d);a.stroke();A(a,f,c,d,d);a.stroke();u(a,k,h,l,g);u(a,k,g,l,h)};m.f_ui_up=function(a,b,c,d,e,f){q(a,f);f=.3*d;var g=c+e/3;C(a,b-d+f,g,b,c-e/3,b+d-f,g)};m.f_ui_down=function(a,b,c,d,e,
f){q(a,f);f=.3*d;var g=c-e/3;C(a,b-d+f,g,b,c+e/3,b+d-f,g)};m.f_ar_pc=function(a,b,c,d,e,f){q(a,f);var g=b-d,k=c-e;d*=2;var h=2*e,m=Math.ceil(e/10),n=Math.round(.8*h),r=Math.round(.2*d);a.fillStyle=f.lineColor;a.fillRect(g,k,d,n);a.fillStyle=f.fillColor;a.fillRect(g+m,k+m,d-2*m,n-2*m);a.fillStyle=f.lineColor;a.fillRect(b-r/2,k+n,r,h-n-m);a.fillStyle=f.lineColor;a.fillRect(b-r,c+e-m,2*r,m)};m.f_ar_human=function(a,b,c,d,e,f){q(a,f);a.fillStyle=f.fillColor;1==a.lineWidth%2&&(b+=.5,c+=.5);f=c-e;c+=e;
d*=2;var g=Math.round(.8*e);e=Math.floor((d-0)/8);d=Math.round(1.5*e);var k=Math.round(2.3*d),h=Math.round(.8*e);b=b+2*e+2*h;var m=b-2*h,n=m-0,r=n-e,p=n-2*e,t=p-0,u=t-e,v=t-2*e,w=v-0,y=w-2*h,z=Math.round((t+p)/2),k=f+k,x=k+2*h,g=c-g;c-=e;A(a,z,f+d,d,d);a.fill();a.stroke();a.beginPath();a.moveTo(m,k);a.arc(m,x,2*h,-Math.PI/2,0);a.lineTo(b,g);a.arc(b-h,g,h,0,Math.PI);a.lineTo(m,x);a.lineTo(n,x);a.lineTo(n,c);a.arc(r,c,e,0,Math.PI);a.lineTo(p,g);a.lineTo(t,g);a.lineTo(t,c);a.arc(u,c,e,0,Math.PI);a.lineTo(v,
x);a.lineTo(w,x);a.lineTo(w,g);a.arc(w-h,g,h,0,Math.PI);a.lineTo(y,k+2*h);a.arc(y+2*h,k+2*h,2*h,-Math.PI,-Math.PI/2);a.closePath();a.fill();a.stroke()};m.f_ar_server1=function(a,b,c,d,e,f){q(a,f);a.fillStyle=f.fillColor;1==a.lineWidth%2&&(b+=.5,c+=.5);G(a,b,c,d,e,[0,0,d/5,0]);a.fill();a.stroke();f=Math.round(e/6);var g=b-d+f,k=b+d-f,h=c-e+f;a.strokeRect(g,h,2*d-2*f,f);h+=2*f;u(a,g,h,k,h);h+=f;u(a,g,h,k,h);h+=f;u(a,g,h,k,h);h=c+e-3*f;u(a,g,h,k,h);A(a,b,h,f,f);a.fill();a.stroke()};m.f_ar_server2=function(a,
b,c,d,e,f){q(a,f);a.fillStyle=f.fillColor;1==a.lineWidth%2&&(b+=.5,c+=.5);f=b-d;var g=c-e,h=2*d,l=2*e;a.fillRect(f,g,h,l);a.strokeRect(f,g,h,l);f=Math.round(d/8);g=b-d+2*f;for(h=0;4>h;)u(a,g,c-e,g,c+e),g+=f,h++;e=c-f;a.strokeRect(b+d-4*f,e,f,f);a.strokeRect(b+d-2*f,e,f,f);u(a,b-d,c+f,b+d,c+f)};m.f_ar_phone=function(a,b,c,d,e,f){q(a,f);var g=d/5,h=e/4,l=d/4,m=Math.round(c+e-h/2);1==a.lineWidth%2&&(m+=.5);G(a,b,c,d,e,[0,0,g,0]);a.fill();a.fillStyle=f.fillColor;a.fillRect(b-d+a.lineWidth,c-e+h,2*d-2*
a.lineWidth,2*e-2*h);a.strokeStyle=f.fillColor;u(a,b-l,m,b+l,m)};m.f_ar_tablet=function(a,b,c,d,e,f){q(a,f);var g=e/4;G(a,b,c,d,e,[0,0,d/5,0]);a.fill();a.fillStyle=f.fillColor;a.fillRect(b-d+a.lineWidth,c-e+g,2*d-2*a.lineWidth,2*e-2*g);d=g/4;A(a,b,c-e+g/2,d,d);a.fill()};m.f_ar_notebook=function(a,b,c,d,e,f){q(a,f);var g=Math.round(e/5),h=Math.round(d/5);G(a,b,c,d-2*g,e,[0,0,g,0]);a.fill();a.fillRect(b-d,c+e-g,2*d,g);a.fillStyle=f.fillColor;a.fillRect(b-d+3*g,c-e+g,2*d-6*g,2*e-2*g);a.fillRect(b-h,
c+e-g,2*h,g/2)};m.f_ar_portrait=function(a,b,c,d,e,f){q(a,f);a.fillStyle=f.fillColor;1==a.lineWidth%2&&(b+=.5,c+=.5);f=b-d;d=b+d;var g=c-e,h=c+e,l=e/2.3,m=.4*l,n=.8*l,r=b+n,p=c+.2*e,n=b-n;c+=.6*e;e=(p+c)/2;a.beginPath();a.moveTo(b-l,g+l);a.arc(b,g+l,l,-Math.PI,0);a.lineTo(b+l,g+l+m);a.arc(b,g+l+m,l,0,Math.PI);a.closePath();a.fill();a.stroke();a.beginPath();a.moveTo(b,c);a.lineTo(r,p);a.lineTo(d,e);a.lineTo(d,h);a.lineTo(f,h);a.lineTo(f,e);a.lineTo(n,p);a.closePath();a.fill();a.stroke()};this.getFontHeight=
function(){var a=HtmlUtils.getFontHeight(w.face,w.size,w.font),a=null;a||(a=w.size);return Math.floor(a)};this.measureTextWidth=function(a){a=X.measureText(a).width;return Math.round(a)};this.setFont=la;this.createVertical=function(a,b,c,d,e,f){return v({x:a,y:b,h:c,w:0,role:d,format:e,draw:Sa},f)};this.createHorizontal=function(a,b,c,d,e,f){var g=!1,h=e.lineThickness;"arrow"===d?(e.arrowStart="arrow",a+=h,c-=h):"rarrow"===d?(e.arrowEnd="arrow",c-=h):"parallel"===d&&(g=!0);return v({x:a,y:b,w:c,h:0,
format:e,parallel:g,draw:Ga},f)};this.createVCandy=function(a,b,c,d,e,f,g){return v({x:a,y:b,h:c,valence:d,top:e,bottom:f,draw:Ra},g)};this.createHCandy=function(a,b,c,d,e,f,g){return v({x:a,y:b,w:c,h:10,valence:d,left:e,right:f,draw:Fa},g)};this.createJCandy=function(a,b,c,d){return v({x:a,y:b,color:c,draw:Ha},d)};this.addSocket=function(a,b){return v({x:a,y:b,active:!1,draw:Oa},"sockets")};this.createRCorner=function(a,b,c,d,e,f){return v({x:a,y:b,format:c,direction:d,radius:e,draw:La},f)};this.createFreeHorizontal=
function(a,b,c,d,e,f){"dashed"==d&&(e.lineStyle="s-2");return v({x:a,y:b,w:c,h:0,style:d,format:e,draw:Ea},f)};this.createCalloutArrow=function(a,b,c,d,e,f,g,h){return v({x:a,y:b,w:c,h:d,cx:e,cy:f,format:g,draw:Ba},h)};this.deleteItem=function(a){if(a in z){var b=P(z[a].layer),c=b.length;delete z[a];for(var d=0;d<c;){if(b[d].id==a){b.splice(d,1);break}d++}}};this.setItemProperty=function(a,b,c){z[a][b]=c};this.moveItem=function(a,b,c){a=z[a];a.x=b;a.y=c};this.draw=function(a){try{h=a,x("lines"),x("line_candies"),
x("icons"),x("icon_candies"),x("sockets"),x("free"),x("free_candies"),x("guides"),h=null}catch(b){throw CallTrace.error(b),b;}};this.clear=function(){Q=0;H=ja();z={}};this.makeDirty=function(){this.dirty=!0};this.cleanDirty=function(){this.dirty=!1};this.setTitle=function(a){};this.createTexture=function(a,b,c,d,e,f,g,h){if(this.renderToTexture){var l=t.retina;e=e+8+10;f=f+8+10;var m=Y.createElement("canvas");m.width=e*t.zoom*l;m.height=f*t.zoom*l;var n=m.getContext("2d");n.font=w.font;l*=t.zoom;
n.scale(l,l);n.translate(-a-c+4,-b-d+4);return v({x:a,y:b,left:c,top:d,width:e,height:f,canvas:m,context:n,draw:Qa,angle:h},g)}return v({x:a,y:b,left:c,top:d,width:e,height:f,primitives:[],draw:Da,font:w.font,angle:h},g)};this.drawText=function(a,b,c,d,e){U(Pa,arguments)};this.setBackground=function(a){na=a};this.getBackground=function(){return na};this.setDefaultFont=function(a){var b,c,d,e;a?(e=Utils.parseFontString(a),b=e.italic,c=e.bold,d=e.size,e=e.family):(c=b=!1,d=Config.FONT_SIZE_1,e=Config.FONT_FAMILY_1,
a=Utils.buildFontString(b,c,d,e));w=ma=new Z(a,b,c,d,e);X.font=a};this.drawShape=function(a,b,c,d,e){U(Ma,arguments)};this.createLine=function(a,b,c,d,e,f){return v({x:a,y:b,w:c,h:d,format:e,draw:Ia},f)};this.createMoveAll=function(a,b,c){return v({x:a,y:b,draw:Ka},c)};this.clearGuides=function(){for(var a=0,b=H.guides,c=b.length;a<c;)delete z[b[a].id],a++;H.guides=[]};this.drawLinkIcon=function(a,b,c,d){U(Ja,arguments)};this.setTransform=function(a,b,c,d){t.dx=a;t.dy=b;t.zoom=c;t.retina=d}};
