function DrakonModule(){function W(){this.starts=[];this.tsUp=[];this.tsDown=[];this.visited={};this.bottom=this.top=null;this.addressEnd=!1}function A(){this.addressEnd=!1;this.nodes={};this.bottom=this.top=null;this.oldIds={}}function B(a,b,c){(a=I(a,b))&&(c[a.id]=!0)}function u(a,b,c,g,d){var k;c.left&&(k=a.getNodeLeft(c),b.push(k));c.up&&g&&(k=a.getNodeUp(c),b.push(k));c.right&&(k=a.getNodeRight(c),b.push(k));c.down&&d&&(k=a.getNodeDown(c),b.push(k))}function J(a,b,c,g,d){var k=0;b=Object.keys(b);
for(var f=b.length;k<f;){var e=b[k],h=a.graph.getItem(e),e=v(d,e).fields;e.x=h.x;e.y=h.y;k++}a=Object.keys(g);if(0!=a.length)for(c=v(d,c),d=0,k=a.length;d<k;)b=a[d],c.fields[b]=g[b],d++}function K(a,b,c){var g=0;b=Object.keys(b);for(var d=b.length;g<d;)a.add(b[g],c),g++}function L(a,b){return M(b)?a.getNodeRight(b):b.id}function X(a,b,c){if(this.simplified){for(var g=[],d=0,k=a.nodes,f=Object.keys(k),e=f.length;d<e;){a=f[d];var h=k[a];"junction"!=h.type&&w(c,h)&&g.push(a);d++}d=0;b=b.set;k=Object.keys(b);
for(f=k.length;d<f;)a=k[d],w(c,b[a])&&g.push(a),d++;a=N(this.ids,g);if(0<a.length){g=0;for(b=a.length;g<b;)this.add(a[g],!0),g++;a=!0}else a=!1;return a}g=[];k=0;f=a.nodes;e=Object.keys(f);for(h=e.length;k<h;)d=e[k],w(c,f[d])&&g.push(d),k++;k=0;f=b.set;e=Object.keys(f);for(h=e.length;k<h;)d=e[k],w(c,f[d])&&g.push(d),k++;f=N(this.block.oldIds,g);if(0<f.length){e=this.block;d=[];c={};for(var k=e,h=0,l=f.length;h<l;){var m=f[h],p=b.get(m);if(p)c[m]=!0;else{var p=a.getNode(m),n=0,n=p.type;("beginend"===
n||"end"===n||"duration"===n||"address"===n||"branch"===n?0:"action"===n?"params"!=p.role:"junction"===n?Y(a,p):1)?m in e.nodes||d.push(m):"junction"!=p.type&&(c[m]=!0)}h++}b=0;for(f=d.length;b<f;)e=a,m=d[b],n=0,h=new A,p=e.getNode(m),l=new W,n=void 0,n=p.type,"question"===n?(n=e.getNodeRight(p),l.starts.push(n),m=l.starts[0],m=e.getNode(m),q(l,m),r(l,m),t(e,l),h.nodes=l.visited,h.top=l.top.id,h.bottom=l.bottom.id,h.addressEnd=l.addressEnd):"case"===n?(m=e.getNodeUpEx(p),n=L(e,m),l.starts.push(n),
m=l.starts[0],m=e.getNode(m),q(l,m),r(l,m),t(e,l),h.nodes=l.visited,h.top=l.top.id,h.bottom=l.bottom.id,h.addressEnd=l.addressEnd):"select"===n?(m=e.getNodeDownEx(p),n=e.getNodeRight(m),l.starts.push(n),m=l.starts[0],m=e.getNode(m),q(l,m),r(l,m),t(e,l),h.nodes=l.visited,h.top=l.top.id,h.bottom=l.bottom.id,h.addressEnd=l.addressEnd):"loopbegin"===n?(p=C(e,p),l.starts.push(m),l.starts.push(p),m=l.starts[0],m=e.getNode(m),q(l,m),r(l,m),t(e,l),h.nodes=l.visited,h.top=l.top.id,h.bottom=l.bottom.id,h.addressEnd=
l.addressEnd):"loopend"===n?(p=D(e,p),l.starts.push(m),l.starts.push(p),m=l.starts[0],m=e.getNode(m),q(l,m),r(l,m),t(e,l),h.nodes=l.visited,h.top=l.top.id,h.bottom=l.bottom.id,h.addressEnd=l.addressEnd):"junction"===n?(n=L(e,p),l.starts.push(n),m=l.starts[0],m=e.getNode(m),q(l,m),r(l,m),t(e,l),h.nodes=l.visited,h.top=l.top.id,h.bottom=l.bottom.id,h.addressEnd=l.addressEnd):(h.nodes[m]=!0,h.top=m,h.bottom=m,B(e,p,h.nodes)),e=h,!k.top||k.top in e.nodes&&k.bottom in e.nodes?k=e:O(a,k.bottom,e.top)?k=
P(k,e):O(a,e.bottom,k.top)?k=P(e,k):Utils.mergeSets(c,e.nodes),b++;a=k;K(this,c,!1);K(this,a.nodes,!0);this.block=a;this.block.oldIds=Utils.listToSet(g);a=!0}else a=!1;return a}function w(a,b){var c=x.getItemCallback(b.type);if(c.boxIntersect)return c.boxIntersect(b,a);var c=b.x-b.w,g=b.y-b.h,d=b.y+b.h;return b.x+b.w<a.left||c>a.right||d<a.top||g>a.bottom?!1:!0}function Q(a,b,c,g,d,k){var f=b.graph.getItem(c);d=R(a,f,g,d);a={};g=d.fields;k.tb=d.tb;k.tb2=d.tb2;if("h"in g){d=g.h;var e=0,h=0,f=b.graph.getNode(c),
e={};e[c]=!0;d<f.h?(e=f.type,"address"===e||"select"===e?(delta=f.h-d,b.changeSize(c,f.w,d),b.moveDownNoTeam(c,delta,a)):"case"===e||"branch"===e?(delta=d-f.h,b.changeSize(c,f.w,d),b.moveDownNoTeam(c,delta,a)):(delta=0,b.changeSize(c,f.w,d))):d>f.h?(h=f.type,"address"===h||"select"===h?(delta=f.h-d,h=E(f),b.pushObjects(h,e,2*delta,"vertical",a),b.moveDownNoTeam(c,delta,a),b.changeSize(c,f.w,d)):"duration"===h?(delta=d-f.h,h=E(f),d=F(f),b.pushObjects(h,e,-delta,"vertical",a),b.pushObjects(d,e,delta,
"vertical",a)):(delta=d-f.h,h=F(f),b.pushObjects(h,e,2*delta,"vertical",a),b.moveDownNoTeam(c,delta,a),b.changeSize(c,f.w,d))):delta=0}if("w"in g)if(d=g.w,f=0,e=b.graph,h=e.getNode(c),Utils.copyBox(h.box),"duration"==h.type)e.getNodeRight(h),f=h.w-d,d>h.w?(b.moveAlone(c,2*f,!0,a),b.moveAlone(c,-f,!1,a),b.changeSize(c,d,h.h)):(y(b,c,null,d,a),b.moveAlone(c,f,!1,a));else if("params"==h.role)f=h.w-d,d>h.w?(b.moveRight(c,-f,a),b.changeSize(c,d,h.h)):(y(b,c,null,d,a),b.moveAlone(c,-f,!1,a));else{var l=
null;h.left&&(l=e.getNodeLeft(h),f=h.w-d);d>h.w?(l&&b.moveAlone(l,f,!0,a),y(b,c,l,d,a)):(y(b,c,null,d,a),l&&b.moveAlone(l,f,!1,a))}J(b,a,c,g,k.commands)}function R(a,b,c,g){a=G({isLine:!1,type:b.type,content:g,x:0,y:0,w:c},a);c={fields:{},tb:a.tb,tb2:a.tb2};var d=c.fields;Utils.shallowEquivalent(g,b.content)||(d.content=g);null!=a.a&&b.a!==a.a&&(d.a=a.a);b.h!==a.h&&(d.h=a.h);b.w!==a.w&&(d.w=a.w);0!=Object.keys(d).length&&(d.tb=a.tb,d.tb2=a.tb2);return c}function y(a,b,c,g,d){var k={};k[b]=!0;c&&(k[c]=
!0);c=a.graph.getNode(b);var f=g-c.w;if(0<f){var e=S(c),h=T(c);a.pushObjects(e,k,-f,"horizontal",d);a.pushObjects(h,k,f,"horizontal",d)}a.changeSize(b,g,c.h)}function N(a,b){return b.filter(function(b){return!(b in a)})}function D(a,b){for(var c=1;;){var g=a.getNodeUp(b);b=a.getNode(g);if("loopbegin"===b.type){if(c--,0===c)return g}else"loopend"===b.type&&c++;if(!b.up)return null}}function C(a,b){for(var c=1;;){var g=a.getNodeDown(b);b=a.getNode(g);if("loopend"===b.type){if(c--,0===c)return g}else"loopbegin"===
b.type&&c++;if(!b.down)return null}}function G(a,b){var c=x.getItemCallback(a.type).fit(a,b);c.w=Math.floor(c.w);c.h=Math.floor(c.h);null!=c.a&&(c.a=Math.floor(c.a));return c}function I(a,b){if(b.left){var c=a.getNodeLeftEx(b);return"duration"==c.type?c:null}return null}function v(a,b){if(b in a)return a[b];var c=new Utils.Command("update","nodes",b,{});return a[b]=c}function z(a,b){return b.up?"address"==a.getNodeUpEx(b).type?!0:!1:!1}function Y(a,b){if(b.down){if("branch"==a.getNodeDownEx(b).type||
z(a,b))return!1;if(b.right){var c=a.getEdge(b.right);if("rarrow"==c.role)return!1;c=a.getNodeRightEx(b);return z(a,c)?!1:!0}return!0}if(z(a,b))return!1;if(b.right){c=a.getEdge(b.right);if("rarrow"==c.role)return!1;c=a.getNodeRightEx(b);return z(a,c)?!1:!0}return!0}function H(a,b){var c=a.bottom;return b.x<c.x||b.x==c.x&&b.y>=c.y?!0:!1}function U(a,b){var c=a.top;return b.x<c.x||b.x==c.x&&b.y<=c.y?!0:!1}function O(a,b,c){b=a.getNode(b);a=a.getNode(c);return b.down&&b.down==a.up?!0:!1}function M(a){return"question"==
a.type||"junction"==a.type&&!a.left&&a.up&&a.right&&a.down?!0:!1}function V(a){return a.isLine||"junction"==a.type||a.type in Z?!1:!0}function t(a,b){for(;0!=b.starts.length;){var c=a,g=b,d=0,k=g.starts,f=k.pop();if(!(f in g.visited))if(g.visited[f]=!0,f=c.getNode(f),B(c,f,g.visited),M(f)){var e=d=void 0,d=c.getNodeUpEx(f);"select"==d.type?(e=c.getNodeRight(f),k.push(e),B(c,d,g.visited),e=c.getNodeDownEx(f),g.visited[d.id]=!0,g.visited[e.id]=!0):e=d=f;U(g,d)?(r(g,d),g.tsUp.push(d)):u(c,k,d,!0,!1);
H(g,e)?(q(g,e),g.tsDown.push(e)):u(c,k,e,!1,!0)}else if(d=c,e=f,"junction"==e.type&&(e.right?"sil_floor"==d.getEdge(e.right).role:e.left&&"sil_floor"==d.getEdge(e.left).role))d=c.getNodeUp(f),k.push(d),H(g,f)?(q(g,f),g.tsDown.push(f)):(f=c.getNodeLeft(f),k.push(f)),g.addressEnd=!0;else if(U(g,f)&&r(g,f),H(g,f)&&q(g,f),d=f.type,"loopbegin"===d)e=C(c,f),d=c.getNodeUp(f),c=c.getNodeDown(f),k.push(e),k.push(c),g.top!==f&&k.push(d);else if("loopend"===d)e=D(c,f),d=c.getNodeUp(f),c=c.getNodeDown(f),k.push(e),
k.push(d),g.bottom!==f&&k.push(c);else if("junction"===d){if(g=c,d=k,c=f,u(g,d,c,!0,!0),c.up&&c.down?0:c.left||c.right)for(k=g,g=d,f=0,c=k.getVertical(c.id),d=c.length;f<d;)e=c[f],k.getItem(e).isLine||g.push(e),f++}else u(c,k,f,!0,!0);for(var k=a,g=b,c=[],f=[],d=0,e=g.tsUp,h=e.length;d<h;){var l=e[d];l==g.top?c.push(l):(l=k.getNodeUp(l),g.starts.push(l));d++}g.tsUp=c;c=0;d=g.tsDown;for(e=d.length;c<e;)h=d[c],h==g.bottom?f.push(h):(h=h.down?k.getNodeDown(h):k.getNodeLeft(h),g.starts.push(h)),c++;g.tsDown=
f}}function F(a){var b=Utils.copyBox(a.box);b.top=a.y+1;return b}function S(a){var b=Utils.copyBox(a.box);b.right=a.x-1;return b}function T(a){var b=Utils.copyBox(a.box);b.left=a.x+1;return b}function E(a){var b=Utils.copyBox(a.box);b.bottom=a.y-1;return b}function P(a,b){var c=new A,g=Utils.copyObject(a.nodes);Utils.mergeSets(g,b.nodes);c.addressEnd=b.addressEnd;c.nodes=g;c.top=a.top;c.bottom=b.bottom;return c}function q(a,b){a.bottom=b;a.x=b.x}function r(a,b){a.top=b;a.x=b.x}var Z={beginend:!0,
pause:!0,ctrlStart:!0,ctrlEnd:!0,timer:!0,end:!0},x=null;this.setSkewerWidth=function(a,b,c,g,d){var k=b.graph;d={commands:d};var f=0;c=k.getVertical(c);for(var e=c.length;f<e;){var h=c[f],l=k.getItem(h);V(l)&&Q(a,b,h,g,l.content,d);f++}};this.setItems=function(a){x=a};this.changeItem=Q;this.fitItem=G;this.isWideIcon=V;this.Selection=function(a){this.simplified=a;this.ids={};this.block=new A;this.blockSelect=X;this.add=function(a,c){this.ids[a]=c?"green":"blue"}};this.findEndLoop=C;this.findBeginLoop=
D;this.getDuration=I;this.getOrCreateUpdate=v;this.changeFreeItem=function(a,b,c,g,d,k,f){var e={},h=f.commands;b=b.get(c);x.resizeItem(b,k,g,d);a=G({isLine:!1,type:b.type,content:k,x:0,y:0,w:g},a);f.tb=a.tb;f.tb2=a.tb2;b.w!=g&&(e.w=g);b.h!=d&&(e.h=d);e.content=k;null!=a.a&&b.a!==a.a&&(e.a=a.a,a.a>=d&&(e.h=a.a+Config.MIN_ICON_HEIGHT));g=Object.keys(e);if(0!=g.length){c=v(h,c);h=0;for(d=g.length;h<d;)k=g[h],c.fields[k]=e[k],h++;c.fields.tb=a.tb;c.fields.tb2=a.tb2;c.table="free"}};this.changeOneItem=
R;this.addToCommands=J;this.makeLeftPushBox=S;this.makeRightPushBox=T;this.makeUpPushBox=E;this.makeDownPushBox=F}var Drakon=new DrakonModule;
