function DraWidgets(ia,R,y,Ca,Da,Ea){function Fa(a){return this.width}function Ga(a){this.isChecked=a;Y(this)}function Ha(){var a,c,b,d,e;a=m(this.id);b=this.rect;c=b.left;d=b.top;e=b.width;p(a,c,d,e,b.height);a=m(this.id+"_edit");ja(a,e)}function Ia(a){return this.height}function Ja(){var a,c,b,d,e;b=this.rect;d=b.left;a=b.top;e=b.width;b=b.height;c=m(this.id);p(c,d,a,e,b);for(var f=d=0,g=this.lefts,h=g.length;f<h;){var l=g[f];a=l.hPadding||0;c=l.vPadding||0;l.width=l.measureWidth(this.height);d+=
a;C(l,d,c,l.width,b-2*c);d+=l.width;f++}f=0;g=this.rights;for(h=g.length;f<h;)l=g[f],a=l.hPadding||0,c=l.vPadding||0,l.width=l.measureWidth(this.height),e-=l.width+a,C(l,e,c,l.width,b-2*c),f++;this.center&&(a=Math.max(0,e-d),C(this.center,d,0,a,b))}function Ka(a){a=M(this.items,a);ka(this,a)}function La(){var a;for(a=0;a<this.items.length;)ka(this,a),a++}function Ma(){var a;a={checked:[],unchecked:[]};for(var c=0,b=this.items,d=b.length;c<d;){var e=b[c];e.checked?a.checked.push(e.id):a.unchecked.push(e.id);
c++}return a}function Na(a){a=M(this.items,a);return-1==a?null:this.items[a]}function Oa(a){a=M(this.items,a);return-1==a?!1:!!this.items[a].checked}function Pa(a){for(var c=0,b=this.items,d=b.length;c<d;){var e=b[c];e.row.className=e.id==a?"list_item_marked":"list_item";c++}}function Qa(a){return D.call(this,a)+3}function Ra(a){var c;c=M(this.items,a);-1!=c&&(this.items.splice(c,1),a=A(this.id,a),a=m(a),S(a))}function Sa(a){for(var c,b=0,d=this.items,e=d.length;b<e;){var f=d[b];c=A(this.id,f.id);
c=m(c);c.className=f.id==a?"list_item_marked":"list_item";b++}}function Ta(a,c,b){a=A(this.id,a);HtmlUtils.setText(a+"_"+c,b)}function Ua(a){this.items=[];m(this.id+"_list").innerHTML="";for(var c=0,b=a.length;c<b;){var d=a[c],e=void 0,f=void 0,g=void 0,h=void 0,l=h=void 0,h=void 0,g=this.columns;if(g.length==d.cells.length){h=this.id+"_list";h=m(h);l=k(h,"tr");l.id=A(this.id,d.id);d.row=l;l.className="list_item";B(l,"click",this.id,d.id,null,!1);O(l,this.id,d.id,null);for(h=0;h<g.length;){var e=
d.cells[h],f=g[h],n=l,q=this.id,r=d.id,t=h,p=void 0,w=void 0,v=p=void 0,u=void 0,p=0,w=A(q,r)+"_"+t,u=k(n,"td"),v=u.style;v.width=f.width;p=f.type;if("text"===p)v.padding="6px",v.lineHeight="120%",HtmlUtils.setDivText(u,e.text),u.id=w;else{if("image"===p)p=Z(u,e.src,e.width,e.height),f.clickable&&(u.className="black_hover common_button",B(u,"click",q,r,t,!0)),e.paddingLeft&&(v.paddingLeft=e.paddingLeft),e.paddingRight&&(v.paddingRight=e.paddingRight);else{if("button"!==p)throw"Unexpected switch value: "+
p;p=k(u,"div");v.padding="3px";p.className="internal_button common_button";B(u,"click",q,r,t,!0);HtmlUtils.setDivText(p,y(e.text))}p.id=w}h++}this.items.push(d)}else E("Wrong number of cells in row");c++}T(this)}function Va(a){a=M(this.items,a);la(this,a)}function Wa(){var a;for(a=0;a<this.items.length;)la(this,a),a++}function Xa(a){var c;c=M(this.items,a);-1!=c&&(this.items.splice(c,1),a=A(this.id,a),a=m(a),S(a))}function Ya(a,c){var b;b=A(this.id,a);HtmlUtils.setText(b,c)}function Za(a){this.items=
[];m(this.id+"_list").innerHTML="";for(var c=0,b=a.length;c<b;){var d=a[c],e=void 0,e=e=void 0;this.items.push(d);e=this.id+"_list";e=m(e);e=k(e,"div");e.id=A(this.id,d.id);var f=e,g=void 0;f.className="list_item";g=f.style;g.padding="6px";g.borderBottom="solid 1px silver";g.lineHeight="120%";HtmlUtils.setDivText(e,d.text);B(e,"click",this.id,d.id,null,!1);O(e,this.id,d.id,null);c++}T(this)}function T(a){var c,b;c=a.id+"_list";b=a.id+"_noItems";0==a.items.length?(I(c,"none"),I(b,"block")):(I(c,"block"),
I(b,"none"))}function $a(a){return this.active.measureHeight(a)}function ab(a){return this.active.measureWidth(a)}function bb(a){var c;a:{var b;b=this.kids;for(c=0;;){if(!(c<b.length)){c=-1;break a}if(b[c].id==a)break a;c++}}-1==c?E("Many.setActive: bad child id: "+a):(null!=this.active&&I(this.active.id,"none"),this.active=this.kids[c],I(a,"inline-block"))}function cb(){var a;aa(this);a=this.rect;C(this.active,0,0,a.width,a.height)}function db(a){var c;a in this.tabs?(c=this.id+"_combo",c=m(c),c.value=
a,ma(this.id,a)):E("Multipane.setActive: bad child id: "+a)}function eb(a){var c;c=this.padding;a-=2*this.padding;for(var b=0,d=this.kids,e=d.length;b<e;){var f=d[b];f.height=f.measureHeight(a);c+=f.height+this.padding;b++}return c}function fb(){var a,c,b,d,e,f,g;c=this.rect;e=c.left;f=c.top;g=c.width;d=c.height;b=m(this.id);a=this.measureHeight(g);c=g;a>d?(c=g-15,a=this.measureHeight(c),b.style.overflowY="scroll"):(d=a,b.style.overflow="hidden");m(this.id+"_inner").style.height=a+"px";p(b,e,f,g,
d);e=this.padding;c-=2*this.padding;f=0;g=this.kids;for(a=g.length;f<a;)b=g[f],C(b,this.padding,e,c,b.height),e+=b.height+this.padding,f++}function gb(a,c,b){var d,e;e=this.cell;""!=e.innerHTML&&(d=k(e,"span"),d.style.display="inline",d.style.color="cyan",HtmlUtils.setDivText(d," \u203a "),b||k(e,"br"));d=k(e,"span");d.style.display="inline";d.style.color="white";c&&(this.idToDiv[c]=d);HtmlUtils.setDivText(d,a);b?(d.style.fontWeight="normal",d.style.fontSize="80%",d.style.cursor="pointer",B(d,"click",
this.id,c,null,!1)):(d.style.fontWeight="normal",d.style.fontSize="100%")}function hb(){this.cell.innerHTML=""}function ib(a,c){var b;(b=this.idToDiv[a])&&HtmlUtils.setDivText(b,c)}function jb(){this.input.focus()}function kb(){return this.input.value}function lb(){/* var a,c,b,d,e,f,g,h,l;c=m(this.id);e=this.input;a=this.button;b=this.rect;g=b.left;h=b.top;l=b.width;b=b.height;d=b-2;f=l-2-b;p(c,g,h,l,b);p(e,1,0,f-1,d-1);p(a,f,0,d,d) */}function mb(a){var c,b;c=m(this.id);b=c.style;a?(b.background="#455A64",
c.className="common_button"):(b.background="#909090",c.className="")}function U(a){var c;if(this.customWidth)return this.customWidth;a=m(this.id);c=a.style;c.display="inline-block";c.position="absolute";delete c.width;c.left="0px";c.top="0px";return a.offsetWidth}function nb(a){var c;c=this.top.measureHeight(a);a=this.center.measureHeight(a);return c+a}function ob(){var a,c,b,d,e,f,g;a=this.rect;d=a.left;e=a.top;g=a.width;b=a.height;c=m(this.id);f=this.top.measureHeight(g);a=Math.max(0,b-f);p(c,d,
e,g,b);C(this.top,0,0,g,f);C(this.center,0,f,g,a)}function pb(a){for(var c,b=c=0,d=this.kids,e=d.length;b<e;){var f=d[b];f.height=f.measureHeight(a);c+=f.height;b++}return c}function na(){return this.width}function qb(){var a,c,b,d,e;a=this.rect;b=a.left;d=a.top;e=a.width;c=a.height;a=m(this.id);p(a,b,d,e,c);d=b=0;a=this.kids;for(c=a.length;d<c;){var f=a[d];f.height=f.measureHeight(e);C(f,0,b,e,f.height);b+=f.height;d++}}function D(a){var c,b;c=m(this.id);b=c.style;b.display="inline-block";b.position=
"absolute";delete b.height;b.left="0px";b.top="0px";b.width=a+"px";b.height="";return c.offsetHeight}function B(a,c,b,d,e,f){a["on"+c]=function(a){J(a,c,b,d,e,f)}}function r(a,c,b,d){var e;e=v.wrapException(function(a){d(a,b)});a["on"+c]=e}function O(a,c,b,d){a.oncontextmenu=function(a){HtmlUtils.stopPropagation(a);rb(a,"contextmenu",c,b,d);return!1}}function sb(a,c,b){var d,e;e=k(a,"select");e.id=c.parentId+"_combo";a=Utils.objectValues(c.tabs);a.sort(tb);for(var f=0,g=a.length;f<g;){var h=a[f];
d=k(e,"option");d.value=h.id;d.text=h.label;f++}e.onchange=function(a){ma(c.parentId,a.currentTarget.value)};b.measureWidth=D}function tb(a,c){return a.label.localeCompare(c.label)}function ka(a,c){var b,d;b=a.items[c];d=A(a.id,b.id);m(d+"_0").src=v.imagePath+"checked.png";b.checked=!0}function ub(a,c){return a.rank<c.rank?-1:a.rank>c.rank?1:a.text.localeCompare(c.text)}function F(a,c,b){t.set("widgets",a.id,c,b.id)}function N(a,c,b){c in a&&(b[c]=a[c])}function w(a,c){if(a.style)for(var b=0,d=a.style,
e=Object.keys(d),f=e.length;b<f;){var g=e[b];c.style[g]=d[g];b++}}function oa(a,c,b){var d;b.div=k(c,"div");b.myDiv=k(b.div,"div");b.kidsDiv=k(b.div,"div");b.myDiv.className="list_item";b.myDiv.display="inline-block";b.myDiv.style.paddingLeft=30*b.depth+"px";B(b.myDiv,"click",a.id,b.id,null,!1);O(b.myDiv,a.id,b.id,null);b.isFolder?(d=Z(b.myDiv,"plus-collapse.png",30,30),d.style.verticalAlign="middle",b.plusDiv=d,c=function(a,c){var d=b.id;HtmlUtils.stopPropagation(a);u(c,d).expanded?(c.collapse(d),
ba(a,"collapse",c.id,d,null,!1)):(c.expand(d),ba(a,"expand",c.id,d,null,!1))},d.style.cursor="default",r(d,"click",a,c)):(a=pa(b.myDiv),a.style.width="30px");a=Z(b.myDiv,b.icon,30,30);a.style.verticalAlign="middle";b.iconDiv=a;a=pa(b.myDiv);a.style.padding="8px";b.textDiv=a;HtmlUtils.setDivText(a,b.text)}function qa(a,c,b,d,e,f,g){var h;h=0;c&&(h=u(a,c),h=h.depth+1);a.items.insert("items",b,{parent:c,isFolder:d,icon:e,text:f,rank:g,depth:h});return u(a,b)}function ca(a,c,b){var d;t.createLink("widgets",
"top","widgets","p2","simple");t.createLink("widgets","center","widgets","p2","simple");da(b,["center","top"]);d=n(c,"top");c=n(c,"center");F(b,"top",z(a,d,b));F(b,"center",z(a,c,b));b.setRect=ob;b.measureHeight=nb}function ra(a,c){var b,d,e,f;if(c.type)if(d=q[c.type],"undefined"==typeof d)E('Unknown widget type: "'+c.type+'"');else return e=Utils.copyObject(c),b={signalId:e.signalId,type:e.type},f=t.insert("widgets",e.id,b),f.signalId||(f.signalId=f.id),b=k(a,"div"),b.id=f.id,e.id=f.id,d(b,e,f),
f.id;else E('"type" property is missing in node')}function z(a,c,b){a=ra(a,c);t.update("widgets",a,{parent:b.id});return K(a)}function x(){aa(this)}function S(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function sa(a){var c,b;(c=R.getElementById(a))&&S(c);b=K(a);c=b.kids.slice(0);b.destructor&&b.destructor();b=0;for(var d=c.length;b<d;)sa(c[b].id),b++;t.remove("widgets",a)}function da(a,c){a.destructor=function(){for(var b=0,d=c.length;b<d;)t.set("widgets",a.id,c[b],null),b++}}function I(a,c){m(a).style.display=
c}function P(a){a.style.display="inline-block"}function ea(a){if("height"in this)return this.height;E("dummy_measureHeight: height not specified")}function fa(a){if("width"in this)return this.width;E("dummy_measureWidth: width not specified")}function J(a,c,b,d,e,f){v.wrapException(function(){ba(a,c,b,d,e,f)})()}function ba(a,c,b,d,e,f){b=K(b);v.onEvent(a,c,b,d,e);f&&a.stopPropagation&&a.stopPropagation()}function m(a){var c;if(c=R.getElementById(a))return c;throw Error("get: element '"+a+"' not found");
}function M(a,c){var b,d,e;e=-1;for(b=0;b<a.length;){d=a[b];if(d.id==c){e=b;break}b++}return e}function ta(a,c){var b;b=a.getBoundingClientRect();return{x:c.clientX-b.left,y:c.clientY-b.top}}function n(a,c){var b;if(b=a[c])return b;E('Missing property "'+c+'" for "'+a.type+'", id: '+a.id)}function Q(a,c,b){return c in a?a[c]:b}function u(a,c){return a.items.get("items",c)}function K(a){return t.get("widgets",a)}function L(a){a.style.display="none"}function k(a,c){var b;b=R.createElement(c);a.appendChild(b);
return b}function ua(a){a=a.style;a.width=null;a.display="inline-block";a.position="absolute";a.left="0px";a.top="0px";a.right="0px";a.bottom="0px"}function pa(a){a=k(a,"div");a.style.display="inline-block";return a}function Z(a,c,b,d){a=k(a,"img");a.src=v.imagePath+c;a.width=b;a.height=d;a.draggable=!1;return a}function A(a,c){return a+"_item_"+c}function vb(a,c){c.isChecked=!c.isChecked;Y(c);J(a,"check",c.id,null,null,!0)}function va(a,c){wa(c,a,!0)}function ma(a,c){var b;b=K(a);b.active=c;K(a+
"_many").setActive(c);b.rect&&b.setRect()}function xa(a,c){wa(c,a,!1)}function wb(a,c){c.input.value&&(c.input.value="",V(c),J(a,"input",c.id,null,null,!0))}function xb(a,c){V(c);J(a,"input",c.id,null,null,!0)}function yb(a,c){if("Escape"==a.key||27==a.keyCode)HtmlUtils.preventDefaultHandling(a),c.clear(),J(a,"escape",c.id,null,null,!0)}function ga(a,c){var b,d,e;c.dragging&&(b=c.rect,d=m(c.id),d=ta(d,a),d=d.x+c.shift,e=b.width,b=c.splitterWidth,d=Math.max(d,b),d=Math.min(d,e-1.5*b),c.current=d,ya(c))}
function za(a,c){var b;b=HtmlUtils.touchToMouse(a);a.preventDefault();ga(b,c)}function G(a,c){var b,d;c.dragging&&(c.dragging=!1,b=c.rect,d=c.current,c.isLeft?c.left=d:c.right=b.width-d,L(c.dummy),c.setRect(),J(a,"resize",c.id,null,null,!1))}function ya(a){var c,b;c=a.rect.height;b=a.splitterWidth;p(a.dummy,a.current-b/2,0,b,c-2)}function E(a){throw Error(a);}function ha(a,c){for(var b=0,d=c.kids.slice(0),e=d.length;b<e;)ha(a,d[b]),b++;S(c.div);a.items.remove("items",c.id)}function Aa(a){a.items=
new TabGen4;a.items.createTable("items");a.items.createLink("items","parent","items","kids","list")}function zb(){var a,c,b,d,e,f,g,h,l,k;aa(this);e=this.overShift;a=this.rect;k=a.width;a=a.height;l=this.splitterWidth;f=this.overlayWidth;c=this.left;g=this.right;h=b=l;this.leftVisible||(b=c=0);this.rightVisible||(h=g=0);d=k-g-c-b/2-h/2;10<=d||(0==g?0==c?d=10:(c=k-g-10-b-h,c>=l?(d=k-g-c-b/2-h/2,this.left=c,this.right=g):(c=l,d=10)):(g=k-c-h-b,g>=1.5*l?(d=k-g-c-b/2-h/2,this.left=c,this.right=g):(g=
1.5*l,0==c?d=10:(c=k-g-10-b-h,c>=l?(d=k-g-c-b/2-h/2,this.left=c,this.right=g):(c=l,d=10)))));0==c?(m(this.leftChild.id).style.display="none",L(this.leftSplitter),L(this.leftOverlay)):(m(this.leftChild.id).style.display="inline-block",P(this.leftSplitter),P(this.leftOverlay),W(this.leftChild.id,0,0,c-l/2,a),p(this.leftSplitter,0+c-l/2,0,l,a),p(this.leftOverlay,0+c-f/2+e,0,f,a));k=0+k;0==g?(m(this.rightChild.id).style.display="none",L(this.rightSplitter),L(this.rightOverlay)):(m(this.rightChild.id).style.display=
"inline-block",P(this.rightSplitter),P(this.rightOverlay),W(this.rightChild.id,k-g+l/2,0,g-l/2,a),p(this.rightSplitter,k-g-l/2,0,l,a),p(this.rightOverlay,k-g-f/2+e,0,f,a));W(this.middleChild.id,0+c+b/2,0,d,a)}function W(a,c,b,d,e){a=K(a);C(a,c,b,d,e)}function rb(a,c,b,d,e){ia.setTimeout(function(){J(a,c,b,d,e,!1)},10)}function Y(a){m(a.id).style.backgroundImage="url('"+(v.imagePath+(a.isChecked?"checked.png":"unchecked.png"))+"')"}function p(a,c,b,d,e){var f;f=a.style;f.display="inline-block";f.position=
"absolute";f.left=c+"px";f.top=b+"px";ja(a,d);b=a.style;f=H(b.paddingTop);c=H(b.paddingBottom);d=H(b.borderTopWidth);a=H(b.borderBottomWidth);b.height=e-f-c-d-a+"px"}function C(a,c,b,d,e){a.rect={left:c,top:b,width:d,height:e};a.setRect()}function V(a){/* var c;c=a.button;a=a.input.value;(a=a.trim())?(c.src=v.imagePath+"backspace.png",c.style.cursor="pointer"):(c.src=v.imagePath+"search-s.png",c.style.cursor="default") */}function aa(a){var c,b,d,e;c=a.rect;b=c.left;d=c.top;e=c.width;c=c.height;a=m(a.id);
p(a,b,d,e,c)}function ja(a,c){var b,d,e,f,g;g=a.style;d=H(g.paddingLeft);f=H(g.paddingRight);b=H(g.borderLeftWidth);e=H(g.borderRightWidth);g.width=c-d-f-b-e+"px"}function wa(a,c,b){var d;d=m(a.id);c=ta(d,c);a.isLeft=b;a.dragging=!0;P(a.dummy);d=a.rect;b?(b=a.left,ua(a.leftOverlay),L(a.rightOverlay)):(b=d.width-a.right,ua(a.rightOverlay),L(a.leftOverlay));a.current=b;a.shift=b-c.x;ya(a)}function H(a){if(a&&"initial"!=a){if("medium"==a)return 1;a=a.substring(0,a.length-2);a=parseFloat(a);return isNaN(a)?
0:a}return 0}function Ab(){this.div().innerHTML="";Aa(this)}function Bb(a){a=u(this,a);a.expanded&&(a.plusDiv.src=v.imagePath+"plus-collapse.png",a.expanded=!1,a.kidsDiv.innerHTML="")}function Cb(){for(var a=0,c=this.items.getState().items,b=Object.keys(c),d=b.length;a<d;){var e=c[b[a]];e.myDiv&&(e.myDiv.style.background="",e.myDiv.style.color="",e.myDiv.className="list_item");a++}}function Db(a){a=u(this,a);if(!a.expanded){a.plusDiv.src=v.imagePath+"plus-expand.png";a.expanded=!0;for(var c=0,b=a.kids,
d=b.length;c<d;)oa(this,a.kidsDiv,b[c]),c++}}function Eb(a){return u(this,a)}function Fb(a){return u(this,a).parent.id}function Gb(a){var c;c=this.items.getState().items;return a in c?!0:!1}function Hb(a){for(var c=0,b=this.items.getState().items,d=Object.keys(b),e=d.length;c<e;){var f=d[c],g=b[f];g.myDiv&&(g.myDiv.className=f==a?"list_item_marked":"list_item");c++}}function Ib(a){(a=this.items.getRowOrNull("items",a))&&ha(this,a)}function Jb(a){var c;a=a||this.root;c=u(this,a);c.kidsDiv.innerHTML=
"";a=0;c=c.kids.slice(0);for(var b=c.length;a<b;)ha(this,c[a]),a++}function Kb(a,c){var b;b=u(this,a);b.text=c;b.textDiv&&HtmlUtils.setDivText(b.textDiv,c)}function Lb(a){var c;a=u(this,a).div;c=m(this.id);HtmlUtils.scrollIntoViewCore(c,a)}function Mb(a){this.deselect();for(var c=0,b=this.items.getState().items,d=Object.keys(b),e=d.length;c<e;){var f=d[c],g=b[f];g.myDiv&&f==a&&(g.myDiv.style.background="#455A64",g.myDiv.style.color="white");c++}}function Nb(a,c){var b;a=a||this.root;b=u(this,a);this.removeChildren(a);
for(var d=0,e=c,f=e.length;d<f;){var g=e[d];qa(this,a,g.id,g.isFolder||!1,g.icon,g.text,g.rank);d++}c=b.kids;c.sort(ub);d=0;e=c;for(f=e.length;d<f;)g=e[d],b.expanded&&oa(this,b.kidsDiv,g),d++}function Ob(a,c){var b;b=u(this,a);b.iconDiv&&(b.iconDiv.src=v.imagePath+c)}function Pb(a,c){var b;b=this.items.getState().items;a in b&&(b=b[a],b=b.textDiv,HtmlUtils.setDivText(b,c))}function la(a,c){var b,d,e;e=a.items[c];b=e.id;d=e.cells[0].src;b=A(a.id,b);m(b+"_0").src=v.imagePath+d;e.checked=!1}function Ba(a){var c;
return function(b,d){c=HtmlUtils.touchToMouse(b);b.preventDefault();a(c,d)}}var X=new ToolTip(ia,R),q={},t=new TabGen4(Ea);t.setNextId(Ca);this.imagePath=Da||"/static/images/";var v=this;this.wrapException=function(a){return a};this.onEvent=function(){};this.getToolTip=function(){return X};q.dummy=function(a,c,b){w(c,a);b.setRect=x;b.measureWidth=fa;b.measureHeight=ea;N(c,"height",b);N(c,"width",b)};q.vdock=ca;q.vpanel=function(a,c,b){var d;d=n(c,"kids");b.width=c.width;c=0;for(var e=d.length;c<e;)z(a,
d[c],b),c++;b.setRect=qb;b.measureHeight=pb;b.measureWidth=na};q.hdock=function(a,c,b){var d;b.height=n(c,"height");w(c,a);b.setRect=Ja;b.measureHeight=Ia;b.lefts=[];b.rights=[];t.createLink("widgets","leftLink","widgets","lefts","list");t.createLink("widgets","rightLink","widgets","rights","list");t.createLink("widgets","center","widgets","p2","simple");da(b,["center"]);for(var e=0,f=n(c,"lefts"),g=f.length;e<g;){var h=f[e];d=z(a,h,b);F(d,"leftLink",b);N(h,"vPadding",d);N(h,"hPadding",d);e++}e=0;
f=n(c,"rights");for(g=f.length;e<g;)h=f[e],d=z(a,h,b),F(d,"rightLink",b),N(h,"vPadding",d),N(h,"hPadding",d),e++;c.center&&(d=z(a,c.center,b),F(b,"center",d))};q.text_button=function(a,c,b){var d;a.className="common_button";b.customWidth=c.customWidth||0;HtmlUtils.noContext(a);a.style.textAlign="center";w(c,a);c.className&&(a.className+=" "+c.className);d=n(c,"text");c.raw||(d=y(d));HtmlUtils.setDivText(a,d);b.setRect=x;b.measureWidth=U;b.enable=mb;(b=c.tooltip)&&X.makeFromElement(a,y(b));B(a,"click",
c.id,null,null,!0)};q.image_button=function(a,c,b){var d,e,f,g;f=a.style;a.className="common_button";HtmlUtils.noContext(a);g=n(c,"width");d=n(c,"height");e=n(c,"image");b.width=g;b.height=d;w(c,a);e="url('"+(v.imagePath+e)+"')";f.display="inline-block";f.width=g+"px";f.height=d+"px";f.backgroundImage=e;f.backgroundSize=g+"px "+d+"px";b.setRect=x;b.measureWidth=fa;b.measureHeight=ea;B(a,"click",c.id,null,null,!0);(c=c.tooltip)&&X.makeFromElement(a,y(c))};q.page=function(a,c,b){var d;a=k(a,"innerDiv");
a.id=b.id+"_inner";d=n(c,"kids");b.padding=c.padding||0;b.width=c.width;for(var e=0,f=d.length;e<f;)z(a,d[e],b),e++;w(c,a);b.setRect=fb;b.measureHeight=eb;b.measureWidth=na};q.list=function(a,c,b){var d;b.items=[];a.style.overflowY="scroll";w(c,a);d=k(a,"div");a=k(a,"div");d.id=c.id+"_list";a.id=c.id+"_noItems";HtmlUtils.setDivText(a,y("MES_NO_ITEMS"));a.style.textAlign="center";a.style.padding="30px";a.style.color="#ff8080";T(b);b.setRect=x;b.setItems=Za;b.remove=Xa;b.setItemText=Ya};q.list_grid=
function(a,c,b){var d;b.items=[];b.columns=n(c,"columns");b.checkable=c.checkable||!1;c.noScroll||(a.style.overflowY="scroll");O(a,b.id,null,null);w(c,a);d=k(a,"table");a=k(a,"div");d.style.width="100%";d.id=c.id+"_list";a.id=c.id+"_noItems";HtmlUtils.setDivText(a,y("MES_NO_ITEMS"));a.style.textAlign="center";a.style.padding="30px";a.style.color="#ff8080";T(b);b.setRect=x;b.setItems=Ua;b.remove=Ra;b.setItemText=Ta;b.setActive=Sa;b.check=Ka;b.uncheck=Va;b.getChecked=Ma;b.checkAll=La;b.uncheckAll=Wa;
b.isChecked=Oa;b.mark=Pa;b.getItem=Na;b.measureHeight=Qa;c.rows&&b.setItems(c.rows)};q.tree=function(a,c,b){b.setRect=x;b.clear=Ab;b.setIcon=Ob;b.setText=Pb;b.setChildren=Nb;b.removeChildren=Jb;b.select=Mb;b.deselect=Cb;b.expand=Db;b.collapse=Bb;b.remove=Ib;b.rename=Kb;b.mark=Hb;b.getParent=Fb;b.hasItem=Gb;b.scrollIntoView=Lb;b.getItem=Eb;b.div=a;Aa(b);w(c,a);a.style.overflowY="auto";a.style.overflowX="hidden";a.style.whiteSpace="nowrap";c=qa(b,null,"<root>",!0,"none","<root>",0);b.root=c.id;c.kidsDiv=
b.div;c.expanded=!0;c.depth=-1;O(a,b.id,null,null)};q.many=function(a,c,b){var d;b.active=null;for(var e=0,f=n(c,"kids"),g=f.length;e<g;)d=z(a,f[e],b),I(d.id,"none"),e++;w(c,a);b.setRect=cb;b.measureHeight=$a;b.measureWidth=ab;b.setActive=bb};q.label=function(a,c,b){var d;a.style.padding="5px";d=n(c,"text");d=c.raw?d:y(d);HtmlUtils.setDivText(a,d);w(c,a);b.setRect=x;b.measureWidth=U;b.measureHeight=D};q.pane=function(a,c,b){var d,e;d={type:"hdock",lefts:[{type:"label",text:n(c,"text"),style:{padding:"7px"}}],
rights:[{id:c.id+"_close",type:"image_button",image:"grey-cross.png",style:{},width:30,height:30}],height:30,style:{background:"#E2EDF5",borderBottom:"1px solid #455A64"}};e=n(c,"kid");ca(a,{id:c.id,type:"vdock",top:d,center:e},b)};q.check=function(a,c,b){var d,e;d=a.style;a.className="common_button";HtmlUtils.noContext(a);e=n(c,"width");c=n(c,"height");b.width=e;b.height=c;d.display="inline-block";d.width=e+"px";d.height=c+"px";d.backgroundSize=e+"px "+c+"px";d.backgroundPosition="center";d.backgroundRepeat=
"no-repeat";Y(b);a.style.cursor="default";r(a,"click",b,vb);b.setRect=x;b.measureWidth=Fa;b.setChecked=Ga};q.search=function(a,c,b){var d;d=n(c,"width");b.width=d;c=n(c,"height");b.height=c;b.setRect=lb;b.measureWidth=fa;b.measureHeight=ea;a.style.background="white";a.style.border="solid 1px #455A64";b.clear=function(){b.input.value="";/* V(b) */};b.getValue=kb;b.focus=jb;d=k(a,"input");d.type="text";d.style.outline="none";d.style.background="white";d.style.border="none";d.style.padding="2px";b.input=d;
/* r(d,"input",b,xb); *//* r(d,"keydown",b,yb); */a=k(a,"img");a.width=c;a.height=c;a.style.display="none";a.draggable=!1;b.button=a;/* r(a,"click",b,wb);V(b) */};q.wbutton=function(a,c,b){var d;a.className="common_button";b.padding=c.padding||10;a.style.padding=b.padding+"px";a.style.borderRadius="5px";HtmlUtils.noContext(a);a.style.textAlign="center";a.style.lineHeight="120%";a.style.whiteSpace="normal";w(c,a);c.className&&(a.className+=" "+c.className);d=y(n(c,"text"));HtmlUtils.setDivText(a,d);b.setRect=
x;b.measureHeight=D;(b=c.tooltip)&&X.makeFromElement(a,y(b));B(a,"click",c.id,null,null,!0)};q.wlabel=function(a,c,b){var d;a.style.textAlign=c.textAlign||"left";a.style.textAlign="left";a.style.lineHeight="120%";a.style.whiteSpace="normal";a.style.width="100%";w(c,a);d=n(c,"text");c=c.raw?d:y(d);HtmlUtils.setDivText(a,c);b.text=c;b.div=a;b.setRect=x;b.measureHeight=D};q.custom=function(a,c,b){n(c,"builder")(a,c,b);b.setRect=x;b.measureHeight=D;b.measureWidth=U};q.edit=function(a,c,b){var d,e,f,g;
e=n(c,"editType");g=Q(c,"water","");d=k(a,"div");d.id=c.id+"_error";d.style.color="#600000";d.style.display="none";d.style.fontWeight="bold";d.style.fontSize="90%";f=k(a,"div");d=k(f,"input");d.type=e;g&&(e=k(f,"div"),e.style.position="absolute",e.style.left="10px",e.style.bottom="10px",e.style.color="grey",e.style.pointerEvents="none",HtmlUtils.setDivText(e,g),HtmlUtils.setPasswordWatermark(d,e,g));d.className="mousetrap";d.style.padding="10px";d.style.margin="0px";d.style.border="solid 1px #707070";
w(c,a);B(d,"keypress",b.id,null,null,!1);d.id=c.id+"_edit";b.setRect=Ha;b.measureHeight=D};q.splitter=function(a,c,b){var d,e,f;t.createLink("widgets","leftChild","widgets","p2","simple");t.createLink("widgets","rightChild","widgets","p2","simple");t.createLink("widgets","middleChild","widgets","p2","simple");da(b,["leftChild","rightChild","middleChild"]);d=n(c,"leftChild");e=n(c,"middleChild");f=n(c,"rightChild");b.splitterWidth=c.splitterWidth||6;b.left=c.left||200;b.right=c.right||200;b.leftVisible=
Q(c,"leftVisible",!0);b.rightVisible=Q(c,"rightVisible",!0);b.overlayWidth=Q(c,"overlayWidth",20);b.overShift=Q(c,"overShift",5);F(b,"leftChild",z(a,d,b));F(b,"middleChild",z(a,e,b));F(b,"rightChild",z(a,f,b));d=k(a,"div");f=k(a,"div");c=k(a,"div");e=k(a,"div");a=k(a,"div");b.leftSplitter=d;b.rightSplitter=f;b.leftOverlay=c;b.rightOverlay=e;b.dummy=a;a.style.display="none";c.style.zIndex=10;e.style.zIndex=10;c.className="dumb";e.className="dumb";a.style.zIndex=5;a.style.background="#5090ff";a.style.border=
"solid 1px black";d.style.background="#455A64";f.style.background="#455A64";d.style.borderLeft="solid 1px #455A64";d.style.borderRight="solid 1px #455A64";f.style.borderLeft="solid 1px #455A64";f.style.borderRight="solid 1px #455A64";c.style.cursor="ew-resize";e.style.cursor="ew-resize";r(c,"mousedown",b,va);r(c,"mousemove",b,ga);r(c,"mouseout",b,G);r(c,"mouseup",b,G);r(e,"mousedown",b,xa);r(e,"mousemove",b,ga);r(e,"mouseout",b,G);r(e,"mouseup",b,G);r(c,"touchstart",b,Ba(va));r(c,"touchmove",b,za);
r(c,"touchend",b,G);r(c,"touchcancel",b,G);r(e,"touchstart",b,Ba(xa));r(e,"touchmove",b,za);r(e,"touchend",b,G);r(e,"touchcancel",b,G);b.setRect=zb};q.path=function(a,c,b){var d;b.idToDiv={};a=k(a,"table");a.style.tableLayout="fixed";a.width="100%";b.table=a;a=k(a,"tr");d=k(a,"td");a=d.style;b.cell=d;a.verticalAlign="middle";a.color="white";a.paddingLeft="5px";a.lineHeight="130%";a.whiteSpace="nowrap";a.overflow="hidden";a.height="52px";w(c,d);b.setRect=x;b.measureHeight=D;b.measureWidth=U;b.addStage=
gb;b.clear=hb;b.renameStage=ib};q.multi_pane=function(a,c,b){var d,e,f,g;b.active=null;d=n(c,"kids");f={id:b.id+"_many",type:"many",kids:d};g={};for(var h=0,k=d.length;h<k;){var m=d[h];e=y(n(m,"tab"));e={id:n(m,"id"),label:e};g[e.id]=e;h++}ca(a,{id:c.id,type:"vdock",top:{type:"hdock",lefts:[{type:"custom",builder:sb,tabs:g,parentId:b.id}],rights:[{id:c.id+"_close",type:"image_button",image:"grey-cross.png",style:{},width:30,height:30}],height:30,style:{background:"#E2EDF5",borderBottom:"1px solid #455A64"}},
center:f},b);b.tabs=g;b.setActive=db};t.createTable("widgets");t.createLink("widgets","parent","widgets","kids","list");this.createWidget=ra;this.getWidget=K;this.resizeWidget=W;this.deleteWidget=sa;this.foreach=function(a){for(var c=0,b=t.getState().widgets,d=Object.keys(b),e=d.length;c<e;)a(b[d[c]]),c++}};
