function ItemsModule(V){function E(){this.a=this.h=this.w=this.tb2=this.tb=null}function Fa(b,a,c){this.id=b;this.xOffset=a;this.yOffset=c}function w(b,a){var c=q(b);return z(a,A(b),b.content,b.w,c)}function x(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)}function W(b,a,c){b=n(c,a);c.drawShape(b,"rectangle",a.x,a.y,[a.w,a.h],m(a,null));var d=q(a);v(c,b,a.x,a.y,a.w,d);k(a,b,0,0);t(c,b,a,"left",d)}function r(b,a,c,d){d.push({x:b,y:a,name:c})}function p(b,a,c){X[b]={size:function(b){return new Utils.Size(a,
c)}}}function Y(b,a,c){b=n(c,a);c.drawShape(b,"beginend",a.x,a.y,[a.w,a.h],m(a,null));var d=q(a);v(c,b,a.x,a.y,a.w,d);k(a,b,0,0);t(c,b,a,"center",d)}function J(b,a){var c=w(b,a);c.h=3*c.h/2;return c}function Z(b,a,c,d,f){var h=m(a,null);b=n(c,a);k(a,b,0,0);c.drawShape(b,"poly",a.x,a.y,d(a),h);d={lineThickness:h.lineThickness,lineColor:h.lineColor};c.drawShape(b,"poly",a.x,a.y,Ga(a),d);B(a.content);d=a.y-a.h+a.a;var h=a.x,e=a.w-Config.INPUT_LEFT;f||(h=a.x+Config.INPUT_LEFT/2,e=a.w-Config.INPUT_LEFT/
2);y(c,b,a,"left",h,d,e,a.tb2);f=D(a);d=q(a);v(c,b,f.x,f.y,f.w,d);y(c,b,a,"left",f.x,f.y,f.w,a.tb,d)}function m(b,a){var c={},d;d=a||b.type;var f=b.content;d=f&&f.fillColor?f.fillColor:Theme.getIconBack(d);c.fillColor=d;d=a||b.type;d=(f=b.content)&&f.lineColor?f.lineColor:Theme.getIconBorder(d);c.lineColor=d;c.lineThickness=aa(b);c.lineStyle=b.content?b.content.lineStyle:"solid";d=b.content?b.content.shadow:!1;c.shadow=d;d=(d=b.content)&&d.secondaryColor?d.secondaryColor:"shelf"==b.type?Theme.getIconSecondaryBack("insertion"):
Theme.getIconSecondaryBack(b.type);c.secondaryColor=d;"none"==c.lineColor&&(c.lineThickness=0);return c}function Ha(b){var a={},c=b.content||{};a.lineColor=c.lineColor||H();a.lineThickness=aa(b)||1;a.lineStyle=b.content?b.content.lineStyle:"solid";a.arrowStart=c.arrowStart;a.arrowEnd=c.arrowEnd;a.fillColor=Theme.getIconBack("action");return a}function ba(b,a,c,d){d=d[a.id];if("green"===d){if(a.isLine){d=b.getHead(a);var f=b.getTail(a);if(a.isVertical)"down"===a.role||"par-down"===a.role?ca(d,f,a,
c,!0):ca(d,f,a,c,!1);else{b=Utils.canInsertInHorizontal(b,a);var h=d.x;b=c.createHCandy(h,d.y,f.x-d.x,b,h+d.w,f.x,"line_candies");k(a,b,0,0)}}else"junction"===a.type?(b=c.createJCandy(a.x,a.y,"#00ff00","icon_candies"),k(a,b,0,0)):da(a,c,"#00ff00");b=0;d=ea(a);for(f=d.length;b<f;){var h=d[b],e=c.createJCandy(h.x,h.y,"yellow","free_candies");k(a,e,h.x-a.x,h.y-a.y);b++}}else"blue"===d&&da(a,c,"#00ffff")}function v(b,a,c,d,f,h){h&&(c=new Utils.Point(c-f+(Config.LINK_PADDING+Config.LINK_PADDING/2)-1,d),
b.drawLinkIcon(a,h,c.x,c.y))}function fa(b,a){if(a.primitives){for(var c=0,d=a.primitives,f=d.length;c<f;)b.deleteItem(d[c].id),c++;a.primitives=null}}function ga(b,a){var c=b.w-b.content.h0x/2,c=z(a,A(b),b.content,c);c.w=b.w;return c}function ha(b,a,c,d){d.h0x=Math.min(d.h0x,a)}function ia(b,a,c){b=n(c,a);c.drawShape(b,"rounded",a.x,a.y,[a.w,a.h,a.content.radius,0],m(a,"question"));k(a,b,0,0);var d=q(a);v(c,b,a.x,a.y,a.w,d);"raction"==a.type?t(c,b,a,"center",d):t(c,b,a,"left",d)}function K(b){var a=
b.x,c=a+b.w,d=b.y,f=d+b.h;b=Math.min(a,c);a=Math.max(a,c);c=Math.min(d,f);d=Math.max(d,f);return new Utils.Box(b-Config.TOUCH_MARGIN,c-Config.TOUCH_MARGIN,a+Config.TOUCH_MARGIN,d+Config.TOUCH_MARGIN)}function z(b,a,c,d,f){var h=B(c),e=2*(d-h);f&&(e-=2*Config.LINK_PADDING);c&&b.setFont(c.font);b=Utils.buildFlow(b,a,e);h=L(b.height,h);a=new E;a.w=d;a.h=h;a.tb=b;return a}function ja(b){var a=e[b.type];if(a.candies)b=a.candies(b);else{a=[];if(b.free){var c=b.x-b.w,d=b.x+b.w,f=b.y-b.h,h=b.y+b.h;r(c,f,
Const.FR_LU,a);r(b.x,f,Const.FR_UP,a);r(d,f,Const.FR_RU,a);r(d,b.y,Const.FR_RI,a);r(d,h,Const.FR_RD,a);r(b.x,h,Const.FR_DO,a);r(c,h,Const.FR_LD,a);r(c,b.y,Const.FR_LE,a)}else c=b.x-b.w,d=b.x+b.w,f=b.y-b.h,h=b.y+b.h,r(c,f,Const.DRN_SIZE_L,a),r(c,b.y,Const.DRN_SIZE_L,a),r(c,h,Const.DRN_SIZE_L,a),r(d,f,Const.DRN_SIZE_R,a),r(d,b.y,Const.DRN_SIZE_R,a),r(d,h,Const.DRN_SIZE_R,a);b=a}return b}function M(b){var a=-b.h;b=C(b)+Config.INPUT_OVERLAP;return(a+b)/2}function C(b){return-b.h+2*b.a}function H(){return ka||
Theme.getLine()}function F(b){var a={};a.lineColor=H();a.lineThickness=N;b&&b.isSkewer&&(a.lineThickness+=2);return a}function ea(b){var a=0,c=[],a=e[b.type];if(a.handles)c=a.handles(b);else{var d=b.content,a=b.type;"gdur"===a?d.right?(c.push({x:b.x-d.h0x,y:b.y-d.h0y,name:Const.FR_0}),c.push({x:b.x-d.h1x,y:b.y+d.h1y,name:Const.FR_1})):(c.push({x:b.x+d.h0x,y:b.y-d.h0y,name:Const.FR_0}),c.push({x:b.x+d.h1x,y:b.y+d.h1y,name:Const.FR_1})):"callout"===a?c.push({x:b.x+d.h0x,y:b.y+d.h0y,name:Const.FR_0}):
"f_rounded"===a&&r(b.x+b.w-d.radius,b.y-b.h,"H_EW",c)}return c}function la(b){var a=e[b];if(a)return a;throw"Unsupported item type: '"+b+"'";}function ma(b){var a=b.w;b=b.h;a=Math.sqrt(a*a+b*b);return Math.max(40,a)}function q(b){return b.content?b.content.status?b.content.status:(b=b.content.link)?-1==b.indexOf("youtube.com")&&-1==b.indexOf("vimeo.com")?"link":"video":null:null}function D(b){var a=0,c=b.x,d=b.y,f=b.w,a=b.type;"case"===a||"branch"===a?d-=Math.floor(b.h/3):"input"===a||"output"===
a||"process"===a?(B(b.content),a=b.h-b.a,b=b.y+b.h-a,c-=Config.INPUT_LEFT,d=b,f-=Config.INPUT_LEFT):"insertion"===a?f-=6:"shelf"===a&&(a=b.h-b.a,d=b=b.y+b.h-a);return{x:c,y:d,w:f}}function na(b){var a=X[b];if(a)return a;throw Error("Subtype '"+b+"' not found");}function B(b){return b?(b=parseInt(b.padding),isNaN(b)?Config.ICON_PADDING:b):Config.ICON_PADDING}function A(b){return b.content?b.content.txt||"":""}function oa(b){var a=b.content;return a&&a.textColor?a.textColor:Theme.getIconFont(b.type)}
function aa(b){return(b=b.content)?(b=b.lineThickness,isNaN(parseInt(b))?Theme.getThickness():b):Theme.getThickness()}function pa(b,a,c){b=K(b);return Utils.hitBox(b,a,c)}function qa(b,a){var c=q(b),c=z(a,A(b),b.content,b.w-5,c);c.w=b.w;return c}function ra(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)}function sa(b,a,c){b=n(c,a);var d=m(a,"action"),f=Utils.copyObject(d);f.fillColor=d.secondaryColor;c.drawShape(b,"rectangle",a.x,a.y,[a.w,a.h],d);m(a,null).fillColor="";var d=Math.floor(3),h=a.x+
a.w-d;c.drawShape(b,"rectangle",a.x-a.w+d,a.y,[d,a.h],f);c.drawShape(b,"rectangle",h,a.y,[d,a.h],f);f=D(a);d=q(a);v(c,b,f.x,f.y,f.w,d);k(a,b,0,0);y(c,b,a,"left",f.x,f.y,f.w,a.tb,d)}function O(b,a){var c=Math.floor(B(b.content)/2),c=z(a,A(b),b.content,b.w-c);c.w=b.w;return c}function Ia(b,a){var c=0-b,d=0+b,f=0-a,h=0+a,e=f+2/3*a;return[c,e,0,f,d,e,d,h,c,h]}function ta(b,a){var c=0-b,d=0+b,f=0-a,h=0+a,e=h-2/3*a;return[c,f,d,f,d,e,0,h,c,e]}function Ja(b,a,c,d){var f=b-c+.5,h=f+6-.5;b+=c;c=b+6;var e=
a-d,l=e+6;a+=d;d=a+6;return[f,e,b,e,b,l,c,l,c,d,h,d,h,a,f,a]}function Ka(b){var a=-b.w,c=-b.w+1.4*Config.INPUT_LEFT,d=-b.w+2*Config.INPUT_LEFT,f=b.w-Config.INPUT_LEFT,h=b.w,e=-b.h,l=M(b),u=C(b),k=C(b)+Config.INPUT_OVERLAP;b=b.h;return[a,e,f,e,f,u,h,u,h,b,d,b,d,k,a,k,c,l]}function Ga(b){var a=-b.w,c=b.w-2*Config.INPUT_LEFT,d=C(b);b=b.h;return[a,b,a,d,c,d,c,b]}function La(b){var a=-b.w,c=b.w-2*Config.INPUT_LEFT,a=-b.w+2*Config.INPUT_LEFT,c=b.w,d=C(b);b=b.h;return[a,b,a,d,c,d,c,b]}function Ma(b){var a=
-b.w,c=-b.w+Config.INPUT_LEFT,d=b.w-2*Config.INPUT_LEFT,f=b.w-1.4*Config.INPUT_LEFT,h=b.w,e=-b.h,l=M(b),u=C(b),k=C(b)+Config.INPUT_OVERLAP;b=b.h;return[a,b,a,u,c,u,c,e,f,e,h,l,f,k,d,k,d,b]}function Na(b){var a=-b.w,c=-b.w+Config.INPUT_LEFT,d=b.w-2*Config.INPUT_LEFT,f=b.w,h=-b.h;M(b);var e=C(b),l=C(b)+Config.INPUT_OVERLAP;b=b.h;return[a,b,a,e,c,e,c,h,f,h,f,l,d,l,d,b]}function Oa(b,a,c,d){b+=.5;a+=.5;var f=b+c;b-=c;c=a+d;d=a-d;return[b,d,f,d,f,c,b,c,b+1.4*Config.INPUT_LEFT,a]}function Pa(b,a,c,d,f){var e=
b+c;b-=c;f=b+f;c=a+d;d=a-d;return[b,a,f,d,e,d,e,c,f,c]}function Qa(b,a){var c=0-b,d=0+b,f=0-a,e=0+a,g=f+20;return[c,e,c,g,c+20,f,d-20,f,d,g,d,e]}function Ra(b,a){var c=0-b,d=0+b,f=0-a,e=0+a,g=e-20;return[c,f,d,f,d,g,d-20,e,c+20,e,c,g]}function ua(b,a,c,d,f){b+=.5;a+=.5;var e=b+c;b-=c;f=e-f;c=a+d;d=a-d;return[b,d,f,d,e,a,f,c,b,c]}function P(b,a){var c=0-b,d=0-a,f=d+2*a,e=c+2*b;return[c,d,e,d,e-20,f,c+20,f]}function Sa(b,a){var c=0-b,d=0+b,f=0-a,e=0+a;return[c,e,c+10,f,d,f,d-10,e]}function n(b,a){var c;
c=a.free?"free":"icons";a.content&&b.setFont(a.content.font);return b.createTexture(a.x,a.y,-a.w,-a.h,2*a.w,2*a.h,c)}function Q(){return G.no?G.no:V("DIA_NO")}function va(b,a){var c=q(b),d=b.w-Config.INPUT_LEFT,f=z(a,b.content?b.content.txt2||"":"",b.content,d),c=z(a,A(b),b.content,d,c),d=new E;d.w=b.w;d.h=f.h+c.h;d.a=f.h;d.tb2=f.tb;d.tb=c.tb;return d}function wa(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)}function xa(b,a){return R(b,a)}function ya(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)}
function S(b,a,c){b=n(c,a);var d=P(a.w,a.h);c.drawShape(b,"poly",a.x,a.y,d,m(a,"loopbegin"));k(a,b,0,0);t(c,b,a,"center")}function I(b,a,c,d,f){b=b.createRCorner(a.x+c,a.y+d,F(),f,5,"free");k(a,b,c,d)}function za(b,a,c,d,f){b=b.createFreeHorizontal(a.x+c,a.y+d,f,"dashed",F(),"free");k(a,b,c,d)}function k(b,a,c,d){a=new Fa(a,c,d);b.primitives.push(a)}function T(b,a,c,d,f,e){d+=f.bottom;var g=0;f=f.tokens;for(var l=f.length;g<l;){var k=f[g],m=c+k.left;"ws"!=k.type&&b.drawText(a,k.text,m,d,e);g++}}function t(b,
a,c,d,f){y(b,a,c,d,c.x,c.y,c.w,c.tb,f)}function y(b,a,c,d,f,e,g,l,k){k&&(f+=Config.LINK_PADDING,g-=Config.LINK_PADDING);k=oa(c);var m=c.content;m&&m.align&&(d=m.align);if("left"===d){if(c=f-g+B(c.content),l)for(e=Math.ceil(e-l.height/2),d=0,l=l.lines,f=l.length;d<f;)T(b,a,c,e,l[d],k),d++}else if("center"===d)for(c=f,e=Math.ceil(e-l.height/2),d=0,l=l.lines,f=l.length;d<f;)g=l[d],m=Math.round(c-g.width/2),T(b,a,m,e,g,k),d++;else{if("right"!==d)throw"Unexpected switch value: "+d;c=f+g-B(c.content);if(l)for(e=
Math.ceil(e-l.height/2),d=0,l=l.lines,f=l.length;d<f;)g=l[d],m=Math.round(c-g.width),T(b,a,m,e,g,k),d++}}function R(b,a){var c=q(b),c=z(a,A(b),b.content,b.w-10,c);c.w=b.w;return c}function Aa(b,a){var c=q(b),d=z(a,b.content?b.content.txt2||"":"",b.content,b.w),c=z(a,A(b),b.content,b.w,c),f=new E;f.w=b.w;f.h=d.h+c.h;f.a=d.h;f.tb2=d.tb;f.tb=c.tb;return f}function Ba(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)}function Ca(b,a,c){var d=m(a,"action"),f=Utils.copyObject(d);b=n(c,a);k(a,b,0,0);c.drawShape(b,
"rectangle",a.x,a.y,[a.w,a.h],d);d=a.y-a.h+a.a;f.fillColor=f.secondaryColor;c.drawShape(b,"rectangle",a.x,d,[a.w,a.a],f);y(c,b,a,"left",a.x,d,a.w,a.tb2);f=q(a);d=D(a);v(c,b,d.x,d.y,d.w,f);y(c,b,a,"left",d.x,d.y,d.w,a.tb,f)}function L(b,a){return Math.round((b/2+a)/Config.SIZE_SNAP)*Config.SIZE_SNAP}function Da(b,a){var c=q(b),d=b.w-Config.INPUT_LEFT,c=z(a,A(b),b.content,d,c);c.w=b.w;return c}function Ea(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)}function da(b,a,c){var d;d=b.free?"free_candies":
"icon_candies";for(var f=0,e=ja(b),g=e.length;f<g;){var l=e[f],m=a.createJCandy(l.x,l.y,c,d);k(b,m,l.x-b.x,l.y-b.y);f++}}function ca(b,a,c,d,f){var e=b.y;b=d.createVCandy(b.x,e,a.y-b.y,f,e+b.h,a.y-a.h,"line_candies");k(c,b,0,0)}function U(){return G.yes?G.yes:V("DIA_YES")}var ka="",N=1,G={},X={},e={action:{},raction:{},collection:{},beginend:{},horizontal:{},junction:{},question:{},vertical:{},select:{},loopbegin:{},loopend:{},address:{},branch:{},pause:{},duration:{},comment:{},insertion:{},ctrlStart:{},
ctrlEnd:{},timer:{},shelf:{},output:{},input:{},end:{},sinput:{},soutput:{},process:{},gdur:{},callout:{},f_rectangle:{},f_line:{},f_insertion:{},f_begin:{},f_shelf:{},f_rounded:{},f_ptr_right:{},f_ptr_left:{},f_label:{},f_more:{},f_circle:{},f_tab:{},f_tab2:{},f_placeholder:{},f_cloud:{},f_db:{},"case":{}};e.action.fit=w;e.action.makeBox=x;e.action.render=W;e.raction.fit=w;e.raction.makeBox=x;e.raction.render=ia;e.collection.fit=w;e.collection.makeBox=x;e.collection.render=function(b,a,c){b=n(c,
{x:a.x,y:a.y,w:a.w+6,h:a.h+6,content:a.content});var d=m(a,"action");c.drawShape(b,"poly",a.x,a.y,Ja(0,0,a.w,a.h),d);var f=a.y-a.h,e=a.y+a.h,g=a.x+a.w;c.drawShape(b,"line",a.x-a.w+.5,e,[g,e],d);c.drawShape(b,"line",g,f,[g,e],d);d=q(a);v(c,b,a.x,a.y,a.w,d);k(a,b,0,0);t(c,b,a,"left",d)};e.loopbegin.fit=O;e.loopbegin.makeBox=function(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)};e.loopbegin.render=function(b,a,c){c.setFont(a.content.font);b=a.w+5;var d;d=a.h;d=c.createTexture(a.x,a.y,-b,-d,2*b,2*
d,"icons");c.drawShape(d,"poly",a.x,a.y,Qa(b,a.h),m(a,null));k(a,d,0,0);b=q(a);v(c,d,a.x,a.y,a.w,b);t(c,d,a,"center",b)};e.loopend.fit=function(b,a){return O(b,a)};e.loopend.makeBox=function(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)};e.loopend.render=function(b,a,c){c.setFont(a.content.font);b=a.w+5;var d;d=a.h;d=c.createTexture(a.x,a.y,-b,-d,2*b,2*d,"icons");c.drawShape(d,"poly",a.x,a.y,Ra(b,a.h),m(a,"loopbegin"));k(a,d,0,0);t(c,d,a,"center")};e.select.fit=R;e.select.makeBox=function(b,a,c,
d){return Utils.boxFromPoint(a,c,b.w,b.h)};e.select.render=function(b,a,c){b=n(c,a);c.drawShape(b,"poly",a.x,a.y,Sa(a.w,a.h),m(a,null));var d=q(a);v(c,b,a.x,a.y,a.w,d);k(a,b,0,0);t(c,b,a,"center",d)};e.pause.fit=xa;e.pause.makeBox=ya;e.pause.render=S;e.duration.fit=function(b,a){a.setFont(b.content.font);var c=Utils.buildBlock(a,A(b)),d;d=B(b.content);d=Math.ceil((c.height+2*d)/2/Config.SIZE_SNAP)*Config.SIZE_SNAP;var f;f=B(b.content);f=Math.ceil((c.width+Config.INPUT_LEFT+2*f)/2/Config.SIZE_SNAP)*
Config.SIZE_SNAP;d<Config.MIN_ICON_HEIGHT&&(d=Config.MIN_ICON_HEIGHT);var e=2*d;f<e&&(f=e);e=new E;e.w=f;e.h=d;e.tb=c;return e};e.duration.makeBox=function(b,a,c,d){b=Utils.boxFromPoint(a,c,b.w,b.h);b.right+=Config.METRE;return b};e.duration.render=S;e.comment.fit=function(b,a){var c=q(b),c=z(a,A(b),b.content,b.w-5,c);c.h+=5;c.w=b.w;return c};e.comment.makeBox=function(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)};e.comment.render=function(b,a,c){b=n(c,a);var d=m(a,null);d.fillColor=d.secondaryColor;
c.drawShape(b,"rectangle",a.x,a.y,[a.w,a.h],d);c.drawShape(b,"rounded",a.x,a.y,[a.w,a.h,10,5],m(a,null));k(a,b,0,0);oa(a);B(a.content);d=q(a);v(c,b,a.x,a.y,a.w,d);t(c,b,a,"left",d)};e["case"].fit=J;e["case"].makeBox=function(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)};e["case"].render=function(b,a,c){var d=m(a,"select");b=n(c,a);c.drawShape(b,"poly",a.x,a.y,ta(a.w,a.h),d);var f=a.y+a.h-2/3*a.h;c.drawShape(b,"line",a.x-a.w,f,[a.x+a.w,f],d);k(a,b,0,0);d=D(a);f=q(a);v(c,b,d.x,d.y,d.w,f);y(c,b,a,
"center",d.x,d.y,d.w,a.tb,f)};e.beginend.fit=function(b,a){return w(b,a)};e.beginend.makeBox=function(b,a,c,d){return e.action.makeBox(b,a,c)};e.beginend.render=Y;e.end.fit=function(b,a){a.setFont(b.content.font);var c=Utils.buildBlock(a,A(b)),d=L(c.height,Config.SNAP),f=L(c.width,Config.SNAP),f=Math.max(f,2*d),e=new E;e.w=f;e.h=d;e.tb=c;return e};e.end.makeBox=function(b,a,c,d){return e.action.makeBox(b,a,c)};e.end.render=function(b,a,c){b=n(c,a);c.drawShape(b,"beginend",a.x,a.y,[a.w-5,a.h-5],m(a,
null));k(a,b,0,0);t(c,b,a,"center")};e.horizontal.fit=function(b,a){};e.horizontal.render=function(b,a,c){var d=b.getHead(a);b=b.getTail(a).x-d.x;c=c.createHorizontal(d.x,d.y,b,a.role,F(),"lines");k(a,c,0,0)};e.junction.fit=function(b,a){return new Utils.Size(0,0)};e.junction.makeBox=function(b,a,c,d){return Utils.boxFromPoint(a,c,0,0)};e.junction.render=function(b,a,c){};e.question.fit=function(b,a){var c=q(b);return O(b,a,c)};e.question.makeBox=function(b,a,c,d){b=e.action.makeBox(b,a,c);b.right+=
2*Config.SNAP;return b};e.question.render=function(b,a,c){b=a.w+5;c.setFont(a.content.font);var d=1.2*c.measureTextWidth(U()),f=c.measureTextWidth(Q()),e=c.getFontHeight();b=c.createTexture(a.x,a.y,-b,-a.h,2*b+Math.floor(1.5*Math.max(d,f)),2*a.h+2*e,"icons");k(a,b,0,0);var g=a.w+5,l=a.h,u=0-g,n=u+20,g=0+g,p=g-20,r=0-l,l=0+l;c.drawShape(b,"poly",a.x,a.y,[u,0,n,r,p,r,g,0,p,l,n,l],m(a,null));u=q(a);v(c,b,a.x,a.y,a.w,u);t(c,b,a,"center",u);a.flag1?(u=d,d=U(),f=Q()):(u=f,d=Q(),f=U());u=-u-Math.floor(e/
4);n=a.h+Math.floor(1.2*e);l=a.w+Math.floor(.6*e);e=-Math.floor(.3*e);g=H();c.drawText(b,d,u+a.x,n+a.y,g);c.drawText(b,f,l+a.x,e+a.y,g)};e.vertical.fit=function(b,a){};e.vertical.render=function(b,a,c){var d=b.getHead(a);b=b.getTail(a).y-d.y;c=c.createVertical(d.x,d.y,b,a.role,F(a),"lines");k(a,c,0,0)};e.address.fit=function(b,a){return J(b,a)};e.address.makeBox=function(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)};e.address.render=function(b,a,c){var d=m(a,null);b=n(c,a);c.drawShape(b,"poly",
a.x,a.y,Ia(a.w,a.h),d);if(a.flag1){var f=a.w,e=a.h,g=0-e,e=(g+(g+2/3*e))/2;c.drawShape(b,"poly",a.x,a.y,[0-f/2,e,0,g,0+f/2,e],{fillColor:d.lineColor})}k(a,b,0,0);d=Math.floor(a.h/3);y(c,b,a,"center",a.x,a.y+d,a.w,a.tb)};e.branch.fit=function(b,a){return J(b,a)};e.branch.makeBox=function(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)};e.branch.render=function(b,a,c){var d=m(a,null);b=n(c,a);c.drawShape(b,"poly",a.x,a.y,ta(a.w,a.h),d);if(a.flag1){var f=a.w,e=a.h,g=0+e,e=(g+(g-2/3*e))/2;c.drawShape(b,
"poly",a.x,a.y,[0-f/2,e,0,g,0+f/2,e],{fillColor:d.lineColor})}k(a,b,0,0);d=D(a);f=q(a);v(c,b,d.x,d.y,d.w,f);y(c,b,a,"center",d.x,d.y,d.w,a.tb,f)};e.insertion.fit=qa;e.insertion.makeBox=ra;e.insertion.render=sa;e.timer.fit=function(b,a){return R(b,a)};e.timer.makeBox=function(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)};e.timer.render=function(b,a,c){b=n(c,a);var d=P(a.w,a.h),f=P(a.w-8,a.h),e=Utils.copyObject(a);e.type="insertion";var g=m(e,null),e=Utils.copyObject(g);e.fillColor=g.secondaryColor;
c.drawShape(b,"poly",a.x,a.y,d,e);c.drawShape(b,"poly",a.x,a.y,f,g);var d=a.x-a.w+8,f=a.x+a.w-8,g=f-20,l=a.y-a.h,u=a.y+a.h;c.drawShape(b,"line",d,l,[d+20,u],e);c.drawShape(b,"line",f,l,[g,u],e);k(a,b,0,0);t(c,b,a,"center")};e.shelf.fit=Aa;e.shelf.makeBox=Ba;e.shelf.render=Ca;e.output.fit=va;e.output.makeBox=wa;e.output.render=function(b,a,c){Z(b,a,c,Ma,!0)};e.input.fit=va;e.input.makeBox=wa;e.input.render=function(b,a,c){var d=m(a,null);b=n(c,a);k(a,b,0,0);c.drawShape(b,"poly",a.x,a.y,Ka(a),d);d=
{lineThickness:d.lineThickness,lineColor:d.lineColor};c.drawShape(b,"poly",a.x,a.y,La(a),d);B(a.content);y(c,b,a,"left",a.x+Config.INPUT_LEFT,a.y-a.h+a.a,a.w-Config.INPUT_LEFT,a.tb2);d=D(a);d.x+=2*Config.INPUT_LEFT;var e=q(a);v(c,b,d.x,d.y,d.w,e);y(c,b,a,"left",d.x,d.y,d.w,a.tb,e)};e.soutput.fit=Da;e.soutput.makeBox=Ea;e.soutput.render=function(b,a,c){b=n(c,a);c.drawShape(b,"poly",a.x,a.y,ua(0,0,a.w,a.h,1.4*Config.INPUT_LEFT),m(a,"action"));var d=q(a);v(c,b,a.x,a.y,a.w,d);k(a,b,0,0);t(c,b,a,"left",
d)};e.sinput.fit=Da;e.sinput.makeBox=Ea;e.sinput.render=function(b,a,c){b=n(c,a);c.drawShape(b,"poly",a.x,a.y,Oa(0,0,a.w,a.h),m(a,"action"));var d=q(a);v(c,b,a.x+Config.INPUT_LEFT,a.y,a.w,d);k(a,b,0,0);y(c,b,a,"left",a.x+Config.INPUT_LEFT,a.y,a.w,a.tb,d)};e.process.fit=function(b,a){var c=q(b),d=b.w-Config.INPUT_LEFT,e=z(a,b.content?b.content.txt2||"":"",b.content,d),c=z(a,A(b),b.content,d,c),d=new E;d.w=b.w;d.h=e.h+c.h;d.a=e.h;d.tb2=e.tb;d.tb=c.tb;return d};e.process.makeBox=function(b,a,c,d){return Utils.boxFromPoint(a,
c,b.w,b.h)};e.process.render=function(b,a,c){Z(b,a,c,Na,!1)};e.f_rectangle.fit=w;e.f_rectangle.makeBox=x;e.f_rectangle.render=W;e.f_tab.fit=w;e.f_tab.makeBox=x;e.f_tab.render=function(b,a,c){b=n(c,a);c.drawShape(b,"tab",a.x,a.y,[a.w,a.h],m(a,null));k(a,b,0,0);t(c,b,a,"center")};e.f_placeholder.fit=w;e.f_placeholder.makeBox=x;e.f_placeholder.render=function(b,a,c){b=n(c,a);var d=m(a,null);c.drawShape(b,"rectangle",a.x,a.y,[a.w,a.h],d);var e=a.x-a.w,h=a.y-a.h,g=a.x+a.w,l=a.y+a.h;c.drawShape(b,"line",
e,h,[g,l],d);c.drawShape(b,"line",e,l,[g,h],d);k(a,b,0,0)};e.f_circle.fit=w;e.f_circle.makeBox=x;e.f_circle.render=function(b,a,c){b=n(c,a);c.drawShape(b,"circle",a.x,a.y,[a.w,a.h],m(a,null));k(a,b,0,0);var d=q(a);v(c,b,a.x,a.y,a.w,d);t(c,b,a,"center",d)};e.f_cloud.fit=function(b,a){var c=w(b,a);c.h=3*c.h/2;return c};e.f_cloud.makeBox=x;e.f_cloud.render=function(b,a,c){b=n(c,a);c.drawShape(b,"cloud",a.x,a.y,[a.w,a.h],m(a,null));k(a,b,0,0);y(c,b,a,"center",a.x,a.y+Math.floor(a.h/3),a.w,a.tb)};e.f_db.fit=
w;e.f_db.makeBox=x;e.f_db.render=function(b,a,c){b=n(c,a);c.drawShape(b,"db",a.x,a.y,[a.w,a.h],m(a,null));k(a,b,0,0);t(c,b,a,"center")};e.f_label.fit=w;e.f_label.makeBox=x;e.f_label.render=function(b,a,c){b=n(c,a);k(a,b,0,0);t(c,b,a,"left")};e.f_rounded.fit=w;e.f_rounded.makeBox=x;e.f_rounded.render=ia;e.f_insertion.fit=qa;e.f_insertion.makeBox=ra;e.f_insertion.render=sa;e.f_begin.fit=w;e.f_begin.makeBox=x;e.f_begin.render=Y;e.f_shelf.fit=Aa;e.f_shelf.makeBox=Ba;e.f_shelf.render=Ca;e.f_line.fit=function(b,
a){var c=A(b),d={w:b.w,h:b.h};if(c){var e=Utils.snapUp(ma(b)/2),e=Math.max(40,e),c=z(a,c,b.content,e);d.tb=c.tb}return d};e.f_line.makeBox=function(b,a,c,d){b=K(b);b.left+=Config.TOUCH_MARGIN;b.top+=Config.TOUCH_MARGIN;b.right-=Config.TOUCH_MARGIN;b.bottom-=Config.TOUCH_MARGIN;return b};e.f_line.render=function(b,a,c){if(b=a.tb){var d=b.width/2,e=b.height/2,h,g,l;h=e+Config.ICON_PADDING;g=ma(a);l=Utils.findAngle(0,0,a.w,a.h);0>a.w?(h=new Utils.Point(g/2,h),g=Utils.rotatePoint(l,h),h=g.x,g=g.y,l=Utils.oppositeAngle(l)):
(h=new Utils.Point(g/2,-h),g=Utils.rotatePoint(l,h),h=g.x,g=g.y);var m=Math.round(h-d),n=Math.round(g-e);c.setFont(a.content.font);e=c.createTexture(a.x,a.y,m,n,2*d,2*e,"free",l);k(a,e,0,0);y(c,e,a,"center",a.x+h,a.y+g,d,b)}c=c.createLine(a.x,a.y,a.w,a.h,Ha(a),"free");k(a,c,0,0)};e.f_line.hit=function(b,a,c){if(0==b.w||0==b.h)return pa(b,a,c);if(pa(b,a,c)){var d=b.x,e=b.y;b=Utils.lineFrom2Points(d,e,d+b.w,e+b.h).distanceToPoint(a,c);b=Math.abs(b)<Config.TOUCH_MARGIN?!0:!1}else b=!1;return b};e.f_line.candies=
function(b){var a=[];r(b.x,b.y,Const.LINE_START,a);r(b.x+b.w,b.y+b.h,Const.LINE_END,a);return a};e.f_line.boxIntersect=function(b,a){var c=K(b);return Utils.boxesIntersect(a,c)};e.f_ptr_right.fit=ga;e.f_ptr_right.makeBox=x;e.f_ptr_right.render=function(b,a,c){b=n(c,a);var d=a.content.h0x;c.drawShape(b,"poly",a.x,a.y,ua(0,0,a.w,a.h,d),m(a,"action"));k(a,b,0,0);y(c,b,a,"left",a.x-d/2,a.y,a.w-d/2,a.tb)};e.f_ptr_right.handles=function(b){var a=[];r(b.x+b.w-b.content.h0x,b.y-b.h,"H_EW",a);return a};e.f_ptr_right.moveHandle=
function(b,a,c,d){a=b.content;c=a.h0x-c;c=Math.max(c,4);c=Math.min(b.w,c);b=Utils.copyObject(a);b.h0x=c;return{content:b}};e.f_ptr_right.resize=ha;e.f_ptr_left.fit=ga;e.f_ptr_left.makeBox=x;e.f_ptr_left.render=function(b,a,c){b=n(c,a);var d=a.content.h0x;c.drawShape(b,"poly",a.x,a.y,Pa(0,0,a.w,a.h,d),m(a,"action"));k(a,b,0,0);y(c,b,a,"left",a.x+d/2,a.y,a.w-d/2,a.tb)};e.f_ptr_left.handles=function(b){var a=[];r(b.x-b.w+b.content.h0x,b.y-b.h,"H_EW",a);return a};e.f_ptr_left.moveHandle=function(b,a,
c,d){a=b.content;c=a.h0x+c;c=Math.max(c,4);c=Math.min(b.w,c);b=Utils.copyObject(a);b.h0x=c;return{content:b}};e.f_ptr_left.resize=ha;e.f_more.fit=function(b,a){var c=na(b.content.subtype);return c.fit?c.fit(b,a):{w:b.w,h:b.h}};e.f_more.render=function(b,a,c){b=a.content.subtype;var d=n(c,a);c.drawShape(d,"more",a.x,a.y,[a.w,a.h,b],m(a,null));k(a,d,0,0)};e.f_more.makeBox=function(b,a,c,d){return Utils.boxFromPoint(a,c,b.w,b.h)};this.getItemCallback=la;this.drawCandies=function(b,a,c,d){for(var e=0,
h=Object.keys(d),g=h.length;e<g;){var l=h[e],k=a.get(l);k||(k=b.getItem(l));ba(b,k,c,d);e++}};this.renderItem=function(b,a,c,d){var e=la(c.type);fa(a,c);c.primitives=[];e.render(b,c,a);ba(b,c,a,d)};this.eraseFromRender=fa;this.moveCanvasNode=function(b,a,c,d,e){c.x=d;c.y=e;a=0;c=c.primitives;for(var h=c.length;a<h;){var g=c[a];b.moveItem(g.id,d+g.xOffset,e+g.yOffset);a++}};this.getHandles=ea;this.moveHandle=function(b,a,c,d,f,h){var g=0,g=e[b.type];if(g.moveHandle)return g.moveHandle(b,a,c,d);g=b.type;
if("gdur"===g){var l=b.content;h=l.h0x;f=l.h0y;var g=l.h1x,k=l.h1y;"FR_0"===a?(h=l.right?h-c:h+c,f-=d,h=Math.max(h,30),g=Math.max(g,30),b=b.h+Config.METRE,f=Math.max(f,b),k=Math.max(k,b),b=Utils.copyObject(l),b.h0x=h,b.h0y=f,b.h1x=g,b.h1y=k):"FR_1"===a?(g=l.right?g-c:g+c,k+=d,h=Math.max(h,30),g=Math.max(g,30),b=b.h+Config.METRE,f=Math.max(f,b),k=Math.max(k,b),b=Utils.copyObject(l),b.h0x=h,b.h0y=f,b.h1x=g,b.h1y=k):b=l;return{content:b}}if("callout"===g)return c=b.content,a=f-b.x,d=h-b.y,b=Utils.boxFromPoint(0,
0,b.w,b.h),Utils.hitBox(b,a,d)?b=c:(b=Utils.copyObject(c),b.h0x=a,b.h0y=d),{content:b};if("f_line"===g){h=b.x;f=b.y;g=h+b.w;b=f+b.h;if("LINE_START"===a)h+=c,f+=d;else{if("LINE_END"!==a)throw"Unexpected switch value: "+a;g+=c;b+=d}b=h==g&&f==b?{}:{x:h,y:f,w:g-h,h:b-f};return b}return"f_rounded"===g?(a=b.content,c=a.radius-c,c=Math.max(c,2),c=Math.min(b.h,c),c=Math.min(b.w,c),b=Utils.copyObject(a),b.radius=c,{content:b}):{content:b.content}};this.setDiaLine=function(b,a){ka=b;if(a)N=a;else{var c=Theme.getThickness();
N=c?c:1}};this.getDiaLine=H;this.getCandies=ja;this.resizeItem=function(b,a,c,d){var f=0,f=e[b.type];f.resize?f.resize(b,c,d,a):(f=b.type,"gdur"===f?(a.h0y=Math.max(a.h0y,d+Config.METRE),a.h1y=Math.max(a.h1y,d+Config.METRE)):"callout"===f?(b=Utils.boxFromPoint(0,0,c+Config.METRE,d+Config.METRE),Utils.hitBox(b,a.h0x,a.h0y)&&(a.h0x=0>a.h0x?Math.min(a.h0x,-c-Config.METRE):Math.max(a.h0x,c+Config.METRE),a.h0y=0>a.h0y?Math.min(a.h0y,-d-Config.METRE):Math.max(a.h0y,d+Config.METRE))):"f_rounded"===f&&(b=
a.radius,b=Math.min(c,b),b=Math.min(d,b),a.radius=b))};this.newMore=function(b){return na(b.subtype).size(b)};this.getLinkHandle=function(b){if(b.content&&b.content.link){var a=D(b),a=new Utils.Point(a.x-a.w+(Config.LINK_PADDING+Config.LINK_PADDING/2)-1,a.y);return{x:a.x,y:a.y,name:"link",link:b.content.link}}return null};this.setUserSettings=function(b){G=Utils.copyObject(b)};e.ctrlStart.fit=w;e.ctrlStart.makeBox=x;e.ctrlStart.render=function(b,a,c){b=n(c,a);c.drawShape(b,"ctrlstart",a.x,a.y,[a.w,
a.h,20],m(a,null));k(a,b,0,0);t(c,b,a,"center")};e.ctrlEnd.fit=w;e.ctrlEnd.makeBox=x;e.ctrlEnd.render=function(b,a,c){b=n(c,a);c.drawShape(b,"ctrlend",a.x,a.y,[a.w,a.h,20],m(a,null));k(a,b,0,0);t(c,b,a,"center")};e.gdur.fit=xa;e.gdur.makeBox=ya;e.gdur.render=function(b,a,c){var d=a.content,e=-d.h0y,h=d.h1y,g,l;d.right?(g=-d.h0x+.5,l=-d.h1x+.5):l=g=5;d.right?(I(c,a,0,e,"right-top"),I(c,a,0,h,"right-bottom")):(I(c,a,0,e,"left-top"),I(c,a,0,h,"left-bottom"));var m=e+5,n=c.createVertical(a.x+0,a.y+m,
d.h0y-5,null,F(),"free");k(a,n,0,m);m=c.createVertical(a.x+0,a.y+0,d.h1y-5,null,F(),"free");k(a,m,0,0);za(c,a,g,e,d.h0x-5);za(c,a,l,h,d.h1x-5);S(b,a,c)};e.callout.fit=w;e.callout.makeBox=x;e.callout.render=function(b,a,c){b=a.content;var d=n(c,a),e=m(a,null);c.drawShape(d,"rounded",a.x,a.y,[a.w,a.h,5,0],e);k(a,d,0,0);var h=q(a);v(c,d,a.x,a.y,a.w,h);t(c,d,a,"left",h);c=c.createCalloutArrow(a.x,a.y,a.w,a.h,b.h0x,b.h0y,e,"free");k(a,c,0,0)};p("f_ui_vscroll",10,80);p("f_ui_hscroll",80,10);p("f_ui_cross",
20,20);p("f_ui_check",20,20);p("f_ui_menu",20,20);p("f_ui_combo",20,20);p("f_ui_left",20,20);p("f_ui_right",20,20);p("f_ui_up",20,20);p("f_ui_down",20,20);p("f_ui_left2",20,20);p("f_ui_right2",20,20);p("f_ui_check_false",20,20);p("f_ui_check_true",20,20);p("f_ui_radio_false",20,20);p("f_ui_radio_true",20,20);p("f_ui_search",20,20);p("f_ui_dots3v",20,20);p("f_ui_dots3h",20,20);p("f_ui_close",50,20);p("f_ui_close_mac",50,20);p("f_ar_pc",90,60);p("f_ar_human",30,70);p("f_ar_server1",30,50);p("f_ar_server2",
60,20);p("f_ar_phone",20,40);p("f_ar_tablet",40,50);p("f_ar_notebook",70,40);p("f_ar_portrait",30,40)};
