function MindModule(){function M(a,b,c,d){this.type=a;this.table=b;this.id=String(c);this.fields=d||{};this.undo=null}function va(a){this.nextId=a;this.edges={};this.nodes={};this.levels={}}function wa(){this.top=this.left=0;this.nodes=[];this.children=[]}function fa(a,b,c){var d,e,f;d=a.graph;e=d.getNode(c);f=e.y-e.h-Config.METRE;d=ga(d,e);null!=d&&d>f&&a.moveDown(c,d-f,b);return e.y}function D(a,b,c,d,e){var f;f=ha(a);a.edges[f]={id:f,isLine:!0,isVertical:b,head:c,tail:d,role:e}}function V(a,b,
c,d){return ia(a,b,{type:"junction",isLine:!1,x:c,y:d,w:0,h:0})}function ia(a,b,c){var d;d=ha(a);c.id=d;a.nodes[d]=c;b.nodes.push(d);return d}function B(a,b,c,d){var e;e={};var f=0;b=Object.keys(b);for(var g=b.length;f<g;){var h=b[f],k=a.graph.getItem(h);h in e?(h=e[h].fields,h.x=k.x,h.y=k.y):(k=new M("update","nodes",h,{x:k.x,y:k.y}),e[h]=k);f++}a=0;e=Utils.objectValues(e);for(f=e.length;a<f;)c.push(e[a]),a++;return{commands:c,nextId:d}}function ja(a,b,c,d){var e,f,g,h;h=a.graph.getNode(b);g={};
g[b]=!0;c<h.h?a.changeSize(b,h.w,c):c>h.h&&(f=c-h.h,e=Drakon.makeDownPushBox(h),a.pushObjects(e,g,2*f,"vertical",d),a.moveDownNoTeam(b,f,d),a.changeSize(b,h.w,c));return h.y}function aa(a,b,c,d,e,f){var g;d=Math.max(d,2*Config.METRE);g=b.graph.getNode(c);e=Drakon.changeOneItem(a,g,d,e);d={};a=e.fields;f.tb=e.tb;f.tb2=e.tb2;if(g.left){if(g=g.id,"h"in a&&ja(b,g,a.h,d),"w"in a){e=a.w;var h,k,l;g=b.graph.getNode(g);k={id:!0};h=e-g.w;if(0!=h)if(0<h&&(l=Drakon.makeRightPushBox(g),b.pushObjects(l,k,2*h,
"horizontal",d)),h=e-g.w,e=g.w,0<h)for(k=Math.floor(h/Config.SNAP),h=0;h<k;)e+=Config.SNAP,b.moveRightNoTeam(g.id,Config.SNAP,d),b.changeSize(g.id,e,g.h),h++;else for(k=-Math.floor(h/Config.SNAP),h=0;h<k;)e-=Config.SNAP,b.changeSize(g.id,e,g.h),b.moveRightNoTeam(g.id,-Config.SNAP,d),h++}}else if(g=g.id,"h"in a&&ja(b,g,a.h,d),"w"in a){e=a.w;var m,n;m=b.graph.getNode(g);k={id:!0};h=e-m.w;0<h&&(l=Drakon.makeLeftPushBox(m),n=Drakon.makeRightPushBox(m),b.pushObjects(l,k,-h,"horizontal",d),b.pushObjects(n,
k,h,"horizontal",d));b.changeSize(g,e,m.h)}Drakon.addToCommands(b,d,c,a,f.commands)}function O(a,b,c,d,e){var f,g,h,k;f=a.graph;k=b.node;g=b.box;f=f.getNodeUpEx(k);b={};b[f.id]=!0;b[k.id]=!0;b[k.up]=!0;d=d?f.y+Config.METRE:f.y;h=new Utils.Box(k.x-1,d,k.x,k.y+k.h);a.pushObjects(h,b,g.right-k.x+Config.METRE+c.right,"horizontal",e);k=new Utils.Box(g.right+Config.METRE,d,g.right+Config.METRE+c.right,d);a.pushObjects(k,b,f.y+Config.METRE+c.bottom-d,"vertical",e)}function ka(a,b,c,d){var e,f,g,h,k;e=a.graph;
f=b.node;h=b.box;e=e.getNodeUpEx(f);b={};b[e.id]=!0;b[f.id]=!0;b[f.up]=!0;k=e.y;g=h.left;h=new Utils.Box(g,k,g,f.y+f.h);f=-Config.METRE-c.right;g+=f;a.pushObjects(h,b,f,"horizontal",d);f=new Utils.Box(g,k,g+c.right,k);a.pushObjects(f,b,e.y+Config.METRE+c.bottom-k,"vertical",d)}function la(a,b){var c;c=new Utils.LogicalTree(b);ba(a,b,c);return c}function ba(a,b,c){var d;d=a.getNode(b);Utils.addLogicalTreeNode(c,d);if(d.down){var e,f;e=[];d=a.getNodeDownEx(d);if("junction"==d.type)for(f=G(a,d);;){f.down&&
(d=a.getNodeDownEx(f),e.push(d));if(!f.right)break;f=a.getNodeRightEx(f)}else e.push(d);d=e;Utils.createLogicalTreeLinks(c,b,!1,d.map(ma));b=0;for(e=d.length;b<e;)f=d[b],ba(a,f.id,c),b++}else if(d.left?"header"==d.role?e=!0:(e=a.getEdge(d.left),e="link"==e.role?!0:!1):e=!1,e){e=[];for(f=a.getNodeLeftEx(d);f=a.getNodeDownEx(f),d=P(a,f),e.push(d),f.down;);d=e;Utils.createLogicalTreeLinks(c,b,!0,d.map(ma));b=0;for(e=d.length;b<e;)f=d[b],ba(a,f.id,c),b++}}function y(a,b,c){var d;d=na();return new PhysicalGraph(a,
b,c,d)}function z(a,b,c){a.graph.removeItem(c);E(b,c)}function R(a,b,c){var d,e,f;f={};e={};d=a.getNodeUpEx(b);f[d.id]=!0;a.enumerateManhattan(b.id,f,e);delete f[d.id];H(f,e,c)}function S(a,b,c){a.graph.removeItem(c);W(b,c)}function xa(a,b){var c;c=Utils.deleteFirst(a,function(a){return a.fields.head==b});Utils.deleteFirst(a,function(a){return a.id==b});return Utils.findFirst(a,function(a){return a.id==c.fields.tail})}function H(a,b,c){var d=0;b=Object.keys(b);for(var e=b.length;d<e;)E(c,b[d]),d++;
d=0;a=Object.keys(a);for(b=a.length;d<b;)W(c,a[d]),d++}function N(a,b){return a.getNodeDownEx(b)}function ga(a,b){var c,d,e,f;if(b.up)return null;c=G(a,b);c=a.getNodeUpEx(c);c=P(a,c);c=c.y+c.h;f=[];for(e=b;;){e=G(a,e);for(e=a.getNodeUpEx(e);e.up;)f.push(e.id),e=a.getNodeUpEx(e);if(!e.left)break}e=0;for(var g=f.length;e<g;)d=a.getNode(f[e]),d=P(a,d),d=ca(a,d),c=Math.max(c,d.bottom),e++;return c}function da(a,b,c){b=b[c];return a.levels[b].left+a.nodes[b].x}function J(a,b){for(var c,d=0,e=a.getHorizontal(b),
f=e.length;;){if(!(d<f))return null;c=a.getItem(e[d]);if(!c.isLine&&c.up)return a.getNodeUpEx(c);d++}}function ma(a){return a.id}function Q(a,b){return Utils.snapUp((a.x+b.x)/2)}function ha(a){var b=a.nextId;a.nextId++;return String(b)}function na(){return{horizontal:ya,vertical:function(){return null}}}function G(a,b){for(var c=b;c.left;)c=a.getNodeLeftEx(c);return c}function P(a,b){for(var c=b;c.right;)c=a.getNodeRightEx(c);return c}function K(a,b){return a.getNodeLeftEx(b)}function oa(a,b,c){b=
"vertical"==b;c=new va(c);a=ea(a,c,a.root,b);return{node:c.nodes[a.nodeId],box:a.box,nextId:c.nextId,nodes:c.nodes,edges:c.edges,levels:c.levels,dockId:a.dockId}}function ea(a,b,c,d){var e,f,g;g=Utils.copyObject(a.nodes[c]);g.x=g.w;g.y=g.h;e=new wa;ia(b,e,g);e.box=pa(g);e.nodeId=g.id;b.levels[g.id]=e;if(f=a.links[c])if(d||"vertical"==f.type){var h,k,l,m;g=e.children;k=e.nodeId;l=b.nodes[k];d=e.box;m=l.x+l.w;var n=0;f=f.children;for(var p=f.length;n<p;)h=f[n],c=ea(a,b,h,!0),g.push(c.nodeId),c=c.box.right+
2*Config.METRE,m=Math.max(m,c),n++;d.right=m;f=l.x-l.w+Config.METRE;h=l.y;a=V(b,e,f,h);D(b,!1,a,k,"link");m=h+l.h+Config.METRE;k=f+Config.METRE;l=a;n=0;for(p=g.length;n<p;)h=g[n],c=b.levels[h],h=b.nodes[h],h=m+h.h,h=V(b,e,f,h),D(b,!1,h,c.dockId,null),D(b,!0,l,h,"arm"),c.left=k,c.top=m,m+=c.box.bottom+Config.METRE,l=h,n++;d.bottom=m-Config.METRE;e.dockId=a}else{var q;h=e.children;d=e.nodeId;g=b.nodes[d];l=e.box;c=1==f.children.length?l.bottom+Config.METRE:l.bottom+2*Config.METRE;m=l.left;k=c;n=0;f=
f.children;for(p=f.length;n<p;)q=ea(a,b,f[n],!1),h.push(q.nodeId),q.left=m,q.top=c,m+=q.box.right+Config.METRE,q=c+q.box.bottom,k=Math.max(k,q),n++;l.right=m-Config.METRE;l.bottom=k;if(1==h.length)a=b.nodes[h[0]],g.x=a.x,D(b,!0,d,a.id,null);else if(a=[],0==h.length%2){f=h.length/2-1;k=f+1;l=da(b,h,f);m=da(b,h,k);g.x=Utils.snapUp((l+m)/2);qa(b,e,h,a);for(h=1;h<a.length;)h!=k&&(l=a[h-1],m=a[h],D(b,!1,l,m,"bridge")),h++;g=g.x;c-=Config.METRE;g=V(b,e,g,c);D(b,!1,a[f],g,"bridge");D(b,!1,g,a[k],"bridge");
D(b,!0,d,g,null)}else{c=(h.length+1)/2-1;g.x=da(b,h,c);qa(b,e,h,a);for(h=1;h<a.length;)l=a[h-1],m=a[h],D(b,!1,l,m,"bridge"),h++;D(b,!0,d,a[c],null)}a=e;d=b.nodes[a.nodeId];d=d.x-d.w-a.box.left;if(0>d){c=0;h=a.nodes;for(f=h.length;c<f;)g=h[c],g=b.nodes[g],g.x-=d,c++;c=0;h=a.children;for(f=h.length;c<f;)g=h[c],a=b.levels[g],a.left-=d,c++}}else e.dockId=g.id;return e}function pa(a){return new Utils.Box(a.x-a.w,a.y-a.h,a.x+a.w,a.y+a.h)}function A(a,b,c){return{id:String(a),isLine:!1,x:b,y:c,w:0,h:0,type:"junction"}}
function ra(a,b,c,d,e){return{id:String(a),isLine:!0,isVertical:b,head:c,tail:d,role:e,type:b?"vertical":"horizontal"}}function qa(a,b,c,d){for(var e,f,g=0,h=c.length;g<h;){var k=c[g];e=a.levels[k];f=a.nodes[k];f=e.left+f.x;e=e.top-Config.METRE;e=V(a,b,f,e);D(a,!0,e,k,void 0);d.push(e);g++}}function T(a,b){return{box:ca(a,b),node:b}}function ca(a,b){var c,d,e,f,g;d=pa(b);g={};e={};g[b.id]=!0;f=null;if(b.down)for(c=a.getNodeDownEx(b),a.enumerateManhattan(c.id,g,e),f&&delete g[f.id],e=0,g=Object.keys(g),
f=g.length;e<f;)c=g[e],c=a.getNode(c),d.left=Math.min(d.left,c.x-c.w),d.top=Math.min(d.top,c.y-c.h),d.right=Math.max(d.right,c.x+c.w),d.bottom=Math.max(d.bottom,c.y+c.h),e++;else if(b.left&&(c=a.getEdge(b.left),"link"==c.role))for(c=a.getNodeLeftEx(b),c.left&&(f=a.getNodeLeftEx(c),g[f.id]=!0),a.enumerateManhattan(c.id,g,e),f&&delete g[f.id],e=0,g=Object.keys(g),f=g.length;e<f;)c=g[e],c=a.getNode(c),d.left=Math.min(d.left,c.x-c.w),d.top=Math.min(d.top,c.y-c.h),d.right=Math.max(d.right,c.x+c.w),d.bottom=
Math.max(d.bottom,c.y+c.h),e++;return d}function F(a,b,c,d){c-=b.x;0!=c&&a.moveRight(b.id,c,d)}function U(a,b,c){a=a.getNodeUpEx(b.node);I(c,b.box.right+Config.METRE,a.y+Config.METRE)}function I(a,b,c){sa(a,a.node.id,b,c)}function sa(a,b,c,d){var e;e=a.levels[b];c=e.left+c;d=e.top+d;b=a.box;b.left+=c;b.top+=d;b.right+=c;b.bottom+=d;for(var f=0,g=e.nodes,h=g.length;f<h;)b=g[f],b=a.nodes[b],b.x+=c,b.y+=d,f++;b=0;e=e.children;for(f=e.length;b<f;)sa(a,e[b],c,d),b++}function E(a,b){var c=new M("delete",
"edges",b,null);a.push(c)}function W(a,b){var c=new M("delete","nodes",b,null);a.push(c)}function t(a,b,c,d,e){b=new M("insert","edges",b,{type:"horizontal",isVertical:!1,isLine:!0,head:c,tail:d,role:e});a.push(b)}function w(a,b){var c;c={type:b.type,isLine:!1,x:b.x,y:b.y,w:b.w,h:b.h,a:b.a,content:b.content,flag1:b.flag1,role:b.role};b.tb&&(c.tb=b.tb);b.tb2&&(c.tb2=b.tb2);c=new M("insert","nodes",b.id,c);a.push(c)}function u(a,b,c,d,e){b=new M("insert","edges",b,{type:"vertical",isVertical:!0,isLine:!0,
head:c,tail:d,role:e});a.push(b)}function C(a,b){for(var c=0,d=b.nodes,e=Object.keys(d),f=e.length;c<f;){var g=e[c];w(a,d[g]);c++}c=0;d=b.edges;e=Object.keys(d);for(f=e.length;c<f;){var g=e[c],g=d[g],h=a,k=void 0,k=k=void 0,k=g.isVertical?"vertical":"horizontal",k={type:k,isVertical:g.isVertical,isLine:!0,head:g.head,tail:g.tail,role:g.role},k=new M("insert","edges",g.id,k);h.push(k);c++}}function ta(a,b,c,d){var e,f;e=new Utils.Box(c.x,c.y,c.x,c.y);d-=c.y;f={};f[c.id]=!0;a.pushObjects(e,f,d,"vertical",
b)}function X(a,b,c,d,e){var f,g,h,k,l;g=a.graph;h=g.getNode(c);f=g.getNodeDownEx(h);E(d,h.down);a.graph.removeItem(h.down);a.rebuildCache();k=g.getNodeLeftEx(f);f.down?(g=Q(k,f),F(a,h,g,b),E(d,f.left),a=A(e,h.x,f.y),e++,w(d,a),t(d,e,a.id,f.id,"bridge"),e++,t(d,e,k.id,a.id,"bridge"),e++,u(d,e,c,a.id,null)):(l=g.getNodeRightEx(f),g=k.x-h.x,a.moveRight(h.id,g,b),E(d,f.left),E(d,f.right),W(d,f.id),t(d,e,k.id,l.id,"bridge"),e++,u(d,e,c,k.id,null));e++;return e}function Y(a,b,c,d,e){var f,g,h,k,l;g=a.graph;
h=g.getNode(c);f=g.getNodeDownEx(h);E(d,h.down);a.graph.removeItem(h.down);a.rebuildCache();l=g.getNodeRightEx(f);f.down?(g=Q(l,f),F(a,h,g,b),E(d,f.right),a=A(e,h.x,f.y),e++,w(d,a),t(d,e,f.id,a.id,"bridge"),e++,t(d,e,a.id,l.id,"bridge"),e++,u(d,e,c,a.id,null)):(k=g.getNodeLeftEx(f),g=l.x-h.x,a.moveRight(h.id,g,b),E(d,f.left),E(d,f.right),W(d,f.id),t(d,e,k.id,l.id,"bridge"),e++,u(d,e,c,l.id,null));e++;return e}function za(a,b){delete Utils.findFirst(a,function(a){return a.fields.tail==b&&"insert"==
a.type}).fields.role}function L(a,b){return a.getNodeRightEx(b)}function ya(a,b){var c;if(b.right){c=a.getEdge(b.right);if("link"==c.role)return a.getNodeRight(b);if(b.up)return c=a.getEdge(b.up),"arm"==c.role?a.getNodeRight(b):null}return null}function Z(a,b,c,d,e,f){f-=c;c=new Utils.Box(c,d,c,e);a.pushObjects(c,{},f,"horizontal",b)}function v(a,b){CallTrace.add(a,[b])}function x(a,b){return a.getNodeUpEx(b)}function ua(){this._below=null;this.below=function(){var a=this._below;return null!=a?a:
this._below=a=N(this.graph(),this.item())};this._graph=null;this.graph=function(a){if("undefined"!=typeof a)this._graph=a,this._toggleTree=this._rightCorner=this._oldSubtree=this._miv04=this._miv03=this._miv02=this._miv01=this._mih064=this._mih063=this._mih062=this._mih061=this._mih06=this._mih05=this._mih04=this._mih03=this._mih02=this._mih01=this._mdv03=this._mdv02=this._mdv01=this._mdh064=this._mdh063=this._mdh062=this._mdh061=this._mdh06=this._mdh05=this._mdh04=this._mdh03=this._mdh02=this._mdh01=
this._leftCorner=this._item=this._below=null;else return this._graph};this._item=null;this.item=function(){var a=this._item;return null!=a?a:this._item=a=this.graph().getItem(this.itemId())};this._itemId=null;this.itemId=function(a){if("undefined"!=typeof a)this._itemId=a,this._rightCorner=this._oldSubtree=this._miv04=this._miv03=this._miv02=this._miv01=this._mih064=this._mih063=this._mih062=this._mih061=this._mih06=this._mih05=this._mih04=this._mih03=this._mih02=this._mih01=this._mdv03=this._mdv02=
this._mdv01=this._mdh064=this._mdh063=this._mdh062=this._mdh061=this._mdh06=this._mdh05=this._mdh04=this._mdh03=this._mdh02=this._mdh01=this._leftCorner=this._item=this._below=null;else return this._itemId};this._items=null;this.items=function(a){if("undefined"!=typeof a)this._items=a,this._toggleTree=this._miv03=this._miv02=this._miv01=this._mih064=this._mih063=this._mih062=this._mih061=this._mih06=this._mih05=this._mih04=this._mih03=this._mih02=this._mih01=this._mdh064=this._mdh063=this._mdh062=
this._mdh06=this._mdh05=this._mdh04=this._mdh03=this._mdh02=null;else return this._items};this._leftCorner=null;this.leftCorner=function(){var a=this._leftCorner;return null!=a?a:this._leftCorner=a=G(this.graph(),this.below())};this._mdh01=null;this.mdh01=function(){var a=this._mdh01;if(null!=a)return a;var b;v("mdh01",this.itemId());a=[];R(this.graph(),this.item(),a);b=this.nextId();return this._mdh01=a={commands:a,nextId:b}};this._mdh02=null;this.mdh02=function(){var a=this._mdh02;if(null!=a)return a;
var b,c,d,e,f,g,h,k;v("mdh02",this.itemId());a=[];e={};f={};c={};b=x(this.graph(),this.item());f[b.id]=!0;this.graph().enumerateManhattan(this.item().id,f,c);d=this.nextId();g=J(this.graph(),b.id);k=K(this.graph(),b);b=K(this.graph(),k);h=N(this.graph(),b);f[k.id]=!0;f[b.id]=!0;c[k.up]=!0;c[k.left]=!0;c[k.right]=!0;c[b.down]=!0;H(f,c,a);f=y(this.items(),this.graph(),this.render());c=f.graph;c.removeItem(k.up);f.rebuildCache();g=c.getNode(g.id);F(f,g,b.x,e);u(a,d,g.id,h.id,null);d++;return this._mdh02=
a=B(f,e,a,d)};this._mdh03=null;this.mdh03=function(){var a=this._mdh03;if(null!=a)return a;var b,c,d,e;v("mdh03",this.itemId());b=[];d={};e={};c={};a=x(this.graph(),this.item());c[a.left]=!0;c[a.down]=!0;e[a.id]=!0;this.graph().enumerateManhattan(this.item().id,e,c);H(e,c,b);e=y(this.items(),this.graph(),this.render());c=this.nextId();c=X(e,d,J(this.graph(),a.id).id,b,c);return this._mdh03=a=B(e,d,b,c)};this._mdh04=null;this.mdh04=function(){var a=this._mdh04;if(null!=a)return a;var b,c,d,e,f,g,h,
k;v("mdh02",this.itemId());a=[];e={};f={};c={};b=x(this.graph(),this.item());f[b.id]=!0;this.graph().enumerateManhattan(this.item().id,f,c);d=this.nextId();g=J(this.graph(),b.id);k=L(this.graph(),b);b=L(this.graph(),k);h=N(this.graph(),b);f[k.id]=!0;f[b.id]=!0;c[k.up]=!0;c[k.left]=!0;c[k.right]=!0;c[b.down]=!0;H(f,c,a);f=y(this.items(),this.graph(),this.render());c=f.graph;c.removeItem(k.up);f.rebuildCache();g=c.getNode(g.id);F(f,g,b.x,e);u(a,d,g.id,h.id,null);d++;return this._mdh04=a=B(f,e,a,d)};
this._mdh05=null;this.mdh05=function(){var a=this._mdh05;if(null!=a)return a;var b,c,d,e;v("mdh05",this.itemId());b=[];d={};e={};c={};a=x(this.graph(),this.item());c[a.right]=!0;c[a.down]=!0;e[a.id]=!0;this.graph().enumerateManhattan(this.item().id,e,c);H(e,c,b);e=y(this.items(),this.graph(),this.render());c=this.nextId();c=Y(e,d,J(this.graph(),a.id).id,b,c);return this._mdh05=a=B(e,d,b,c)};this._mdh06=null;this.mdh06=function(){var a=this._mdh06;if(null!=a)return a;var b,c;v("mdh06",this.itemId());
a=x(this.graph(),this.item());c=L(this.graph(),a);b=K(this.graph(),a);return this._mdh06=a=a.up?this.mdh061():c.up?c.down?this.mdh064():this.mdh062():b.up&&!b.down?this.mdh063():this.mdh064()};this._mdh061=null;this.mdh061=function(){var a=this._mdh061;if(null!=a)return a;var b;v("mdh061",this.itemId());a=[];R(this.graph(),this.item(),a);b=this.nextId();return this._mdh061=a={commands:a,nextId:b}};this._mdh062=null;this.mdh062=function(){var a=this._mdh062;if(null!=a)return a;var b,c,d,e,f,g,h,k,
l;v("mdh062",this.itemId());b=[];f={};d=this.nextId();h=y(this.items(),this.graph(),this.render());c=h.graph;a=x(this.graph(),this.item());e=K(this.graph(),a);k=L(this.graph(),a);l=L(this.graph(),k);g=x(this.graph(),k);R(this.graph(),this.item(),b);c.removeItem(a.down);z(h,b,a.left);z(h,b,a.right);z(h,b,k.right);z(h,b,k.up);S(h,b,k.id);S(h,b,a.id);h.rebuildCache();F(h,g,l.x,f);t(b,d,e.id,l.id,"bridge");d++;u(b,d,g.id,l.id,null);d++;return this._mdh062=a=B(h,f,b,d)};this._mdh063=null;this.mdh063=function(){var a=
this._mdh063;if(null!=a)return a;var b,c,d,e,f,g,h,k,l;v("mdh063",this.itemId());b=[];g={};d=this.nextId();k=y(this.items(),this.graph(),this.render());c=k.graph;a=x(this.graph(),this.item());l=L(this.graph(),a);e=K(this.graph(),a);f=K(this.graph(),e);h=x(this.graph(),e);R(this.graph(),this.item(),b);c.removeItem(a.down);z(k,b,a.left);z(k,b,a.right);z(k,b,e.left);z(k,b,e.up);S(k,b,e.id);S(k,b,a.id);k.rebuildCache();F(k,h,f.x,g);t(b,d,f.id,l.id,"bridge");d++;u(b,d,h.id,f.id,null);d++;return this._mdh063=
a=B(k,g,b,d)};this._mdh064=null;this.mdh064=function(){var a=this._mdh064;if(null!=a)return a;var b,c,d,e,f,g,h,k;v("mdh064",this.itemId());b=[];f={};d=this.nextId();h=y(this.items(),this.graph(),this.render());c=h.graph;a=x(c,this.item());e=c.getNodeLeftEx(a);k=c.getNodeRightEx(a);g=J(c,a.id);R(this.graph(),this.item(),b);c.removeItem(a.down);z(h,b,a.left);z(h,b,a.right);S(h,b,a.id);h.rebuildCache();d=g.x>a.x?Y(h,f,g.id,b,d):X(h,f,g.id,b,d);t(b,d,e.id,k.id,"bridge");d++;return this._mdh064=a=B(h,
f,b,d)};this._mdv01=null;this.mdv01=function(){var a=this._mdv01;if(null!=a)return a;var b,c,d,e,f,g;v("mdv01",this.itemId());a=[];e={};b={};d=G(this.graph(),this.item());g=x(this.graph(),d);f=L(this.graph(),g);c=this.nextId();e[d.id]=!0;e[g.id]=!0;b[g.down]=!0;b[g.right]=!0;this.graph().enumerateManhattan(this.item().id,e,b);g.left?(d=K(this.graph(),g),b[g.left]=!0,H(e,b,a),t(a,c,d.id,f.id,null),c++):H(e,b,a);return this._mdv01=a={commands:a,nextId:c}};this._mdv02=null;this.mdv02=function(){var a=
this._mdv02;if(null!=a)return a;var b,c,d,e;v("mdv02",this.itemId());a=[];e={};b={};d=G(this.graph(),this.item());x(this.graph(),d);c=this.nextId();e[d.id]=!0;b[d.up]=!0;b[d.right]=!0;this.graph().enumerateManhattan(this.item().id,e,b);H(e,b,a);return this._mdv02=a={commands:a,nextId:c}};this._mdv03=null;this.mdv03=function(){var a=this._mdv03;if(null!=a)return a;var b,c,d,e,f,g;v("mdv03",this.itemId());a=[];f={};b={};e=G(this.graph(),this.item());g=x(this.graph(),e);d=N(this.graph(),e);c=this.nextId();
f[e.id]=!0;b[e.up]=!0;b[e.right]=!0;b[e.down]=!0;this.graph().enumerateManhattan(this.item().id,f,b);H(f,b,a);u(a,c,g.id,d.id,"arm");c++;return this._mdv03=a={commands:a,nextId:c}};this._mih01=null;this.mih01=function(){var a=this._mih01;if(null!=a)return a;var b,c,d,e,f,g,h,k,l;v("mih01",this.itemId());a=[];f={};k=y(this.items(),this.graph(),this.render());h=this.newHorTree();d=h.nextId;g=h.node;c=h.box;e=this.item().y+this.item().h+Config.METRE;b=e+c.bottom;ta(k,f,this.item(),b);l=this.item().x+
c.right-g.x;c=this.item().x-g.x;Z(k,f,this.item().x,e,b,l);Z(k,f,this.item().x,e,b,c);b=this.item().x-g.x;I(h,b,e);C(a,h);u(a,d,this.item().id,g.id,null);d++;return this._mih01=a=B(k,f,a,d)};this._mih02=null;this.mih02=function(){var a=this._mih02;if(null!=a)return a;var b,c,d,e,f,g,h,k,l,m,n,p,q,r;v("mih02",this.itemId());a=[];k={};q=y(this.items(),this.graph(),this.render());g=q.graph;p=g.getNode(this.itemId());r=g.getNodeDownEx(p);n=T(g,r);c=r.y-r.h-(p.y+p.h)-2*Config.METRE;0>c&&q.moveDown(r.id,
-c,k);b=r.y-r.h-Config.METRE;f=b+Config.METRE;e=n.box.right+Config.METRE;z(q,a,r.up);m=this.newHorTree();c=m.nextId;l=m.node;h=A(c,r.x,b);c++;q.graph.addItem(h);d=ra(c,!0,h.id,r.id,null);c++;q.graph.addItem(d);q=y(this.items(),g,this.render());O(q,n,m.box,!1,k);I(m,e,f);g=Q(r,l);F(q,p,g,k);p=q.graph.getNode(p.id);g=A(c,p.x,b);c++;b=A(c,l.x,b);c++;C(a,m);w(a,h);w(a,g);w(a,b);u(a,c,h.id,r.id,null);c++;u(a,c,b.id,l.id,null);c++;u(a,c,p.id,g.id,null);c++;t(a,c,h.id,g.id,"bridge");c++;t(a,c,g.id,b.id,
"bridge");c++;return this._mih02=a=B(q,k,a,c)};this._mih03=null;this.mih03=function(){var a=this._mih03;if(null!=a)return a;var b,c,d,e,f,g;v("mih03",this.itemId());a=[];c={};g=y(this.items(),this.graph(),this.render());b=N(this.graph(),this.rightCorner());e=T(this.graph(),b);f=this.newHorTree();b=f.nextId;d=f.node;O(g,e,f.box,!1,c);U(this.graph(),e,f);e=A(b,d.x,this.rightCorner().y);b++;C(a,f);w(a,e);t(a,b,this.rightCorner().id,e.id,"bridge");b++;u(a,b,e.id,d.id,null);b++;b=Y(g,c,this.item().id,
a,b);return this._mih03=a=B(g,c,a,b)};this._mih04=null;this.mih04=function(){var a=this._mih04;if(null!=a)return a;var b,c,d,e,f,g,h,k,l,m,n,p,q,r;v("mih04",this.itemId());a=[];h={};p=y(this.items(),this.graph(),this.render());g=p.graph;n=g.getNode(this.itemId());r=g.getNodeDownEx(n);m=T(g,r);c=r.y-r.h-(n.y+n.h)-2*Config.METRE;0>c&&p.moveDown(r.id,-c,h);b=r.y-r.h-Config.METRE;z(p,a,r.up);l=this.newHorTree();c=l.nextId;k=l.node;f=b+Config.METRE;e=m.box.left-Config.METRE-l.box.right;q=A(c,r.x,b);c++;
p.graph.addItem(q);d=ra(c,!0,q.id,r.id,null);c++;p.graph.addItem(d);p=y(this.items(),g,this.render());ka(p,m,l.box,h);I(l,e,f);g=Q(r,k);F(p,n,g,h);n=p.graph.getNode(n.id);g=A(c,n.x,b);c++;b=A(c,k.x,b);c++;C(a,l);w(a,b);w(a,g);w(a,q);u(a,c,q.id,r.id,null);c++;u(a,c,b.id,k.id,null);c++;u(a,c,n.id,g.id,null);c++;t(a,c,b.id,g.id,"bridge");c++;t(a,c,g.id,q.id,"bridge");c++;return this._mih04=a=B(p,h,a,c)};this._mih05=null;this.mih05=function(){var a=this._mih05;if(null!=a)return a;var b,c,d,e,f,g;v("mih05",
this.itemId());a=[];c={};g=y(this.items(),this.graph(),this.render());b=N(this.graph(),this.leftCorner());e=T(this.graph(),b);f=this.newHorTree();b=f.nextId;d=f.node;ka(g,e,f.box,c);var h;h=this.graph().getNodeUpEx(e.node);I(f,e.box.left-Config.METRE-f.box.right,h.y+Config.METRE);e=A(b,d.x,this.leftCorner().y);b++;C(a,f);w(a,e);t(a,b,e.id,this.leftCorner().id,"bridge");b++;u(a,b,e.id,d.id,null);b++;b=X(g,c,this.item().id,a,b);return this._mih05=a=B(g,c,a,b)};this._mih06=null;this.mih06=function(){var a=
this._mih06;if(null!=a)return a;var b;v("mih06",this.itemId());a=x(this.graph(),this.item());b=L(this.graph(),a);return this._mih06=a=a.up?this.mih063():b.up?b.down?this.mih062():this.mih061():this.mih064()};this._mih061=null;this.mih061=function(){var a=this._mih061;if(null!=a)return a;var b,c,d,e,f,g;v("mih061",this.itemId());a=[];d={};g=y(this.items(),this.graph(),this.render());f=this.newHorTree();c=f.nextId;e=f.node;O(g,this.oldSubtree(),f.box,!0,d);U(this.graph(),this.oldSubtree(),f);b=x(this.graph(),
this.item());b=J(this.graph(),b.id);b=N(this.graph(),b);F(g,b,e.x,d);C(a,f);u(a,c,b.id,e.id,null);c++;return this._mih061=a=B(g,d,a,c)};this._mih062=null;this.mih062=function(){var a=this._mih062;if(null!=a)return a;var b,c,d,e,f,g,h,k,l,m;v("mih062",this.itemId());b=[];f={};l=y(this.items(),this.graph(),this.render());h=this.newHorTree();d=h.nextId;c=l.graph;g=h.node;a=x(c,this.item());m=c.getNodeRightEx(a);k=c.getNodeUpEx(m);O(l,this.oldSubtree(),h.box,!0,f);U(c,this.oldSubtree(),h);z(l,b,m.up);
z(l,b,a.right);l.rebuildCache();c=Q(g,k);F(l,k,c,f);c=A(d,g.x,a.y);d++;e=A(d,k.x,a.y);d++;C(b,h);w(b,c);w(b,e);d++;u(b,d,k.id,e.id,null);d++;u(b,d,c.id,g.id,null);d++;t(b,d,a.id,c.id,"bridge");d++;t(b,d,c.id,e.id,"bridge");d++;t(b,d,e.id,m.id,"bridge");d++;return this._mih062=a=B(l,f,b,d)};this._mih063=null;this.mih063=function(){var a=this._mih063;if(null!=a)return a;var b,c,d,e,f,g,h,k,l,m;v("mih063",this.itemId());b=[];f={};l=y(this.items(),this.graph(),this.render());h=this.newHorTree();d=h.nextId;
c=l.graph;g=h.node;a=x(c,this.item());m=c.getNodeRightEx(a);k=c.getNodeUpEx(a);O(l,this.oldSubtree(),h.box,!0,f);U(c,this.oldSubtree(),h);z(l,b,a.up);z(l,b,a.right);l.rebuildCache();c=Q(g,k);F(l,k,c,f);c=A(d,k.x,a.y);d++;e=A(d,g.x,a.y);d++;C(b,h);w(b,c);w(b,e);u(b,d,k.id,c.id,null);d++;u(b,d,e.id,g.id,null);d++;t(b,d,a.id,c.id,"bridge");d++;t(b,d,c.id,e.id,"bridge");d++;t(b,d,e.id,m.id,"bridge");d++;return this._mih063=a=B(l,f,b,d)};this._mih064=null;this.mih064=function(){var a=this._mih064;if(null!=
a)return a;var b,c,d,e,f,g,h,k;v("mih064",this.itemId());b=[];e={};h=y(this.items(),this.graph(),this.render());g=this.newHorTree();d=g.nextId;c=h.graph;f=g.node;a=x(c,this.item());k=c.getNodeRightEx(a);O(h,this.oldSubtree(),g.box,!0,e);U(c,this.oldSubtree(),g);c=J(c,a.id);z(h,b,a.right);h.rebuildCache();d=c.x>a.x?X(h,e,c.id,b,d):Y(h,e,c.id,b,d);c=A(d,f.x,a.y);d++;C(b,g);w(b,c);u(b,d,c.id,f.id,null);d++;t(b,d,a.id,c.id,"bridge");d++;t(b,d,c.id,k.id,"bridge");d++;return this._mih064=a=B(h,e,b,d)};
this._miv01=null;this.miv01=function(){var a=this._miv01;if(null!=a)return a;var b,c,d,e,f,g,h,k,l,m,n,p,q;v("miv01",this.itemId());a=[];l={};p=y(this.items(),this.graph(),this.render());n=this.newVerTree();f=n.nextId;m=n.node;e=n.box;g=fa(p,l,this.itemId());q=g+this.item().h;b=this.item().x-this.item().w+Config.METRE;h=b+Config.METRE;k=q+Config.METRE;d=k+e.bottom;e=h+e.right;c=new Utils.Point(b,q);var r=this.itemId(),z,x;z=new Utils.Box(c.x,c.y,c.x,c.y);c=e-c.x;x={};x[r]=!0;p.pushObjects(z,x,c,"horizontal",
l);d-=q;q=new Utils.Box(b,q,e,q);p.pushObjects(q,{},d,"vertical",l);I(n,h,k);C(a,n);h=A(f,b,m.y);f++;w(a,h);t(a,f,h.id,n.dockId,null);f++;g=A(f,b,g);f++;this.item().left?(b=K(this.graph(),this.item()),E(a,this.item().left),w(a,g),t(a,f,b.id,g.id,null),f++):w(a,g);t(a,f,g.id,this.item().id,"link");f++;u(a,f,g.id,h.id,"arm");f++;return this._miv01=a=B(p,l,a,f)};this._miv02=null;this.miv02=function(){var a=this._miv02;if(null!=a)return a;var b,c,d,e,f,g,h,k,l,m,n;v("miv02",this.itemId());a=[];l={};n=
y(this.items(),this.graph(),this.render());e=n.graph;g=e.getNode(this.itemId());m=this.newVerTree();f=m.nextId;h=m.node;d=m.box;fa(n,l,this.itemId());b=ca(e,g);e=G(e,g);c=b.bottom;b=e.x;g=b+Config.METRE;k=c+Config.METRE;c=k+d.bottom;d=g+d.right;ta(n,l,e,c);Z(n,l,b,k,c,d);I(m,g,k);C(a,m);h=A(f,b,h.y);f++;w(a,h);t(a,f,h.id,m.dockId,null);f++;u(a,f,e.id,h.id,"arm");f++;return this._miv02=a=B(n,l,a,f)};this._miv03=null;this.miv03=function(){var a=this._miv03;if(null!=a)return a;var b,c,d,e,f,g,h,k,l,
m,n,p,q,r;v("miv03",this.itemId());a=[];l={};p=y(this.items(),this.graph(),this.render());b=p.graph;n=this.newVerTree();e=n.nextId;m=n.node;d=n.box;f=b.getNode(this.itemId());h=G(b,f);r=b.getNodeUpEx(h);P(b,r);b.getEdge(r.right);k=ga(b,f)+Config.METRE;b=h.x;g=b+Config.METRE;c=k+d.bottom;q=g+d.right;d=f.y-f.h-Config.METRE-c;0>d&&p.moveDown(f.id,-d,l);Z(p,l,b,k,c,q);p.rebuildCache();z(p,a,h.up);I(n,g,k);C(a,n);f=A(e,b,m.y);e++;w(a,f);t(a,e,f.id,n.dockId,null);e++;u(a,e,r.id,f.id,"arm");e++;u(a,e,f.id,
h.id,"arm");e++;return this._miv03=a=B(p,l,a,e)};this._miv04=null;this.miv04=function(){var a=this._miv04;if(null!=a)return a;var b,c,d,e,f;v("miv04",this.itemId());a=[];e=this.newVerTree();c=e.nextId;d=e.node;f=this.item().y+this.item().h;b=this.item().x-this.item().w-Config.METRE;I(e,b+Config.METRE,f+Config.METRE);C(a,e);f=A(c,b,this.item().y);c++;b=A(c,b,d.y);c++;w(a,f);w(a,b);t(a,c,b.id,e.dockId,null);c++;t(a,c,f.id,this.itemId(),null);c++;u(a,c,f.id,b.id,"arm");c++;return this._miv04=a={commands:a,
nextId:c}};this._newHorTree=null;this.newHorTree=function(){var a=this._newHorTree;return null!=a?a:this._newHorTree=a=oa(this.toInsert(),"horizontal",this.nextId())};this._newVerTree=null;this.newVerTree=function(){var a=this._newVerTree;return null!=a?a:this._newVerTree=a=oa(this.toInsert(),"vertical",this.nextId())};this._nextId=null;this.nextId=function(a){if("undefined"!=typeof a)this._nextId=a,this._toggleTree=this._newVerTree=this._newHorTree=this._miv04=this._miv03=this._miv02=this._miv01=
this._mih064=this._mih063=this._mih062=this._mih061=this._mih06=this._mih05=this._mih04=this._mih03=this._mih02=this._mih01=this._mdv03=this._mdv02=this._mdv01=this._mdh064=this._mdh063=this._mdh062=this._mdh061=this._mdh06=this._mdh05=this._mdh04=this._mdh03=this._mdh02=this._mdh01=null;else return this._nextId};this._oldSubtree=null;this.oldSubtree=function(){var a=this._oldSubtree;return null!=a?a:this._oldSubtree=a=T(this.graph(),this.item())};this._render=null;this.render=function(a){if("undefined"!=
typeof a)this._render=a,this._toggleTree=this._miv03=this._miv02=this._miv01=this._mih064=this._mih063=this._mih062=this._mih061=this._mih06=this._mih05=this._mih04=this._mih03=this._mih02=this._mih01=this._mdh064=this._mdh063=this._mdh062=this._mdh06=this._mdh05=this._mdh04=this._mdh03=this._mdh02=null;else return this._render};this._rightCorner=null;this.rightCorner=function(){var a=this._rightCorner;return null!=a?a:this._rightCorner=a=P(this.graph(),this.below())};this._toInsert=null;this.toInsert=
function(a){if("undefined"!=typeof a)this._toInsert=a,this._newVerTree=this._newHorTree=this._miv04=this._miv03=this._miv02=this._miv01=this._mih064=this._mih063=this._mih062=this._mih061=this._mih06=this._mih05=this._mih04=this._mih03=this._mih02=this._mih01=null;else return this._toInsert};this._toggleTree=null;this.toggleTree=function(){var a=this._toggleTree;if(null!=a)return a;var b,c,d,e,f;v("toggleTree","");b:{a=0;d=this.graph().nodes;b=Object.keys(d);for(f=b.length;;){if(!(a<f)){Utils.throwError("Head not found");
break}c=d[b[a]];if("header"===c.role){d=c;break b}a++}d=void 0}f=la(this.graph(),d.id);e=Object.keys(f.nodes);if(1==e.length)a=null;else{b=f.links[d.id];b.type="horizontal"==b.type?"vertical":"horizontal";a=[];e={};c={};this.graph().enumerateManhattan(d.id,e,c);H(e,c,a);c=new Utils.Manhattan;e=d;e={id:"xxx",type:e.type,role:e.role,content:Utils.copyObject(e.content),x:e.x,y:e.y,w:e.w,h:e.h};c.addItem(e);e=this.render();var g=this.nextId(),h=this.items(),k;k=new ua;k.graph(c);k.render(e);k.nextId(g);
k.items(h);k.itemId("xxx");k.toInsert(f);f=k.mih01();a=a.concat(f.commands);f=f.nextId;c=xa(a,"xxx");c.fields.role="header";"vertical"==b.type&&(c.fields.x+=2*Config.METRE,za(a,c.id));b=c.fields.x-d.x;c=c.fields.y-d.y;d=a;b=-b;c=-c;e=0;for(g=d.length;e<g;)h=d[e],"nodes"==h.table&&(h.fields.x+=b,h.fields.y+=c),e++;a={commands:a,nextId:f}}return this._toggleTree=a}}this.ME=ua;this.getHorParent=J;this.setItemWidth=function(a,b,c,d,e){var f,g;f=b.graph;g=f.getItem(c);e={commands:e};var h;h=g.left&&"header"!=
g.role?!0:!1;if(h){var k,l;h=G(f,g);l=f.getEdge(h.right);c=[];if("link"==l.role)c.push(g.id);else{h=f.getVertical(h.id);l=0;for(var m=h.length;l<m;)g=f.getItem(h[l]),g.right&&(k=f.getEdge(g.right),"link"!=k.role&&(g=P(f,g),"header"!=g.role&&c.push(g.id))),l++}h=0;for(l=c.length;h<l;)m=c[h],g=f.getItem(m),aa(a,b,m,d,g.content,e),h++}else aa(a,b,c,d,g.content,e)};this.changeItem=aa;this.getSoftExpanders=na;this.copySubtree=la;this.mustFitSiblings=function(a){return"miv02"===a||"miv03"===a?!0:!1};this.getDefaultIconType=
function(a){return a in{mih03:!0,mih05:!0,mih06:!0,mih061:!0,mih062:!0,mih063:!0,mih064:!0,mih01:!0,mih02:!0,mih04:!0}?"raction":"action"}}var Mind=new MindModule;
