function PhysicalGraph(I,J,K,r){function D(a,c,d,b,e,f,g){this.name=a;this.x=c;this.y=d;this.left=b;this.top=e;this.right=f;this.bottom=g}function L(a,c,d,b,e,f,g,h,p){this.id=a;this.isLine=c;this.isVertical=d;this.x=b;this.y=e;this.head=f;this.tail=g;this.goThrough=h;this.box=p}function x(a,c,d){var b=0;c=Object.keys(c);for(var e=c.length;b<e;){var f=c[b];a.getItem(f).isLine||(d[f]=!0);b++}}function w(a,c,d){a=a.teams;return("horizontal"===d?a.left:a.up).get(c)}function E(a,c,d,b){var e=A(b);b={};
var f=a.graph;B(a,c,d,e,b,null);a=y(f,b);return{items:b,edges:a}}function A(a){var c={};return c="horizontal"===a?new D(a,"x","y","left","top","right","bottom"):new D(a,"y","x","top","left","bottom","right")}function z(a,c,d,b,e,f){var g=A(b),h={};e?c=w(a,c,b):(c="horizontal"===b?a.graph.getVertical(c):a.graph.getHorizontal(c),c=new Utils.Set(c));B(a,c,d,g,h);y(a.graph,h);x(a.graph,h,f)}function B(a,c,d,b,e){for(var f=a.graph,g=0,h=c.list,p=h.length;g<p;){var q=h[g];e[q]=!0;var n=f.getItem(q);F(a,
n.box,c.map,d,b,e);var q=d,k=b,l=n.box,m=n.touchBox;n.isLine||(n[k.x]+=q);n=k.left;k=k.right;l[n]+=q;l[k]+=q;m[n]+=q;m[k]+=q;g++}}function F(a,c,d,b,e,f){c=Utils.expandBox(c,Config.METRE);var g=Utils.copyBox(c),h=0<b?e.right:e.left;g[h]+=b;for(var h=a.graph,p=0,q=a.teams.itemIds,n=q.length;p<n;){var k=q[p];if(!(k in d)&&k in h.items){var l=h.getItem(k);if(!l.isLine||(l.isVertical?"vertical"!==e.name:"vertical"===e.name)){var m=l.box,l=e.left,u=e.top,r=e.right,v=e.bottom,t=void 0;g[u]>=m[v]?t=0:m[u]>=
g[v]?t=0:(u=m[r],v=g[l],t=g[r],m=m[l],t=0<b?t<=m||v>=m?0:c[r]>m?0:t-m:v>=u||t<=u?0:c[l]<u?0:v-u);l=t;0!==l&&(k=w(a,k,e.name),B(a,k,l,e,f))}}p++}}function G(a){var c=M.getItemCallback(a.type).makeBox(a,a.x,a.y,K);a.box=c}function H(a,c){var d=a.getNode(c.head),b=a.getNode(c.tail);if(c.isVertical){var e=b.y-d.y,b=d.x,d=d.y;c.touchBox=new Utils.Box(b-Config.TOUCH_MARGIN,d+Config.TOUCH_MARGIN,b+Config.TOUCH_MARGIN,d+e-Config.TOUCH_MARGIN);c.box=new Utils.Box(b,d,b,d+e)}else e=b.x-d.x,b=d.x,d=d.y,c.touchBox=
new Utils.Box(b+Config.TOUCH_MARGIN,d-Config.TOUCH_MARGIN,b+e-Config.TOUCH_MARGIN,d+Config.TOUCH_MARGIN),c.box=new Utils.Box(b,d,b+e,d)}function y(a,c){for(var d={},b=0,e=Object.keys(c),f=e.length;b<f;){var g=a.getItem(e[b]);g.isLine||(Utils.addNotNilToSet(d,g.left),Utils.addNotNilToSet(d,g.right),Utils.addNotNilToSet(d,g.up),Utils.addNotNilToSet(d,g.down));b++}b=0;e=Object.keys(d);for(f=e.length;b<f;)g=a.getEdge(e[b]),H(a,g),b++;return d}function C(a){a.touchBox=a.goThrough?new Utils.Box(a.x-Config.TOUCH_MARGIN,
a.y-Config.TOUCH_MARGIN,a.x+Config.TOUCH_MARGIN,a.y+Config.TOUCH_MARGIN):Utils.copyBox(a.box)}var M=I;this.graph=new Utils.Manhattan;this.rebuildCache=function(){r||(r={left:null,up:null,right:null,down:null});this.teams=this.graph.buildTeams(r)};this.insertPhysicalNode=function(a){var c="junction"===a.type;a=Utils.copyObject(a);a.goThrough=c;C(a);this.graph.addItem(a)};this.insertPhysicalEdge=function(a,c,d,b,e){a=new L(a,!0,b,null,null,c,d,!1);a.role=e;this.graph.addItem(a);H(this.graph,a)};this.findPhysicalItem=
function(a,c){for(var d=null,b=0,e=this.graph.nodes,f=Object.keys(e),g=f.length;;){if(!(b<g)){b=0;e=this.graph.edges;f=Object.keys(e);for(g=f.length;b<g;){var h=f[b],p=e[h];if(Utils.hitBox(p.touchBox,a,c)){d=h;break}b++}break}h=f[b];p=e[h];if(Utils.hitBox(p.touchBox,a,c)){d=h;break}b++}return d};this.startPhysicalDrag=function(a,c){var d,b;b=this.graph.getItem(a);b.isLine?b.isVertical?(d=null,b=b.head):(d=b.head,b=null):b=d=a;var e=null,f=null;d&&(e=w(this,d,"vertical"));b&&(f=w(this,b,"horizontal"));
this.activeUp=c.up(this,e);this.activeDown=c.down(this,e);this.activeLeft=c.left(this,f);this.activeRight=c.right(this,f)};this.physicalDrag=function(a,c){var d={},b={},e={},f={},g=this.graph;if(0!==a){var h;h=0<a?this.activeRight:this.activeLeft;h&&(e=E(this,h,a,"horizontal"),d=e.items,e=e.edges)}0!==c&&(h=0<c?this.activeDown:this.activeUp,h&&(f=E(this,h,c,"vertical"),b=f.items,f=f.edges));h={};x(g,d,h);x(g,b,h);Utils.mergeSets(e,f);return{nodes:h,edges:e}};this.deletePhysicalItem=function(a){this.graph.removeItem(a)};
this.insertPhysicalItem=function(a){a.isLine?this.insertPhysicalEdge(a.id,a.head,a.tail,a.isVertical,a.role):(G(a),this.insertPhysicalNode(a))};this.pushObjects=function(a,c,d,b,e){b=A(b);var f={};F(this,a,c,d,b,f);y(this.graph,f);x(this.graph,f,e)};this.moveDown=function(a,c,d){z(this,a,c,"vertical",!0,d)};this.moveRight=function(a,c,d){z(this,a,c,"horizontal",!0,d)};this.getTeam=function(a,c){return w(this,a,c)};this.moveAlone=function(a,c,d,b){var e=this.graph.getItem(a),f=e.box;d&&(d={},d[a]=
!0,this.pushObjects(f,d,c,"horizontal",b));e.x+=c;f.left+=c;f.right+=c;C(e);b[a]=!0;y(this.graph,b)};this.changeSize=function(a,c,d){a=this.graph.getNode(a);a.w=c;a.h=d;G(a);C(a)};this.moveDownNoTeam=function(a,c,d){z(this,a,c,"vertical",!1,d)};this.moveRightNoTeam=function(a,c,d){z(this,a,c,"horizontal",!1,d)};(function(a,c){for(var d=0,b=c.nodes,e=Object.keys(b),f=e.length;d<f;){var g=e[d],g=Utils.copyObject(b[g]);a.insertPhysicalItem(g);d++}d=0;b=c.edges;e=Object.keys(b);for(f=e.length;d<f;)g=
e[d],g=Utils.copyObject(b[g]),a.insertPhysicalItem(g),d++;a.rebuildCache()})(this,J,r)};
