function TabGen4(E){function K(a,c,b){var d;d=a[c];d||(d=[],a[c]=d);d.push(b)}function B(a){var c=0,c=typeof a;if("number"===c||"boolean"===c||"string"===c||"undefined"===c||null===a)return a;if(isArray(a))return a.slice(0);for(var c={},b=0,d=Object.keys(a),f=d.length;b<f;){var h=d[b];c[h]=B(a[h]);b++}return c}function F(a,c,b){if("id"==b)m("id cannot be a link");else if(b in a)m('Field "'+b+'" is already a link in table "'+c+'"');else return c={field:b},a[b]=c}function C(a){var c,b;if(c=a.op){if(b=
n[c])return a=b(a);m('Unknown op: "'+c+'"')}else m("op is missing")}function e(a,c){var b;b=a[c];if(void 0==b)m('Field "'+c+'" is missing in action "'+a.op+'"');else return b}function D(a){var c;if(a in y)return a in z?c=z[a]:(c={},z[a]=c),c;m('createLink: table "'+a+'" does not exist')}function u(a,c,b){var d;d=y[a];if(void 0==d)m(b+': table "'+a+'" does not exist');else if(d=d[c],void 0==d)m(b+': record with key "'+c+'" does not exist in table "'+a+'"');else return d}function L(a,c,b){a=b[a.listField].indexOf(c);
return[b.id,a]}function M(a,c,b){var d;(d=a[c])?delete d[b]:(d={},a[c]=d)}function m(a){throw Error(a);}function N(a,c){for(var b=0,d=Object.keys(a),f=d.length;b<f;){var h=d[b],e=a[h];"undefined"==typeof e?delete c[h]:c[h]=e;b++}}function O(a,c,b,d){var f,h,e,g,l,k;if(l=z[a]){g=[];a=[];k={};var x=0;h=Object.keys(b);for(var n=h.length;x<n;){f=h[x];e=l[f];var r=void 0,v=void 0,q=void 0,A=void 0,p=void 0,t=A=p=v=r=void 0,q=void 0,p=0,p=b,A=k,r=d,q=p[f],r=r[f];q!==r&&(e?(p=e.type,"ptr-list"===p||"ptr-map"===
p||"ptr-simple"===p?(p=g,t=a,q?("string"==typeof q?(v=q,q=-1):(v=q[0],q=q[1]),v=u(e.listTable,v,"foreign key check"),A[f]=v,A=[v,e.type,e.listField,q],p.push(A)):A[f]=q,r&&(A=[r,e.type,e.listField],t.push(A))):m('Field "'+f+'" is a link that cannot be set')):A[f]=q);x++}N(k,d);k=0;for(x=g.length;k<x;)e=g[k],b=e[0],l=e[1],f=e[2],h=e[3],l=H[l],l(b,f,h,d,c),k++;g=0;for(k=a.length;g<k;)e=a[g],b=e[0],l=e[1],f=e[2],l=I[l],l(b,f,d,c),g++}else N(b,d)}var G=this,n={},t={},y={},z={},J={},H={},I={};this.state=
y;this.links=z;this.nextId=1;this.dispatch=C;this.getState=function(){return y};this.setState=function(a){};this.subscribe=function(a){};this.get=function(a,c){return u(a,c,"get")};this.getRowOrNull=function(a,c){var b;b=y[a];if(void 0==b)m('getRowOrNull: table "'+a+'" does not exist');else return b=b[c],void 0==b?null:b};this.setNextId=function(a){G.nextId=a};this.createTable=function(a){a in y?m('createTable: table name "'+a+'" is not unique'):y[a]={}};this.createLink=function(a,c,b,d,f){var e,
w,g,l;w=[a,c,b,d,f].join("|");if(!(w in J))if("list"===f)l="ptr-list",f="list",g=D(a),e=D(b),g=F(g,a,c),e=F(e,b,d),g.listField=d,e.ptrField=c,g.listTable=b,e.ptrTable=a,g.type=l,e.type=f,J[w]=!0;else if("map"===f)l="ptr-map",f="map",g=D(a),e=D(b),g=F(g,a,c),e=F(e,b,d),g.listField=d,e.ptrField=c,g.listTable=b,e.ptrTable=a,g.type=l,e.type=f,J[w]=!0;else if("simple"===f){l="ptr-simple";f="simple";g=D(a);e=D(b);g=F(g,a,c);a:{var k;if("id"==d)m("id cannot be a link");else if(d in e)if(k=e[d],"simple"==
k.type){e=k;break a}else m('Field "'+d+'" is already a link in table "'+b+'"');else{k={field:d};e=e[d]=k;break a}e=void 0}g.listField=d;e.ptrField=c;g.listTable=b;e.ptrTable=a;g.type=l;e.type=f;J[w]=!0}else m('Unsupported link type "'+f+'". Should be list or map.')};this.buildUndo=function(a){var c=a.op;if(c){var b=t[c];if(b)return b(a);m('Unknown op: "'+c+'"')}else m("op is missing")};this.insert=function(a,c,b){return C({op:"insert",table:a,id:c,values:b})};this.update=function(a,c,b){return C({op:"update",
table:a,id:c,values:b})};this.remove=function(a,c){return C({op:"remove",table:a,id:c})};this.set=function(a,c,b,d){a={op:"update",table:a,id:c,values:{}};a.values[b]=d;return C(a)};this.push=function(a,c,b,d){return C({op:"push",table:a,id:c,field:b,value:d})};n.insert=function(a){var c,b,d,f;f=e(a,"values");c=a.id;c||(c=G.nextId,G.nextId++);c=c.toString();d=e(a,"table");b=y[d];if(void 0==b)m('insert: table "'+d+'" does not exist');else if(c in b)m('insert: record with key "'+c+'" already exists in table "'+
d+'"');else{a={};O(d,c,f,a);a.id=c;b[c]=a;c=0;if(f=z[d]){d=0;b=Object.keys(f);for(var h=b.length;d<h;){var w=b[d];c=f[w];w in a||(c=c.type,"list"===c?a[w]=[]:"map"===c&&(a[w]={}));d++}}return a}};n.remove=function(a){var c,b,d;c=e(a,"id");d=e(a,"table");b=y[d];if(void 0==b)m('remove: table "'+d+'" does not exist');else{if(a=b[c])if(delete b[c],c=z[d]){var f,h=0;b=a.id;d=0;for(var w=Object.keys(a),g=w.length;d<g;){var l=w[d],k=a[l];if(k&&(f=c[l]))if(h=f.type,"ptr-list"===h)f=k[f.listField],k=void 0,
k=f.indexOf(a),-1!=k&&f.splice(k,1);else if("ptr-map"===h)f=k[f.listField],delete f[b];else if("ptr-simple"===h)k[f.listField]=null;else if("list"===h)for(var h=0,l=k,x=l.length;h<x;)k=l[h],k[f.ptrField]=null,h++;else if("map"===h)for(var h=0,l=k,x=Object.keys(l),u=x.length;h<u;)k=l[x[h]],k[f.ptrField]=null,h++;else{if("simple"!==h)throw"Unexpected switch value: "+h;m('Cannot delete: active link on "'+l+'"')}d++}}return a}};n.update=function(a){var c,b,d;d=e(a,"values");c=e(a,"id");b=e(a,"table");
a=u(b,c,"update");O(b,c,d,a);return a};n.madd=function(a){var c,b,d,f;c=e(a,"field");d=e(a,"key");f=e(a,"value");b=e(a,"id");a=e(a,"table");b=u(a,b,"mapAdd");a=b[c];a||(a={},b[c]=a);a[d]=f;return b};n.mremove=function(a){var c,b,d;c=e(a,"field");d=e(a,"key");b=e(a,"id");a=e(a,"table");b=u(a,b,"mapRemove");M(b,c,d);return b};n.push=function(a){var c,b,d;c=e(a,"field");d=e(a,"value");b=e(a,"id");a=e(a,"table");b=u(a,b,"arrayPush");K(b,c,d);return b};n.pop=function(a){var c,b;c=e(a,"field");b=e(a,"id");
a=e(a,"table");b=u(a,b,"arrayPop");(c=b[c])&&c.pop();return b};n.aadd=function(a){var c,b,d,f;c=e(a,"field");d=e(a,"index");f=e(a,"value");b=e(a,"id");a=e(a,"table");b=u(a,b,"arrayAdd");a=b[c];a||(a=[],b[c]=a);a.splice(d,0,f);return b};n.aremove=function(a){var c,b,d;c=e(a,"field");d=e(a,"index");b=e(a,"id");a=e(a,"table");b=u(a,b,"arrayRemove");(c=b[c])&&c.splice(d,1);return b};n.noop=function(a){return null};t.insert=function(a){return[{op:"remove",table:a.table,id:a.id}]};t.remove=function(a){var c,
b,d,f,h,m,g;c=e(a,"id");a=e(a,"table");h=u(a,c,"undo remove");m=[];if(d=z[a]){g={};for(var l=0,k=Object.keys(h),x=k.length;l<x;){var n=k[l];f=h[n];if((b=d[n])&&f){var r=n,v=f;f=g;var n=m,q=h,t=void 0,p=void 0,p=0,t=q.id,p=b.type;if("list"===p)for(r=0,q=v.length;r<q;)p=v[r],f={},f[b.ptrField]=t,p={op:"update",table:b.ptrTable,id:p.id,values:f},n.push(p),r++;else if("map"===p)for(var r=0,q=Object.keys(v),y=q.length;r<y;)p=v[q[r]],f={},f[b.ptrField]=t,p={op:"update",table:b.ptrTable,id:p.id,values:f},
n.push(p),r++;else if("ptr-list"===p)f[r]=L(b,q,v);else if("ptr-map"===p||"ptr-simple"===p)f[r]=v.id}else g[n]=B(f);l++}delete g.id}else d=B(h),delete d.id,g=d;m.unshift({op:"insert",table:a,id:c,values:g});return m};t.update=function(a){var c,b,d,f,h,m;f=e(a,"values");c=e(a,"id");h=e(a,"table");a=u(h,c,"undo update");m={};if(d=z[h])for(var g=0,l=Object.keys(f),k=l.length;g<k;){var n=l[g];f=a[n];b=d[n];m[n]=b&&f?"ptr-list"==b.type?L(b,a,f):f.id:B(f);g++}else for(d=0,g=Object.keys(f),b=g.length;d<
b;)n=g[d],f=a[n],m[n]=B(f),d++;return[{op:"update",table:h,id:c,values:m}]};t.madd=function(a){var c,b,d;c=e(a,"field");d=e(a,"key");b=e(a,"id");return[{table:e(a,"table"),op:"mremove",id:b,field:c,key:d}]};t.mremove=function(a){var c,b,d,f;c=e(a,"field");d=e(a,"key");b=e(a,"id");a=e(a,"table");f=u(a,b,"undo mapRemove");f=B(f[c][d]);return[{table:a,op:"madd",id:b,field:c,key:d,value:f}]};t.push=function(a){var c,b;c=e(a,"field");b=e(a,"id");return[{table:e(a,"table"),op:"pop",id:b,field:c}]};t.pop=
function(a){var c,b,d;b=e(a,"field");d=e(a,"id");a=e(a,"table");if((c=u(a,d,"undo arrayPop")[b])&&0!=c.length)return c=c[c.length-1],b={table:a,op:"push",id:d,field:b,value:B(c)},[b];m("undo for arrayPop: nothing to pop: "+a+" "+d+" "+b)};t.aadd=function(a){var c,b,d;c=e(a,"field");d=e(a,"index");b=e(a,"id");return[{table:e(a,"table"),op:"aremove",id:b,field:c,index:d}]};t.aremove=function(a){var c,b,d,f;b=e(a,"field");f=e(a,"index");d=e(a,"id");a=e(a,"table");c=u(a,d,"undo arrayRemove")[b];if(!c||
f>=c.length)m("undo for arrayRemove: bad index: "+a+" "+d+" "+b+" "+f);else return c=c[f],b={table:a,op:"aadd",id:d,field:b,index:f,value:B(c)},[b]};H["ptr-list"]=function(a,c,b,d,e){-1==b?K(a,c,d):(e=a[c],e||(e=[],a[c]=e),e.splice(b,0,d))};H["ptr-map"]=function(a,c,b,d,e){b=a[c];b||(b={},a[c]=b);b[e]=d};H["ptr-simple"]=function(a,c,b,d,e){a[c]=d};I["ptr-list"]=function(a,c,b,d){a=a[c];b=a.indexOf(b);-1!=b&&a.splice(b,1)};I["ptr-map"]=function(a,c,b,d){M(a,c,d)};I["ptr-simple"]=function(a,c,b,d){a[c]=
null};E&&"undefined"!=typeof window&&(window.gdata||(window.gdata={}),E in window.gdata?m('Database name "'+E+'" is not unique'):(window.gdata[E]=G,G.name=E))}"undefined"!=typeof module&&(module.exports=TabGen4);
