function ViewWidget(t,ba,d,k,Q){function p(a,b){this.x=a;this.y=b}function R(a,b){this.w=a;this.h=b}function A(a,b){var c=a.x,d=a.y,g=d/e-f.y,c=Math.round(c/b-(c/e-f.x)),d=Math.round(d/b-g);return new p(c,d)}function B(a,b){a.addEventListener("mousewheel",b,!1);a.addEventListener("DOMMouseScroll",b,!1)}function C(a,b){var c=Math.round((a-D)/e-f.x),d=Math.round((b-E)/e-f.y);return{x:c,y:d,cx:a,cy:b}}function x(a,b){var c=b+F,d=Math.round(e*(a+F+f.x)),c=Math.round(e*(c+f.y));return new Utils.Point(d,
c)}function r(){var a=h.getBackground(),a=a||Theme.getBackground();d.style.background!=a&&(d.style.background=a);var a=f,b=d.getContext("2d");b.setTransform(1,0,0,1,0,0);b.clearRect(0,0,d.width,d.height);var c=e*g;b.scale(c,c);b.translate(a.x,a.y);h.setTransform(a.x,a.y,e,g);h.draw(b)}function G(){h.setZoom(e,g);h.redrawCache();y()}function H(){var a=d.getBoundingClientRect();D=a.left;E=a.top;var b=Math.max(10,a.width),a=Math.max(10,a.height);return new R(b,a)}function I(a){J(a,!0)}function J(a,b){b&&
CallTrace.reset();l(a);m.x=a.clientX;m.y=a.clientY;var c=u(a);a.ctrlKey&&(c.button=2);CallTrace.add("vw:mouseDown",[c.x,c.y,c.cx,c.cy,c.button]);h.mouseDown(c)}function S(a){CallTrace.add("vw:mouseLeave",[]);0!=a.buttons&&v(a)}function K(a){l(a);var b=a.clientX-m.x,c=a.clientY-m.y,d=u(a),b={x:d.x,y:d.y,dx:b/e,dy:c/e,cx:a.clientX,cy:a.clientY};m.x=a.clientX;m.y=a.clientY;h.mouseMove(b)}function v(a){l(a);a=u(a);CallTrace.add("vw:mouseUp",[a.x,a.y,a.cx,a.cy,a.button]);h.mouseUp(a)}function L(a){var b=
Math.max(-1,Math.min(1,a.wheelDelta||-a.detail));l(a);a={delta:b,shiftKey:a.shiftKey,ctrlKey:a.ctrlKey||a.metaKey};CallTrace.add("vw:mouseWheel",[a.delta,a.shiftKey,a.ctrlKey]);h.mouseWheel(a)}function l(a){a.preventDefault?a.preventDefault():a.returnValue=!1}function y(){new p(f.x,f.y);var a=H();M=a.w;var b=N=a.h;d.width=a.w*g;d.height=b*g;r();b=a.h;k.width=a.w*g;k.height=b*g}function T(a,b,c){var d=this;this.timers[a]=t.setTimeout(function(){delete d.timers[a];b(a);y()},c)}function U(){for(var a=
0,b=Object.keys(this.timers),c=b.length;a<c;)this.remove(b[a]),a++}function V(a){var b=this.timers[a];delete this.timers[a];t.clearInterval(b)}function u(a){var b=C(a.clientX,a.clientY);b.button=a.button;b.dx=a.dx/e;b.dy=a.dy/e;return b}function W(a){CallTrace.add("vw:touchcancel",[]);DTools.print("cancel touch vw");l(a);q.touchcancel(a)}function X(a){CallTrace.add("vw:touchend",[a]);DTools.print("end touch vw");l(a);q.touchend(a)}function Y(a){DTools.print("move touch vw");l(a);q.touchmove(a)}function Z(a){CallTrace.reset();
CallTrace.add("vw:touchstart",[a]);DTools.clear();DTools.print("start touch vw");l(a);q.touchstart(a)}function z(a,b){b=Math.max(.2,Math.min(3,b));f=A(a,b);e=b;r()}function O(){var a;for(a=0;a<w.length;){var b=w[a];if(b>e){z(m,b);break}a++}}function P(){var a;for(a=w.length-1;0<=a;){var b=w[a];if(b<e){z(m,b);break}a--}}var aa=this,M=0,N=0,q=null,n=null,g=1,f=new p(0,0),D=0,E=0,e=1;new p(0,0);var m=new p(0,0),h=null,w=[.25,1/3,.4,.5,.6,2/3,.7,.8,.9,1,1.2,1.25,1.5,1.75,2],F=0;(function(){g=HtmlUtils.getRetinaFactor();
q=new Multitouch(aa);d.addEventListener("mousedown",I);d.addEventListener("mousemove",K);d.addEventListener("mouseup",v);d.addEventListener("touchstart",Z);d.addEventListener("touchmove",Y);d.addEventListener("touchend",X);d.addEventListener("touchcancel",W);B(d,L);B(k,L);d.oncontextmenu=function(){return!1};d.onmouseleave=S})();this.rebuild=y;this.redraw=function(){r()};this.setPayload=function(a){h=a;q.setBeh(h);h.setZoom(e,g)};this.pan=function(a,b){f=new p(a,b);t.requestAnimationFrame(r)};this.Timers=
function(){this.timers={};this.add=T;this.clear=U;this.remove=V};this.setTimeout=setTimeout;this.clientToDiagram=C;this.diagramToClient=x;this.toDiagram=u;this.incomingClick=function(a){CallTrace.add("vw:incomingClick",[]);J(a,!1);v(a)};this.scrollBy=function(a,b){f.x+=a;f.y+=b;t.requestAnimationFrame(r)};this.finishScroll=function(){};this.zoomBy=function(a){0<a?O():P()};this.finishZoom=G;this.zoomTo=function(a){var b=H(),b=new p(b.w/2,b.h/2);f=A(b,a);e=a;G()};this.zoomIn=O;this.zoomOut=P;this.getZoom=
function(){return e};this.zoomAt=z;this.getRetinaFactor=function(){return g};this.showOver=function(){k.style.display="inline-block"};this.hideOver=function(){k.style.display="none";k.getContext("2d").clearRect(0,0,k.width,k.height)};this.selectBlock=function(a){var b=k.getContext("2d");n&&b.clearRect(n.left-3,n.top-3,n.right-n.left+6,n.bottom-n.top+6);if(a){var c=x(a.left,a.top);a=x(a.right,a.bottom);b.lineWidth=2*g;c.x*=g;c.y*=g;a.x*=g;a.y*=g;c=new Utils.Box(c.x,c.y,a.x,a.y);a=c.right-c.left;var d=
c.bottom-c.top;b.strokeStyle=Q.getDiaLine();b.strokeRect(c.left,c.top,a,d)}n=c};this.mouseDown=I;this.mouseMove=K;this.mouseUp=v;this.setCursor=function(a){d.style.cursor=a};this.getVisibleBox=function(){var a=-f.x,b=-f.y;return new Utils.Box(a,b,a+M/e,b+N/e)}};
